### ISSUE TITLE
Upgrade to Android Studio 4.0 release APK then throw [Cause: path may not be null or empty string. path='']

### ISSUE THREAD

**Issue by itenl** [getsentry/sentry-react-native#912] opened 2020-06-05 03:59 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.3.8

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

- [x]  (`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

or

- [ ]  (`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**

 Use Android Studio 4.0 release apk throw error [ Cause: path may not be null or empty string. path='' ], but i delete the [apply from: "../../node_modules/@sentry/react-native/sentry.gradle"] it working now and build release APK everything is normal,  and try test throw error in RN everything is normal, so why?

Android Studio Version:
```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1237M
Cores: 8
Registry: ide.new.welcome.screen.force=true
Non-Bundled Plugins: 
```

**Steps to reproduce:**
- Step 1: Android Studio 3.4.1 build release is okay.
- Step 2: upgrade to Android Studio 4.0 build release throw error[Cause: path may not be null or empty string. path='']
- Step 3: delete [apply from: "../../node_modules/@sentry/react-native/sentry.gradle"] build release is okay.

**Actual result:**

[throw error: Cause: path may not be null or empty string. path='']

**Expected result:**

[build release apk is okay.]

**Comment by marandaneto** [comment] 2020-06-05 08:25
hey @itenl thanks for raising this.

did you upgrade also your Android Gradle Plugin to v4.0.0 or only AS? thanks.

**Comment by itenl** [comment] 2020-06-08 02:24
@marandaneto Currently Gradle Plugin use [classpath 'com.android.tools.build:gradle:3.3.0'], did't upgrade Gradle Plugin.

**Comment by marandaneto** [comment] 2020-06-08 06:51
this might be related to getsentry/sentry-android-gradle-plugin/issues/19

it's a curious case though, you don't need AS to build your project, but only Gradle and the Android tooling (AGP).
so if you do `./gradlew build` on its own terminal, do you still experience the same problem?

Did you upgrade your Gradle version?

could you copy-paste the whole log? thanks.

**Comment by itenl** [comment] 2020-06-08 08:12
![image](https://user-images.githubusercontent.com/16585374/84004675-7faa1000-a99e-11ea-8062-b0c077597050.png)

I'm use command [./gradlew assembleproductionCashCashRelease --stacktrace --info] is working now, howerer [Build - Generate Signed Bundle / APK...] to make Release in AS an throw error.

**Comment by TianHeZheng** [comment] 2020-06-08 08:25
@marandaneto 
I also encountered the same error, Gradle plugin version 3.3.0, Gradle version 4.10.1. And I cannot build successfully on AndroidStudio3.6 and AndroidStudio4.0

**Comment by marandaneto** [comment] 2020-06-08 11:05
ok, it works when building outside of AS though.
the reason is simple, AS 4.x builds only the necessary build types/flavors/ABIs for the attached device/emulator but the plugin tries to do its job for all the configurations, those files don't exist yet.

We'll figure this out, thanks.

**Comment by itenl** [comment] 2020-06-09 15:28
@marandaneto Got it thx, btw, I deleted [apply from: "../../node_modules/@sentry/react-native/sentry.gradle"] when I released the apk, sentry can still be used in RN, so will deleting it affect me?

**Comment by marandaneto** [comment] 2020-06-09 20:11
@galaxy-zheng is it the same error using AS 3.6?

@itenl you probably you won't get your stack traces demangled, as this plugin does the uploading of source maps.

you could also generate your signed bundles using command line, the problem is only when using AS.

**Comment by galaxy-zheng** [comment] 2020-06-10 03:19
@marandaneto  not sure ！

**Comment by itenl** [comment] 2020-06-10 06:10
@marandaneto Okay, but i use command [sentry-cli releases -o organization-name -p project-name files prod@6.0.6 upload-sourcemaps /Users/UserName/Code/project-rn/bundles/android --url-prefix="~/assets/] upload bundle and used Sentry.setRelease('prod@6.0.6') to set the version number to prod@6.0.6, But still shows [Source code was not found Url app:///index.android.bundle], If you still need any information, I can continue to provide.

unzip apk get bundle file path:[ apk-root/assets/index.android.bundle ]

![image](https://user-images.githubusercontent.com/16585374/84232536-0ee03080-ab23-11ea-8f9d-512180709e4b.png)


![image](https://user-images.githubusercontent.com/16585374/84232353-b01ab700-ab22-11ea-8931-323d4fe5ec78.png)
![image](https://user-images.githubusercontent.com/16585374/84232603-36cf9400-ab23-11ea-91dd-24464208461a.png)

**Comment by marandaneto** [comment] 2020-06-10 07:07
@itenl you don't need to use `sentry-cli` manually as the SDK does it automatically, it needs to hook in the build lifecycle in order to do its job properly.
removing `sentry.gradle` as you did is the cause of your errors for sure.

**Comment by itenl** [comment] 2020-06-10 07:48
@marandaneto Sure, I agree with u said, if use AS release APK maybe can upload `index.android.bundle.map`,but i have React-Native-Code-Push need `sentry-cli` manually upload `index.android.bundle.map`.

**Comment by marandaneto** [comment] 2020-06-14 08:02
I see, I don't know how the code push works, so I'll leave this one to @HazAT or @jennmueng

**Comment by jennmueng** [comment] 2020-06-15 09:31
@itenl I see that the sourcemaps do not have a distribution set, the sourcemap will have to exactly match both the release and the dist set on the event to be symbolicated correctly. You can see the dist on the events as they'll have a `dist` tag.

You can do that by adding a --dist argument to the cli command.
```sh
--dist $DIST

# Example:
--dist 3.0.0.0
```
Also, to make sure with codepush builds the dist value is matching, you should also use `Sentry.setDist()` in the code.

**Comment by itenl** [comment] 2020-06-16 07:57
@jennmueng 
- I already try to, but not working, very depressing.

- Sentry cli command `sentry-cli releases -o organization-name -p project-name files 5.0.7 upload-sourcemaps /Users/UserName/Code/project-rn/bundles/android --dist 91507`


![image](https://user-images.githubusercontent.com/16585374/84746984-45b5bb00-afe9-11ea-9030-ad1fde78cfb3.png)

![image](https://user-images.githubusercontent.com/16585374/84747089-6ed64b80-afe9-11ea-8248-159ab879f4e9.png)

![image](https://user-images.githubusercontent.com/16585374/84746936-37679f00-afe9-11ea-88f9-9c22cc011960.png)

![image](https://user-images.githubusercontent.com/16585374/84747275-a0e7ad80-afe9-11ea-8f9c-a3b5f920b487.png)

**Comment by HazAT** [comment] 2020-06-16 08:37
@itenl Please keep stick to the topic, the initial reason you opened the issue seems to be solved that's why I am closing this issue now.
To answer you next problem you posted, while `release` and `dist` match you also need to make sure that the filename matches with the one uploaded in artifacts. So in your case `index.js` can't be found in the artifacts. Either use the `RewriteFrames` Integration to fix this or make sure the bundle you use is called `index.android.bundle`.

**Closed by HazAT** 2020-06-16 08:37 UTC
Labels: :beetle: Bug, android, code-push, gradle
