### ISSUE TITLE
Getting "No platform selected" from sentry-wizard

### ISSUE THREAD

**Issue by alexstoyanov** [getsentry/sentry-react-native#1386] opened 2021-03-10 09:39 UTC
### Environment

How do you use Sentry?
Sentry SaaS

Which SDK and version?
@sentry/react-native: 2.2.2
react-native: 0.63.3

### Steps to Reproduce

1. Follow the installation guide and running 
npx @sentry/wizard -i reactNative -p android
2. Getting this:
`✅ Patched build.gradle file.
Error: No platform selected
    at ReactNative.MobileProject.getPlatforms (/Applications/MAMP/htdocs/shkolo/shkolo-mobileapp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/MobileProject.js:65:19)
    at ReactNative._patchJs (/Applications/MAMP/htdocs/shkolo/shkolo-mobileapp/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:224:14)
    at /Applications/MAMP/htdocs/shkolo/shkolo-mobileapp/node_modules/@sentry/wizard/dist/lib/Helper/File.js:28:45
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

🎉  Successfully set up Sentry for your project 🎉`
3. But android/sentry.properties is not generated
and after that when I try to build the android app I get:
`
> Task :app:bundleReleaseJsAndAssets_SentryUpload_89 FAILED
error: An organization slug is required (provide with --org)
`
### Expected Result

The Sentry setup should be successful and the app should be build successfully

### Actual Result

I get both errors described in the steps.

**Comment by HazAT** [comment] 2021-03-10 13:39
Thanks for reporting, we are taking a look

**Comment by thatguyyoulove** [comment] 2021-03-17 18:07
I am seeing the exact same issue. Project previously had v2.0.0 setup in November and everything worked well. After updating via yarn to 2.3.0 I started getting compile issues in Android. Wizard --uninstall would fail with ENAMETOOLONG when trying to revert the iOS project, so I just reverted my initial sentry install commit, cleaned build folders, ran yarn, etc. Then when trying to re-add sentry using the current version and wizard I get the same error as the OP.

@sentry/react-native: 2.3.0
react-native: 0.63.4

**Comment by TheRagnar** [comment] 2021-03-24 12:17
+1

**Comment by RenatoSerra22** [comment] 2021-03-25 19:33
Facing the same issue, 

"@sentry/react-native": "^2.4.0"
"react-native": "~0.63.4"

This would likely be a reason source maps are not being uploaded right?

**Comment by it-hienvv** [comment] 2021-03-29 06:54
The same issue

**Comment by hanselsen** [comment] 2021-03-29 11:30
Same here

**Comment by NhanTranThanh** [comment] 2021-03-30 03:58
Same here

**Comment by Zakyyy** [comment] 2021-04-08 12:00
same here

**Comment by victoriaSh** [comment] 2021-04-12 00:39
Had the same issue.
Ran `npm i --save-dev @sentry/wizard@1.1.4` as @hanselsen said.
But after that I got: 
```
✅ Patched build.gradle file.
✅ Patched App.js file.
✅ Added sentry.properties file to android
Successfully set up android for react-native
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (node:fs:1507:5)
    at {projectdir}/node_modules/@sentry/wizard/dist/lib/Helper/File.js:23:20
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

🎉  Successfully set up Sentry for your project 🎉
```
And "An organization slug is required" error on building project.

Then I just copied sentry.properties from android to ios directory and everything works fine.

**Comment by hanselsen** [comment] 2021-04-12 12:59
Indeed as @victoriaSh said, I too am stuck on this new TypeError.
As both version 1.2.3 and 1.1.4 are crashing, we should use 1.2.3 and try to fix the "No platform selected" issue.
Is there anyone from Sentry that can confirm that this is under investigation?

**Comment by hanselsen** [comment] 2021-04-12 14:44
I decided not to be lazy and used [the manual configuration](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/). It is now working for me. Hopefully other people will get to enjoy the wizard.

**Comment by bruscantini** [comment] 2021-04-19 15:46
I also get this even though it ssaid "Successfully set up Sentry for your project":
```
Error: No platform selected
    at ReactNative.MobileProject.getPlatforms (/Users/pure2maestro/code/ember-app/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/MobileProject.js:65:19)
    at ReactNative._patchJs (/Users/pure2maestro/code/ember-app/node_modules/@sentry/wizard/dist/lib/Steps/Integrations/ReactNative.js:224:14)
    at /Users/pure2maestro/code/ember-app/node_modules/@sentry/wizard/dist/lib/Helper/File.js:28:45
    at process._tickCallback (internal/process/next_tick.js:68:7)
{
	"message": "Expected \"/*\", \"//\", or \"{\" but \"u\" found.",
	"expected": [
		{
			"type": "literal",
			"text": "//",
			"ignoreCase": false
		},
		{
			"type": "literal",
			"text": "/*",
			"ignoreCase": false
		},
		{
			"type": "literal",
			"text": "{",
			"ignoreCase": false
		}
	],
	"found": "u",
	"location": {
		"start": {
			"offset": 0,
			"line": 1,
			"column": 1
		},
		"end": {
			"offset": 1,
			"line": 1,
			"column": 2
		}
	},
	"name": "SyntaxError"
}
```
I can't even "pod install" now. Throws this:

```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
              if config.name == 'Staging'
                  config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
                  config.build_settings['CONFIGURATION_BUILD_DIR'] = '$(BUILD_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
              end
  end
  installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              if config.name == 'Staging'
                  config.build_settings['CONFIGURATION_TEMP_DIR'] = '$(PROJECT_TEMP_DIR)/Release$(EFFECTIVE_PLATFORM_NAME)'
                  config.build_settings['PODS_CONFIGURATION_BUILD_DIR'] = '${PODS_BUILD_DIR}/Release$(EFFECTIVE_PLATFORM_NAME)'
              end
          end
  end
end
```

### Error

```
NoMethodError - undefined method `[]' for nil:NilClass
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.1/lib/xcodeproj/project.rb:265:in `new_from_plist'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.1/lib/xcodeproj/project.rb:212:in `initialize_from_file'
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.17.1/lib/xcodeproj/project.rb:112:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1177:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1176:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:1171:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer/analyzer.rb:106:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:410:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/installer.rb:156:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by KinanKazmi** [comment] 2021-05-10 05:46
Same issue here.

**Comment by hanselsen** [comment] 2021-05-10 06:03
I can confirm that the PR 105 fixes the issue. Thanks!

**Comment by KinanKazmi** [comment] 2021-05-10 06:11
@hanselsen how can i get the version with that PR merged ?

**Comment by KinanKazmi** [comment] 2021-05-10 06:31
It says last update was 6 days ago. I just tried it last hour.

**Comment by jennmueng** [comment] 2021-05-10 06:33
@KinanKazmi Did you actually update? This issue does not exist anymore.

**Closed by jennmueng** 2021-05-10 06:33 UTC
Labels: Status: Investigating

**Comment by KinanKazmi** [comment] 2021-05-10 06:36
@jennmueng i just installed it an hour ago and got that error.

**Comment by jennmueng** [comment] 2021-05-10 06:38
> It says last update was 6 days ago. I just tried it last hour.
> […](#)

If it still occurs please provide a reproduction

**Comment by KinanKazmi** [comment] 2021-05-10 06:41
<img width="1141" alt="Screenshot 2021-05-10 at 11 40 01 AM" src="https://user-images.githubusercontent.com/20215123/117616426-8f207300-b184-11eb-863c-185f8854e415.png">

**Comment by KinanKazmi** [comment] 2021-05-10 06:44
@hanselsen some of my packages dont exist on yarn so that doesn't work at all.

**Comment by KinanKazmi** [comment] 2021-05-10 07:31
@jennmueng can you confirm if i need to provide more info for this ?

**Comment by hanselsen** [comment] 2021-05-10 07:46
@KinanKazmi 
`npm remove --save @sentry/wizard`
`npm install --save @sentry/wizard@1.2.7`

**Comment by jennmueng** [comment] 2021-05-10 08:03
@KinanKazmi if it says that it patched the files successfully, you should be good. I will check why the error still throws if I can reproduce your issue.

**Comment by KinanKazmi** [comment] 2021-05-10 08:15
@jennmueng it actually broke my xcode project. The xCode cant even open the project. Luckily i had Git backup so i restored it. Then pod install caused more issues. Updated cocapods and still no difference.
Note: I'm using the latest Mac OS and Xcode.

**Comment by jennmueng** [comment] 2021-05-10 08:43
@KinanKazmi Can you provide a reproduction repo? Looks like some edge case as it’s solved for others.

**Comment by KinanKazmi** [comment] 2021-05-17 03:46
@jennmueng sorry i forgot to respond here, yes that worked. Thanks a bunch!
