### ISSUE TITLE
Document used sentry-android version in changelog

### ISSUE THREAD

**Issue by pvegh** [getsentry/sentry-react-native#3565] opened 2024-01-29 14:12 UTC
since this library uses it like: api 'io.sentry:sentry-android:6.34.0'
it's important in the release notes/changelog

Also isn't 6 outdated?
In a hybrid project we're updating https://github.com/getsentry/sentry-android-gradle-plugin/releases which is currently using SDK 7.2. This leads to 2 versions which can lead to problems but at least uncertanity about actually used versions.

**Comment by krystofwoldrich** [comment] 2024-01-30 16:58
Hi @pvegh,
I'll close this as a duplicate of https://github.com/getsentry/sentry-react-native/issues/3570.

Every time we upgrade the undelaying dependencies we include a note about it. 
- https://github.com/getsentry/sentry-react-native/releases/tag/5.14.0

**Closed by krystofwoldrich** 2024-01-30 16:58 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
