### ISSUE TITLE
[DebugSymbolicator] Improve source context resolution to avoid extra 404 http requests 

### ISSUE THREAD

**Issue by nabati** [getsentry/sentry-react-native#1887] opened 2021-11-12 09:33 UTC
### Environment

iOS Simulator
Sentry SaaS.

react-native-sdk 3.2.3

### Steps to Reproduce

For some reason, enabling sentry while enabling network inspect in react native debugger, I get a lot of false positives in the list of requested network resources. It seems Sentry initiates fetching the source for some files (?). When I disable Sentry, the requests and associated errors disappear. 

It seems like Sentry is using trial and error to find the source code, and thus creating a lot of false positives in the logs? 

![image](https://user-images.githubusercontent.com/1499050/141444674-0460eb73-0a26-4ab2-b90d-542d935fa32b.png)

Note that it also is successful in finding context.ts at some point. 

Tested urls
Failed
```http://localhost:8081//Users/xxxx/Projects/mevisio-native-app/src/context.ts```
```http://localhost:8081/context.ts```

Successful
```http://localhost:8081/src/context.ts```

### Expected Result

To not see these failed network requests when checking the network requests in react native debugger.

**Comment by marandaneto** [comment] 2021-11-12 09:39
@nabati thanks for reporting, is it debug or release mode? if debug, can you try release mode?

@jennmueng could it be related to https://github.com/getsentry/sentry-react-native/issues/1346 ?

**Comment by jennmueng** [comment] 2021-11-17 15:44
@marandaneto Yep, looks related to #1346. Looks like it's time we revisit the debug symbolicator integration.

**Comment by skjolber** [comment] 2024-03-11 12:08
Could this be an issue of port forwarding, i.e. 

```
adb reverse tcp:8080 tcp:8080
```

gives

```
Error: Unable to resolve module ./http://localhost:8081/index from /home/thomas/entur/git/abt-mobile-client-sdk/examples/client/.: 

None of these files exist:
  * http:/localhost:8081/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * ...
```

however `http://localhost:8081/index.js` does exist on my local developer machine. So this would indicate that the localhost in the above message is the Android device itself.

Workaround, add to sentry configuration:

```
integrations: function (integrations: any) { // see https://github.com/getsentry/sentry-react-native/issues/1346
    // filter default integrations
    return integrations.filter(function (integration:any) {
      return integration.name !== "DebugSymbolicator";
    });
  }
```

**Comment by krystofwoldrich** [comment] 2024-03-12 16:48
Hi @skjolber,
thank you for the message, the failing requests are caused by the `DebugSymbolicator` as mentioned above.
By fetching the source context

https://github.com/getsentry/sentry-react-native/blob/395a14b289fce9cdff1e67433fccd855fc6e5632/src/js/integrations/debugsymbolicator.ts#L182-L191

**Comment by krystofwoldrich** [comment] 2024-09-04 09:23
The extra requests also cause unnecessary builds of the Expo/React Native Web bundles if used in the application

- https://github.com/getsentry/sentry-react-native/issues/4054

**Comment by krystofwoldrich** [comment] 2024-10-02 10:04
The extra requests also trigger unintentional Web builds which can cause confusion (especially when the mobile build works, but web errors out)

- example https://github.com/getsentry/sentry-react-native/issues/4134

**Comment by krystofwoldrich** [comment] 2024-12-10 12:02
- Added/fixed in https://github.com/getsentry/sentry-react-native/pull/4287
- Released in https://github.com/getsentry/sentry-react-native/releases/tag/6.3.0

Sentry by default adds a middleware which is responsible for retrieving the source context, instead of  making multiple requests from the application. If source context is not needed the middleware can be disabled by the following code.

```js
// Expo
const { getSentryExpoConfig } = require('@sentry/react-native/metro');
const config = getSentryExpoConfig(__dirname, {
  enableSourceContextInDevelopment: false,
});

// React Native
const { withSentryConfig } = require('@sentry/react-native/metro');
module.exports = withSentryConfig(config, {
  enableSourceContextInDevelopment: false,
});
```

**Closed by krystofwoldrich** 2024-12-10 12:02 UTC
Labels: Type: :beetle: Bug, Platform: React-Native
