### ISSUE TITLE
Cannot read property 'setGlobalHandler' of undefined when adding metro serializer

### ISSUE THREAD

**Issue by thefranfran** [getsentry/sentry-react-native#3575] opened 2024-02-02 11:07 UTC
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.18.0

**`react-native` version:** 0.73.3

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: "...",
  attachScreenshot: true,
  tracesSampler: (samplingContext) => {
    const { parentSampled } = samplingContext;
    if (parentSampled === true) {
      return 1;
    }

    return 0;
  },
});
```
---
**I have the following issue:**

According to my last issue (https://github.com/getsentry/sentry-react-native/issues/3551) patch with (https://github.com/getsentry/sentry-react-native/pull/3573) 
Now when I run my project I have this error **Cannot read property 'setGlobalHandler' of undefined**
I have any error in the console so it should be a metro bug 
(Edit) Yes I can confirm when I remove the metro config my app running

This is my metro config 

```
const { getDefaultConfig } = require("@react-native/metro-config");
const {
  createSentryMetroSerializer,
} = require("@sentry/react-native/dist/js/tools/sentryMetroSerializer");

module.exports = (() => {
  const config = getDefaultConfig(__dirname);

  const { transformer, resolver } = config;

  config.transformer = {
    ...transformer,
    babelTransformerPath: require.resolve("react-native-svg-transformer"),
  };
  config.resolver = {
    ...resolver,
    assetExts: resolver.assetExts.filter((ext) => ext !== "svg"),
    sourceExts: [...resolver.sourceExts, "svg"],
  };
  config.serializer = {
    customSerializer: createSentryMetroSerializer(),
  };

  return config;
})();
```

**Steps to reproduce:**
- `npx @sentry/wizard@latest -s -i reactNative`
- Build project with Xcode

**Actual result:**

![Simulator Screenshot - iPhone 15 - 2024-02-02 at 12 02 08](https://github.com/getsentry/sentry-react-native/assets/11378561/b52f8f1b-46cf-4fc5-84f1-75154662d490)

**Comment by krystofwoldrich** [comment] 2024-02-05 14:58
@thefranfran Thank you for the message, would you be able to share a minimal reproducible example with us?

Sadly with the information we currently have we can't reproduce the issue.

**Comment by ad-aero** [comment] 2024-02-06 16:03
Hi @thefranfran, any solution?

**Comment by thefranfran** [comment] 2024-02-06 16:51
> fixed replacing `createSentryMetroSerializer` by `withSentryConfig`
> 
> `const {getDefaultConfig} = require('@react-native/metro-config'); const {withSentryConfig} = require('@sentry/react-native/metro');
> 
> const path = require('path'); const workspaceRoot = path.resolve(__dirname, '../..'); const projectRoot = __dirname;
> 
> const config = getDefaultConfig(projectRoot);
> 
> config.watchFolders = [workspaceRoot]; config.resolver.nodeModulesPaths = [ path.resolve(projectRoot, 'node_modules'), path.resolve(workspaceRoot, 'node_modules'), ]; config.resolver.disableHierarchicalLookup = true;
> 
> module.exports = withSentryConfig(config);`

Yes I approve this solution, it works fine now

**Comment by krystofwoldrich** [comment] 2024-02-08 12:46
@ad-aero and @thefranfran Thank you for the updates. Happy to hear that `withSentryConfig` solves the error. I will close the issue now.

**Closed by krystofwoldrich** 2024-02-08 12:46 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
