### ISSUE TITLE
On-Premise Sentry - Android - Envelope submission failed

### ISSUE THREAD

**Issue by omerkarakose** [getsentry/sentry-react-native#3148] opened 2023-06-26 16:18 UTC
**OS:**
- [x]  MacOS

**Platform:**
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 5.4.1

**`react-native` version:** 0.67.2

**Are you using Expo?**
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```typescript
const release = `${getVersion()}:${getBuildNumber()}`
const dist = getBuildNumber()

Sentry.init({
    dsn: Config.SENTRY_DSN,
    environment: Config.ENVIRONMENT,
    attachStacktrace: true,
    enableAutoSessionTracking: true,
    release,
    dist,
    debug: true,
})
```

---
**I have following issue:**

Android builds can upload SourceMaps successfully and I can see them on the SourceMap screen of the dashboard like below SS:

<img width="1201" alt="Screenshot 2023-06-26 at 19 14 32" src="https://github.com/getsentry/sentry-react-native/assets/110257867/0fc8844f-51ed-41a3-87fb-62629333fe74">

### **But the problem is, Android app can not upload any issue to the Sentry Dashboard.**

<img width="1784" alt="Screenshot 2023-06-26 at 19 15 38" src="https://github.com/getsentry/sentry-react-native/assets/110257867/565ad94c-d01b-40b9-bda9-d255ba767caa">

sentry.properties file has correct url, org, project and auth.token value. We created auth.token with all permissions but still does not work.

### NOTE: iOS app can send issues to the Sentry Dashboard successfully

**Comment by krystofwoldrich** [comment] 2023-06-27 08:45
Hi,
thank you for the message and the details,

do you use the same DSN for both iOS and Android? The sending of the envelopes doesn't depend on the `auth.token`, which is used only for the debug files upload.

**Comment by omerkarakose** [comment] 2023-06-27 08:57
> Hi, thank you for the message and the details,
> 
> do you use the same DSN for both iOS and Android? The sending of the envelopes doesn't depend on the `auth.token`, which is used only for the debug files upload.

Hi @krystofwoldrich, yes we are using the same DSN for both iOS and Android.

DSN value is below : ( I masked the domain name for the privacy purposes )

`https://b58ce4f0c74b4bcfa19393e15465e481@sentry-ui.euw2.devops-*****.com/7`

**Comment by krystofwoldrich** [comment] 2023-06-27 09:15
@omerkarakose Could you try to run the Android app with `fetchTransport`, to isolate the issue?

```js
import { makeFetchTransport } from '@sentry/browser';

Sentry.init({
  transport: makeFetchTransport,
  ...restOfTheOptions,
});

**Comment by omerkarakose** [comment] 2023-06-27 09:34
I've added sentry/browser package to the app and added transport flag to the Sentry.init.

```typescript
import { makeFetchTransport } from '@sentry/browser'
import * as Sentry from '@sentry/react-native'
import { getBuildNumber, getVersion } from 'react-native-device-info'

import Config from ':app/config'

export const initSentry = (): void => {
  const release = `${getVersion()}:${getBuildNumber()}`
  const dist = getBuildNumber()

  Sentry.init({
    transport: makeFetchTransport,
    dsn: Config.SENTRY_DSN,
    environment: Config.ENVIRONMENT,
    attachStacktrace: true,
    enableAutoSessionTracking: true,
    release,
    dist,
    debug: true,
  })
}
```

but I'm not sure there is any difference in the Android Studio logs.

I can only see the same envelope submission failed 403 error logs.

@krystofwoldrich do you have any idea to identify the issue with a different way ?

**Comment by krystofwoldrich** [comment] 2023-06-27 09:52
@omerkarakose Just to confirm, now the log should be from `ReactNativeJS` and not from the Java package `Sentry`. Is it?

**Comment by omerkarakose** [comment] 2023-06-27 09:57
I can see below logs on the logcat: ( I run the app on release mode, so RN bundle is integrated inside the apk. )

```log
2023-06-27 12:30:55.457 14882-14882 Sentry                  pid-14882                            D  io.sentry.auto-init read: false
2023-06-27 12:30:55.457 14882-14882 Sentry                  pid-14882                            I  Retrieving auto-init from AndroidManifest.xml
2023-06-27 12:30:56.122 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: ModulesLoader'
2023-06-27 12:30:56.122 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Unhandled promise rejections will be caught by Sentry.'
2023-06-27 12:30:56.122 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: ReactNativeErrorHandlers'
2023-06-27 12:30:56.122 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: Release'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: InboundFilters'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: FunctionToString'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: Breadcrumbs'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: LinkedErrors'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: Dedupe'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: HttpContext'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: EventOrigin'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: SdkInfo'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: ReactNativeInfo'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: RewriteFrames'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: DeviceContext'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[ReactNativeTracing] Native frames instrumentation initialized.'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[ReactNativeTracing] Not instrumenting route changes as routingInstrumentation has not been set.'
2023-06-27 12:30:56.123 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Integration installed: ReactNativeTracing'
2023-06-27 12:30:56.136 14882-14966 RNSentry                pid-14882                            I  Starting with DSN: 'https://********************************@sentry-ui.euw2.devops-*****.com/7'
2023-06-27 12:30:56.136 14882-14966 RNSentry                pid-14882                            I  Native Integrations '[io.sentry.UncaughtExceptionHandlerIntegration@769112c, io.sentry.ShutdownHookIntegration@effe7f5]'
2023-06-27 12:30:56.146 14882-14966 Sentry                  pid-14882                            W  ActivityLifecycle, FragmentLifecycle and UserInteraction Integrations need an Application class to be installed.
2023-06-27 12:30:56.150 14882-14966 Sentry                  pid-14882                            D  Class not available:androidx.compose.ui.node.Owner
                                                                                                    java.lang.ClassNotFoundException: androidx.compose.ui.node.Owner
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at java.lang.Class.forName(Class.java:379)
                                                                                                    	at io.sentry.android.core.LoadClass.loadClass(LoadClass.java:21)
                                                                                                    	at io.sentry.android.core.LoadClass.isClassAvailable(LoadClass.java:39)
                                                                                                    	at io.sentry.android.core.LoadClass.isClassAvailable(LoadClass.java:44)
                                                                                                    	at io.sentry.android.core.AndroidOptionsInitializer.initializeIntegrationsAndProcessors(AndroidOptionsInitializer.java:157)
                                                                                                    	at io.sentry.android.core.SentryAndroid.lambda$init$1(SentryAndroid.java:113)
                                                                                                    	at io.sentry.android.core.-$$Lambda$SentryAndroid$8U2bM905P-uVTL1lR52SjiYrYUE.configure(Unknown Source:8)
                                                                                                    	at io.sentry.Sentry.applyOptionsConfiguration(Sentry.java:172)
                                                                                                    	at io.sentry.Sentry.init(Sentry.java:142)
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89)
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70)
                                                                                                    	at io.sentry.react.RNSentryModuleImpl.initNativeSdk(RNSentryModuleImpl.java:106)
                                                                                                    	at io.sentry.react.RNSentryModule.initNativeSdk(RNSentryModule.java:27)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
                                                                                                    	at android.os.Looper.loop(Looper.java:223)
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
                                                                                                    Caused by: java.lang.ClassNotFoundException: androidx.compose.ui.node.Owner
                                                                                                    	at java.lang.Class.classForName(Native Method) 
                                                                                                    	at java.lang.Class.forName(Class.java:454) 
                                                                                                    	at java.lang.Class.forName(Class.java:379) 
                                                                                                    	at io.sentry.android.core.LoadClass.loadClass(LoadClass.java:21) 
                                                                                                    	at io.sentry.android.core.LoadClass.isClassAvailable(LoadClass.java:39) 
                                                                                                    	at io.sentry.android.core.LoadClass.isClassAvailable(LoadClass.java:44) 
                                                                                                    	at io.sentry.android.core.AndroidOptionsInitializer.initializeIntegrationsAndProcessors(AndroidOptionsInitializer.java:157) 
                                                                                                    	at io.sentry.android.core.SentryAndroid.lambda$init$1(SentryAndroid.java:113) 
                                                                                                    	at io.sentry.android.core.-$$Lambda$SentryAndroid$8U2bM905P-uVTL1lR52SjiYrYUE.configure(Unknown Source:8) 
                                                                                                    	at io.sentry.Sentry.applyOptionsConfiguration(Sentry.java:172) 
                                                                                                    	at io.sentry.Sentry.init(Sentry.java:142) 
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:89) 
                                                                                                    	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:70) 
                                                                                                    	at io.sentry.react.RNSentryModuleImpl.initNativeSdk(RNSentryModuleImpl.java:106) 
                                                                                                    	at io.sentry.react.RNSentryModule.initNativeSdk(RNSentryModule.java:27) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
                                                                                                    	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
                                                                                                    	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
                                                                                                    	at android.os.Looper.loop(Looper.java:223) 
                                                                                                    	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
                                                                                                    	at java.lang.Thread.run(Thread.java:923) 
2023-06-27 12:30:56.151 14882-14975 Sentry                  pid-14882                            D  SU isn't found on this Device.
2023-06-27 12:30:56.151 14882-14966 Sentry                  pid-14882                            I  Initializing SDK with DSN: 'https://********************************@sentry-ui.euw2.devops-*****.com/7'
2023-06-27 12:30:56.151 14882-14966 Sentry                  pid-14882                            I  GlobalHubMode: 'true'
2023-06-27 12:30:56.155 14882-14966 Sentry                  pid-14882                            D  UncaughtExceptionHandlerIntegration enabled: true
2023-06-27 12:30:56.155 14882-14966 Sentry                  pid-14882                            D  default UncaughtExceptionHandler class='io.intercom.android.sdk.errorreporting.IntercomExceptionHandler'
2023-06-27 12:30:56.155 14882-14966 Sentry                  pid-14882                            D  UncaughtExceptionHandlerIntegration installed.
2023-06-27 12:30:56.155 14882-14966 Sentry                  pid-14882                            D  ShutdownHookIntegration installed.
2023-06-27 12:30:56.157 14882-14966 Sentry                  pid-14882                            D  SendCachedEnvelopeIntegration installed.
2023-06-27 12:30:56.157 14882-14966 Sentry                  pid-14882                            D  NdkIntegration enabled: true
2023-06-27 12:30:56.158 14882-14977 Sentry                  pid-14882                            D  Started processing cached files from /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d
2023-06-27 12:30:56.158 14882-14977 Sentry                  pid-14882                            D  Processing dir. /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d
2023-06-27 12:30:56.158 14882-14977 Sentry                  pid-14882                            D  Processing 5 items from cache dir /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d
2023-06-27 12:30:56.158 14882-14977 Sentry                  pid-14882                            D  File /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/outbox is not a File.
2023-06-27 12:30:56.158 14882-14977 Sentry                  pid-14882                            D  File /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/.sentry-native is not a File.
2023-06-27 12:30:56.158 14882-14977 Sentry                  pid-14882                            D  Processing file: /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/28e66f49-7321-4181-b5a7-6d2104238a43.envelope
2023-06-27 12:30:56.159 14882-14966 sentry-native           pid-14882                            I  using database path "/data/data/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/.sentry-native"
2023-06-27 12:30:56.159 14882-14966 sentry-native           pid-14882                            D  starting backend
2023-06-27 12:30:56.159 14882-14966 sentry-native           pid-14882                            D  processing and pruning old runs
2023-06-27 12:30:56.160 14882-14966 Sentry                  pid-14882                            D  NdkIntegration installed.
2023-06-27 12:30:56.160 14882-14966 Sentry                  pid-14882                            D  Registering EnvelopeFileObserverIntegration for path: /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/outbox
2023-06-27 12:30:56.161 14882-14977 Sentry                  pid-14882                            D  Captured Envelope is already cached
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  EnvelopeFileObserverIntegration installed.
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  SendCachedEnvelopeIntegration installed.
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  enableSessionTracking enabled: true
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  enableAppLifecycleBreadcrumbs enabled: true
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  AnrIntegration enabled: true
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  ANR timeout in milliseconds: 5000
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  AnrIntegration installed.
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  AppComponentsBreadcrumbsIntegration enabled: true
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  AppComponentsBreadcrumbsIntegration installed.
2023-06-27 12:30:56.162 14882-14966 Sentry                  pid-14882                            D  SystemEventsBreadcrumbsIntegration enabled: true
2023-06-27 12:30:56.163 14882-14966 Sentry                  pid-14882                            D  SystemEventsBreadcrumbsIntegration installed.
2023-06-27 12:30:56.163 14882-14966 Sentry                  pid-14882                            D  NetworkBreadcrumbsIntegration enabled: true
2023-06-27 12:30:56.165 14882-14966 Sentry                  pid-14882                            D  NetworkBreadcrumbsIntegration installed.
2023-06-27 12:30:56.165 14882-14966 Sentry                  pid-14882                            D  enableSystemEventsBreadcrumbs enabled: true
2023-06-27 12:30:56.166 14882-14966 Sentry                  pid-14882                            D  TempSensorBreadcrumbsIntegration installed.
2023-06-27 12:30:56.166 14882-14966 Sentry                  pid-14882                            D  enableSystemEventBreadcrumbs enabled: true
2023-06-27 12:30:56.175 14882-14882 Sentry                  pid-14882                            D  AppLifecycleIntegration installed.
2023-06-27 12:30:56.177 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Setting idle transaction on scope. Span ID: b68ddfa96a363f4a'
2023-06-27 12:30:56.177 14882-14966 RNSentry                pid-14882                            I  FrameMetricsAggregator installed.
2023-06-27 12:30:56.177 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[Tracing] starting ui.load transaction - App Start'
2023-06-27 12:30:56.177 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'Starting heartbeat'
2023-06-27 12:30:56.177 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', 'pinging Heartbeat -> current counter: 0'
2023-06-27 12:30:56.177 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[ReactNativeTracing] Starting ui.load transaction "App Start" on scope'
2023-06-27 12:30:56.178 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[Tracing] Starting \'app.start.cold\' span on transaction \'App Start\' (b68ddfa96a363f4a).'
2023-06-27 12:30:56.512 14882-14978 Sentry                  pid-14882                            D  Request failed, API returned 403
2023-06-27 12:30:56.512 14882-14978 Sentry                  pid-14882                            D  <html>
                                                                                                    <head><title>403 Forbidden</title></head>
                                                                                                    <body>
                                                                                                    <center><h1>403 Forbidden</h1></center>
                                                                                                    </body>
                                                                                                    </html>
2023-06-27 12:30:56.513 14882-14978 Sentry                  pid-14882                            D  The transport failed to send the envelope with response code 403
2023-06-27 12:30:56.513 14882-14978 Sentry                  pid-14882                            E  Envelope submission failed
                                                                                                    java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:267)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:199)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-06-27 12:30:56.513 14882-14978 Sentry                  pid-14882                            D  Marking envelope submission result: false
2023-06-27 12:30:56.513 14882-14977 Sentry                  pid-14882                            D  Deleted file /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/28e66f49-7321-4181-b5a7-6d2104238a43.envelope.
2023-06-27 12:30:56.513 14882-14977 Sentry                  pid-14882                            D  Processing file: /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/last_crash
2023-06-27 12:30:56.513 14882-14977 Sentry                  pid-14882                            D  File '/data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/last_crash' doesn't match extension expected.
2023-06-27 12:30:56.513 14882-14977 Sentry                  pid-14882                            D  Processing file: /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/2f3115d8-2286-4aa8-88e2-724794dbeb44.envelope
2023-06-27 12:30:56.514 14882-14978 Sentry                  pid-14882                            D  Serializing object: {
                                                                                                    	"sid": "936d77f8-a658-4f6f-a705-e02f20bc97be",
                                                                                                    	"did": "e0d65650-daeb-456e-82b2-ed3eeb8c82a3",
                                                                                                    	"init": true,
                                                                                                    	"started": "2023-06-27T09:30:56.175Z",
                                                                                                    	"status": "ok",
                                                                                                    	"errors": 0,
                                                                                                    	"timestamp": "2023-06-27T09:30:56.175Z",
                                                                                                    	"attrs": {
                                                                                                    		"release": "0.0.5:11",
                                                                                                    		"environment": "dev"
                                                                                                    	}
                                                                                                    }
2023-06-27 12:30:56.514 14882-14977 Sentry                  pid-14882                            D  Captured Envelope is already cached
2023-06-27 12:30:56.514 14882-14978 Sentry                  pid-14882                            D  Serializing object: {
                                                                                                    	"sid": "936d77f8-a658-4f6f-a705-e02f20bc97be",
                                                                                                    	"did": "e0d65650-daeb-456e-82b2-ed3eeb8c82a3",
                                                                                                    	"init": true,
                                                                                                    	"started": "2023-06-27T09:30:56.175Z",
                                                                                                    	"status": "ok",
                                                                                                    	"errors": 0,
                                                                                                    	"timestamp": "2023-06-27T09:30:56.175Z",
                                                                                                    	"attrs": {
                                                                                                    		"release": "0.0.5:11",
                                                                                                    		"environment": "dev"
                                                                                                    	}
                                                                                                    }
2023-06-27 12:30:56.514 14882-14978 Sentry                  pid-14882                            I  Crash marker file exists, crashedLastRun will return true.
2023-06-27 12:30:56.514 14882-14978 Sentry                  pid-14882                            D  Adding Envelope to offline storage: /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/f80cc9f1-5d08-435b-a367-185a387feef2.envelope
2023-06-27 12:30:56.694 14882-14978 Sentry                  pid-14882                            D  Request failed, API returned 403
2023-06-27 12:30:56.694 14882-14978 Sentry                  pid-14882                            D  <html>
                                                                                                    <head><title>403 Forbidden</title></head>
                                                                                                    <body>
                                                                                                    <center><h1>403 Forbidden</h1></center>
                                                                                                    </body>
                                                                                                    </html>
2023-06-27 12:30:56.694 14882-14978 Sentry                  pid-14882                            D  The transport failed to send the envelope with response code 403
2023-06-27 12:30:56.694 14882-14978 Sentry                  pid-14882                            E  Envelope submission failed
                                                                                                    java.lang.IllegalStateException: The transport failed to send the envelope with response code 403
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.flush(AsyncHttpTransport.java:267)
                                                                                                    	at io.sentry.transport.AsyncHttpTransport$EnvelopeSender.run(AsyncHttpTransport.java:199)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)
2023-06-27 12:30:56.694 14882-14978 Sentry                  pid-14882                            D  Adding Envelope to offline storage: /data/user/0/com.*****.*******.***/cache/sentry/3274ef5ce2790a6c4c675f69b232a0e6cee08e8d/f46c141a-142a-41f7-9587-9b4122f1cb74.envelope


2023-06-27 12:30:57.425 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[Tracing] finishing IdleTransaction', '2023-06-27T09:30:57.424Z', 'ui.load'
2023-06-27 12:30:57.426 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[StallTracking] Stall measurements were not added to transaction due to exceeding the max count.'
2023-06-27 12:30:57.426 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[Tracing] flushing IdleTransaction'
2023-06-27 12:30:57.426 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[Measurements] Adding measurements to transaction', '{\n  "app_start_cold": {\n    "value": 750,\n    "unit": "millisecond"\n  }\n}'
2023-06-27 12:30:57.426 14882-14965 ReactNativeJS           pid-14882                            I  'Sentry Logger [log]:', '[Tracing] Finishing ui.load transaction: App Start.'
```

**Comment by krystofwoldrich** [comment] 2023-06-27 11:03
@omerkarakose This log is with the `makeFetchTransport `?

**Comment by omerkarakose** [comment] 2023-06-27 11:10
@krystofwoldrich Yes, the code is exactly like in this comment: https://github.com/getsentry/sentry-react-native/issues/3148#issuecomment-1609138993

**Comment by krystofwoldrich** [comment] 2023-06-27 11:53
Could you try to delete and install the app again?

Are you using Sentry Android Gradle Plugin?

**Comment by omerkarakose** [comment] 2023-06-27 12:18
@krystofwoldrich I made a clean install on the emulator right now. Logcat looks like same to me:

https://gist.github.com/omerkarakose/0085a5f310eccb82cd69489506224ccc

Yes, I'm using the gradle plugin.

```gradle
apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/@sentry/react-native/sentry.gradle"
```

Using `sentry/react-native 5.4.1` version. Gradle script is coming from node_modules

**Comment by krystofwoldrich** [comment] 2023-06-27 13:33
@omerkarakose I know you are using On-Premise backend, but have you tried this with Sentry.io, just to check if the issue is related to the On-Premise setup or the RN SDK?

**Comment by omerkarakose** [comment] 2023-06-27 19:53
@krystofwoldrich @marandaneto Thanks for the responses, I'll reach out our dev-ops team so we can check the server configuration.

I'll send a comment when we find the cause

**Comment by krystofwoldrich** [comment] 2023-06-28 13:09
@omerkarakose We will close this for now, feel free to comment here when you find out more.

**Closed by krystofwoldrich** 2023-06-28 13:09 UTC
Labels: Status: Awaiting Response, Platform: React-Native, Waiting for: Product Owner
