### ISSUE TITLE
Task :@sentry_react-native:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by naheedsa** [getsentry/sentry-react-native#3193] opened 2023-07-16 13:42 UTC
Anyone familiar with the issue?  
React native version: 0.72.3
Sentry version: 5.7.1
> Task :@sentry_react-native:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/8.0.1/userguide/command_line_interface.html#sec:command_line_warnings
20 actionable tasks: 15 executed, 5 up-to-date

info 💡 Tip: Make sure that you have set up your development environment correctly, by running react-native doctor. To read more about doctor command visit: https://github.com/react-native-community/cli/blob/main/packages/cli-doctor/README.md#doctor 

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':@sentry_react-native:compileDebugJavaWithJavac' (type 'JavaCompile').
  - Gradle detected a problem with the following location: '/home/stellarmate/Projects/stellarmateapp2/node_modules/@sentry/react-native/android/build/generated/aidl_source_output_dir/debug/out'.
    
    Reason: Task ':@sentry_react-native:compileDebugJavaWithJavac' uses this output of task ':sentry_react-native:compileDebugAidl' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':sentry_react-native:compileDebugAidl' as an input of ':@sentry_react-native:compileDebugJavaWithJavac'.
      2. Declare an explicit dependency on ':sentry_react-native:compileDebugAidl' from ':@sentry_react-native:compileDebugJavaWithJavac' using Task#dependsOn.
      3. Declare an explicit dependency on ':sentry_react-native:compileDebugAidl' from ':@sentry_react-native:compileDebugJavaWithJavac' using Task#mustRunAfter

**Comment by krystofwoldrich** [comment] 2023-07-17 11:58
Hi, 
thank you for the message,
your error looks like a duplicate of https://github.com/getsentry/sentry-react-native/issues/3144?

Are you also manually adding the `sentry_react-native` project to the builds? Maybe the same solution will help. The library is auto-linked so no the project doesn't have to be added manually.
https://github.com/devDanielCespedes/sentry-minimal-reproducible-example-error/compare/main...krystofwoldrich:sentry-minimal-reproducible-example-error:main

**Comment by krystofwoldrich** [comment] 2023-07-28 11:50
Closing this due to inactivity. If this is still an issue feel free to comment here or open a new issue if the context changed.

**Closed by krystofwoldrich** 2023-07-28 11:50 UTC
Labels: Platform: React-Native
