### ISSUE TITLE
not working on Android 9 (real device or simulator)

### ISSUE THREAD

**Issue by webforuse** [getsentry/sentry-react-native#650] opened 2019-09-03 09:31 UTC
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
├── @babel/runtime@7.5.5
├── @react-native-community/async-storage@1.6.1
├── @react-native-community/geolocation@2.0.2
├── @react-native-community/netinfo@4.2.0
├── @react-native-community/push-notification-ios@1.0.2
├── @sentry/react-native@1.0.1
├── awesome-debounce-promise@2.1.0
├── axios@0.18.1
├── babel-plugin-transform-remove-console@6.9.4
├── base-64@0.1.0
├── hex-to-rgba@2.0.1
├── javascript-natural-sort@0.7.1
├── js-sha256@0.9.0
├── lodash@4.17.15
├── lodash.isequal@4.5.0
├── lodash.isnil@4.0.0
├── mobx@5.13.0
├── mobx-react@5.4.4
├── moment@2.24.0
├── moment-timezone@0.5.26
├── plural-ru@2.0.1
├── prop-types@15.7.2
├── query-string@6.8.2
├── react@16.8.6
├── UNMET PEER DEPENDENCY react-native@0.60.4
├── react-native-animatable@1.3.2
├── react-native-autocomplete-input@3.6.0
├── react-native-autocomplete-search@1.0.8
├── react-native-camera@3.2.0
├── react-native-communications@2.2.1
├── react-native-cookies@3.3.0
├── react-native-device-info@0.15.3
├── react-native-elements@1.1.0
├── react-native-fs@2.14.1
├── react-native-gesture-handler@1.4.0
├── react-native-i18n@2.0.15
├── react-native-image-picker@0.28.1
├── react-native-indicators@0.12.0
├── react-native-keyboard-aware-scroll-view@0.8.0
├── react-native-linear-gradient@2.5.6
├── react-native-message-bar@2.0.10
├── react-native-modal@11.3.1
├── react-native-modalbox@1.7.1
├── react-native-offline@3.15.2
├── react-native-onesignal@3.3.1
├── react-native-picker-select@6.3.0
├── react-native-public-ip@1.0.1
├── react-native-queue@1.2.1
├── react-native-reanimated@1.2.0
├── react-native-render-html@4.1.2
├── react-native-responsive@1.0.2
├── react-native-simple-radio-button@2.7.3
├── react-native-svg@9.6.2
├── react-native-vector-icons@6.6.0
├── react-native-webview@6.9.0
├── react-navigation@3.11.1
├── react-redux@5.1.1
├── recompose@0.26.0
├── redux@3.7.2
├── redux-form@7.4.2
├── redux-saga@1.0.5
├── redux-thunk@2.3.0
├── rn-fetch-blob@0.10.16
├── sha256@0.2.0
├── socket.io@2.2.0
├── socket.io-client@2.2.0
├── styled-components@3.4.10
├── styled-tools@0.4.0
└── utf-8@2.0.0
```

Config:

```
Sentry.config('https://...@sentry.io/...', {
....
}).install()
```

---
I have following issue:

not working on Android 9

Description goes here ...
not working on Android 9 (real device or simulator)

**Steps to reproduce:**
- Step
run app and call Sentry.captureEvent({
  message: 'test-init-sentry',
  level: 'info',
});

**Actual result:**
not working on Android 9 (simulator or device)
working is fine on (iOS or Android 8)

**Expected result:**
working on Android 9 (simulator or device)

**Comment by HazAT** [comment] 2019-09-04 09:46
Can you please upgrade to `1.0.2` and see if the problem is still there?

**Comment by webforuse** [comment] 2019-09-04 17:47
i install Sentry 1.0.4 
not working on Android 9 (simulator or real device)

**Comment by HazAT** [comment] 2019-09-05 12:18
Hey, I just tried it with an Android 9 device and in debug and release build, works without an issue.
Please provide a repro case, I will close this for now.

**Closed by HazAT** 2019-09-05 12:18 UTC

**Comment by webforuse** [comment] 2019-09-05 18:57
no not working.
Working if run console (react-native run-android)
is working.
If in Android Studio build release.apk (nothing works) simulator or real device.

What proof do you need to believe ?

We have a project because of this in a very bad condition, we can not normally catch bugs
