### ISSUE TITLE
No JS-level errors sent in Release mode

### ISSUE THREAD

**Issue by matt-dalton** [getsentry/sentry-react-native#700] opened 2019-10-17 12:40 UTC
OS:
- [ ]  Windows
- [ x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.60.6

Init Code:

```
Sentry.init({
    dsn: 'https://blah@sentry.io/blah',
    ignoreErrors: [NetworkError.name],
    debug: true // just while I test
})
```

---
I have following issue:

Our React Native sentry installation no longer reports JS-level bugs. I'm now on react-native 0.60.6 & @sentry/react-native 1.0.9. I'm currrently testing on iOS but it hasn't been working on Android either. It hasn't been working for us for a while so don't think it's a new version issue.

I've tried removing and reinstalling the library.

When I run in dev mode, any error I throw appears in Sentry. But if I take the same code and run in release mode nothing gets sent. I can see the following in the logs in Xcode:
```
2019-10-17 13:25:14.309488+0100 [63272:2506227] Sentry Started -- Version: 4.4.0
2019-10-17 13:25:22.524 [error][tid:com.facebook.react.JavaScript] Sentry Logger [Error]: An event processor returned null, will not send event.
```

**Steps to reproduce:**
- Install RN 0.60.6 & @sentry/react-native 1.0.9
- Init the lib, then add `throw new Error('test')` on root `App.js`
- Run the app in dev mode
- It works! Bug appears in Sentry
- Build the app in release mode (i.e. BuildConfiguration: Release)
- Run the app. 

**Actual result:**
- No bug received in Sentry

**Expected result:**
- Should be a bug report

**Comment by filipef101** [comment] 2019-10-22 16:28
Does using a older version fix this?

**Comment by matt-dalton** [comment] 2019-10-23 08:17
Is there any particular version I should try going back to? As I say, this hasn't worked for a while so not sure how far to go back

**Comment by AChevallier** [comment] 2019-10-30 10:31
I have the same problem ! :(
I cannot say since when.

**Comment by jpolo** [comment] 2019-12-06 17:42
Still reproducible on RN 0.61.5 + Sentry 1.1.0

**Comment by shridharbavannawar** [comment] 2019-12-09 10:04
Any update on this? Facing same issue on  `"react-native": "0.61.4"` `"@sentry/react-native": "1.2.0"`

**Comment by shridharbavannawar** [comment] 2019-12-09 11:21
> Any update on this? Facing same issue on `"react-native": "0.61.4"` `"@sentry/react-native": "1.2.0"`

Doesn't work for android release build. Works fine for iOS though.

**Comment by shridharbavannawar** [comment] 2019-12-11 05:55
> Any update on this? Facing same issue on `"react-native": "0.61.4"` `"@sentry/react-native": "1.2.0"`
> Doesn't work for android release build. Works fine for iOS though.

It worked for me. Created a new project, configured sentry. Crash logs appear for both android and ios release build. Using the same version `react-native` and `@sentry/react-native` mentioned above

**Comment by filipef101** [comment] 2019-12-18 21:03
It's dumb this is open for so long when there are paying customers affected by this

**Comment by matt-dalton** [comment] 2019-12-19 09:29
I managed to fix this after speaking to tech support. Achieved this by switching from `ignoreErrors: [NetworkError.name]` to a beforeSend function. I wrote something super simple like this:
```
const ignoredEventTypes: Array<string> = [NetworkError.name]

export default (event: Event) => {
    const eventType = get(event, 'exception.values[0].type')

    if (ignoredEventTypes.includes(eventType)) {
        // Not returning the event ignores it
        return
    }

    return event
}
```

For some reason, ignoreErrors was blocking anything

**Comment by HazAT** [comment] 2020-01-09 08:40
I am closing this since it seems to be solved.
The log `Sentry Logger [Error]: An event processor returned null, will not send event.` says that we discarded it because `ignoreError` matched it.
I am not sure if all ppl in this thread have exactly this problem?!

**Closed by HazAT** 2020-01-09 08:40 UTC

**Comment by Aryk** [comment] 2020-08-11 18:19
> I managed to fix this after speaking to tech support. Achieved this by switching from `ignoreErrors: [NetworkError.name]` to a beforeSend function. I wrote something super simple like this:
> 
> ```
> const ignoredEventTypes: Array<string> = [NetworkError.name]
> 
> export default (event: Event) => {
>     const eventType = get(event, 'exception.values[0].type')
> 
>     if (ignoredEventTypes.includes(eventType)) {
>         // Not returning the event ignores it
>         return
>     }
> 
>     return event
> }
> ```
> 
> For some reason, ignoreErrors was blocking anything

1) What is "get" in your function? Can't seem to find it in sentry lib....
2) Im getting the same error:

<img width="468" alt="Screen Shot 2020-08-11 at 9 14 27 PM" src="https://user-images.githubusercontent.com/525212/89933768-3bdebb80-dc18-11ea-981c-65d016ca0d48.png">

Are you suggesting essentially not to use "ignoreErrors" and do basically do the ignoring in beforeSend, seems kind of hacky...but is what it is I guess...

**Comment by jennmueng** [comment] 2020-08-12 14:27
@Aryk Can I see what you have set for `ignoreErrors`?

**Comment by Aryk** [comment] 2020-08-12 14:29
Sure ...here's the entire code:

```ts
Sentry.init({
  dsn: <hidden>,
  enableInExpoDevelopment: true,
  debug: true,
  environment: Constants.manifest.releaseChannel || "development",
  attachStacktrace: true,
  ignoreErrors: [
  "GraphQL Error (Code: 502)", // On development, get this weird intermittent message.
  "Background Location has not been configured. To enable it",
  "Network request failed",
  "Rendered fewer hooks than expected. This may be caused by",
  ],
});
// Keys are snake_case because this was the convention in the documentation.
Sentry.setTags({
  device_name: Constants.deviceName,
  ios_model: Constants.platform.ios?.model,
  ios_build_number: Constants.manifest.ios?.buildNumber,
  android_version_code: Constants.manifest.android?.versionCode,
  revision_id: Constants.manifest.revisionId,
  release_id: Constants.manifest.releaseId,
  version: Constants.manifest.version,
  // system_version: Constants.systemVersion.toString(),
});
```

**Comment by jennmueng** [comment] 2020-08-12 14:35
@Aryk So is the event being dropped an event that shouldn't be dropped I assume right? And can I see you have already set `debug: true`, can I have the logs?

**Comment by Aryk** [comment] 2020-08-12 14:51
Sure...how do I get you the logs? I don't see it write to any log files in my directory. I can give you the console output, does that work?

**Comment by Aryk** [comment] 2020-08-12 15:02
This is all I'm getting in my console:

<img width="468" alt="Screen Shot 2020-08-11 at 9 14 27 PM" src="https://user-images.githubusercontent.com/525212/90031531-0395b680-dcc6-11ea-99ee-fd71de1c6fc4.png">

**Comment by jennmueng** [comment] 2020-08-12 15:11
@Aryk Hmm that looks correct, I see you have `"Network request failed"` in your `ignoreErrors`, it's being ignored thus the message. Also, the message is showing because you have `debug: true` set. If you disable debug the error won't be shown.

**Comment by Aryk** [comment] 2020-08-12 16:06
Wow ok...I will turn debug off then. lol 

Thanks for pointing that out...this error was driving me crazy
