### ISSUE TITLE
Sentry trace header not propagated to requests made from the native layer.

### ISSUE THREAD

**Issue by valeriashpiner** [getsentry/sentry-react-native#1456] opened 2021-04-19 20:12 UTC
### Environment

How do you use Sentry?
**Sentry SaaS (sentry.io)**

Which SDK and version?
**"@sentry/react-native": "^2.4.0",**

### Steps to Reproduce
0. I tried to set up `Performance monitoring` through `Included Instrumentation`.

1. I set up Sentry.
<img width="250" alt="Screen Shot 2021-04-19 at 4 03 28 PM" src="https://user-images.githubusercontent.com/18754922/115296360-dd63c880-a128-11eb-9ffa-28997c682c3e.png">

2. I connected Sentry to Navigatior.
<img width="250" alt="Screen Shot 2021-04-19 at 4 05 53 PM" src="https://user-images.githubusercontent.com/18754922/115296573-1f8d0a00-a129-11eb-92b7-bfa8025818be.png">

3. That's all what I did.

### Expected Result
I would like to see `sentry-trace` in my request headers. None of my request has it right now.
Can you, please, explain what step did I miss.

### Actual Result
In `Transactions` tab in Performance Dashboard I see only screen names which I visit, but I don't see any other transactions (network calls, for example). I don't have `sentry-trace` headers in any of my network calls.

**Comment by fdalmard** [comment] 2021-05-04 09:26
Same issue here 😐

**Comment by jrunkel** [comment] 2021-05-04 10:46
Here too.

**Comment by osamaarefm** [comment] 2021-05-16 11:59
Same here.

**Comment by yahuio** [comment] 2021-06-11 08:26
Same here

**Comment by yahuio** [comment] 2021-07-02 02:08
Any update?

**Comment by oktorakevinarigi** [comment] 2021-07-26 07:38
Same her.

Any update?

**Comment by jennmueng** [comment] 2021-07-26 08:08
I just got back from a vacation, I will look into this ASAP

**Comment by Imperyall** [comment] 2021-08-03 10:57
same here

**Comment by 0b3r** [comment] 2021-09-09 03:44
same here

**Comment by jennmueng** [comment] 2021-10-19 03:47
How is everyone making the requests that are missing the `sentry-trace` header? Can I get some examples? 

FYI Given the current hybrid SDK limitations the trace header **will only be attached to outgoing http requests sent by the javascript layer**, and none from the native layer.

**Comment by laygir** [comment] 2021-10-19 06:24
@jennmueng I am on Vue2 but for what its worth, here's my issue:

I make a request using Axios on the beforeEach hook of my router. When `VueRouterInstrumentation` is enabled, my request starts before the pageload or navigation transaction kicks in, this causes the request to NOT have the trace header.

It took me some time to figure out automatic instrumentation does not pick up individual XHR requests (bummer) unless there is an active transaction. And automatic instrumentation only creates transactions for pageload and navigation as far as I could see so far.

Perhaps documentation could be improved to state these hard facts, because as a dev who started using Sentry tracing just 2 weeks ago, I was under the assumption that every XHR request should have been pick up by the automatic instrumentation.

Also this following Sentry support reply has mislead me on that expectation:

> "For the front-end side, the automatic instrumentation should create transaction to every XHR request (as long as the sampling is 100%). If it doesn't, we will need to check the logs after adding the debug option, in order to understand why."

**Comment by marandaneto** [comment] 2021-11-08 11:07
@jennmueng did you manage to reproduce this?

**Comment by kaokei** [comment] 2021-11-11 03:20
I just met the same problem in a vue3 app. And I think the key problem is that sentry start pageload transaction too late. Now sentry start pageload transaction inside `router.beforeEach`. The sentry-trace header will miss if I send request before that time.

The picture below shows the timeline.

![image](https://user-images.githubusercontent.com/82272759/141231276-8b4b6735-1d16-4f02-81b6-c74f815d540b.png)

**Comment by laygir** [comment] 2021-11-11 08:29
Hey @kaokei 👋 

I have been in touch with Sentry support and recently concluded a month long e-mail thread precisely about this behaviour.
Also have created the issue below and it's been acknowledged by the Sentry and support told me it is in the backlog and will be fixed soon. I hope they fulfill this promise.

https://github.com/getsentry/sentry-javascript/issues/4072

Feel free to add your additional findings on the above issue.

**Comment by marandaneto** [comment] 2021-11-11 10:05
@valeriashpiner can you confirm that you're also using the vue router? thanks

**Comment by jennmueng** [comment] 2021-11-30 20:57
@laygir @kaokei As you guys are using Vue and not React Native, I guess it's not exactly related to this issue with the React Native SDK and rather the discussion should be on the Sentry Javascript repo: https://github.com/getsentry/sentry-javascript/issues/4072. Noting that I have not been able to reproduce this issue along with no one providing reproductions I will assume it is due to creating the request on the native layer side rather on the Javascript side like I earlier hypothesized.

I will thus rename this issue and move it to our Backlog.

**Comment by marandaneto** [comment] 2021-12-06 13:35
@jennmueng I'm a bit lost here, help me out understanding what should be done.

if people are using the `vue` integration, they might hit https://github.com/getsentry/sentry-javascript/issues/4072, ok, that's a reported bug already.

what do you mean by `requests made from the native layer`? Native layer = Native SDKs Android and iOS? how did you come to this conclusion? the issue description had no clue about making a request on the Java/ObjC side.

**Comment by marandaneto** [comment] 2022-01-12 10:56
@jennmueng mind clarifying? thanks

**Comment by marandaneto** [comment] 2022-01-12 16:07
After discussing on a call, the `vue` issue isn't related to this at all.
The original issue is about syncing down the sentry trace header to the Native layer (Android/iOS).

**Comment by marandaneto** [comment] 2022-01-12 16:45
Closed in favor of https://github.com/getsentry/sentry-react-native/issues/2003 and https://github.com/getsentry/sentry-javascript/issues/4072

**Closed by marandaneto** 2022-01-12 16:45 UTC
Labels: Type: :beetle: Bug, Status: Awaiting Response, Platform: React-Native
