### ISSUE TITLE
No native crashes caught before RCTRootView initialization

### ISSUE THREAD

**Issue by chrs1885** [getsentry/sentry-react-native#603] opened 2019-06-13 13:35 UTC
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

Output of `node -v && npm -v && npm ls --prod --depth=0`

```
v8.15.0
6.4.1
```

Config:

```
Sentry.config('https://foo@sentry.io/bar', {
  deactivateStacktraceMerging: false, // default: true | Deactivates the stack trace merging feature
  handlePromiseRejection: true // default: true | Handle unhandled promise rejections
}).install();
```

---
I have following issue:

Our app is using a native bottom navigation. Each tab is representing a RCTRootView or a native view. Depending on which tab is active when launching the app, the SDK may or may not be initialized. In case of a native view, native crashes will not be reported. I understand that the SDK was not built for app setups like this, but for single RCTRootView apps instead. However, would it be possible to use the native AND the react native SDK at the same time by disabling native crash handling when configuring the react native SDK?

Furthermore, due to privacy concerns we need to stop/start crash reporting based on a toggle state inside our settings screen. Is there a way to do so by using the rn sdk?

**Steps to reproduce:**
-

**Actual result:**
No crashes are reported. You need to display a RN screen before native client gets initialized.

**Expected result:**
Crashes are reported even before a RCTRootView was presented to the user.

**Comment by chrs1885** [comment] 2019-07-08 10:02
Any updates on this one? We are currently evaluating several crash service, therefore I need to verify that Sentry meets this requirement.

**Comment by HazAT** [comment] 2019-07-08 12:45
So with `@sentry/react-native` `1.0.0-beta.1` see here: https://github.com/getsentry/sentry-react-native/issues/612

It's possible to use both the native and react-native SDK together.
There is a new option called: 
``
/**
   * Enables native crashHandling. This only works if `enableNative` is `true`.
   * Defaults to `true`.
   */
  enableNativeCrashHandling: boolean;
```

if this is set to `false` the crash handler will not be started.
With that, you will still have the native transport.

**Comment by chrs1885** [comment] 2019-07-08 14:22
@HazAT Thanks for your reply. Speaking of iOS I can still see some issues here: In our app setup crashes can occur even before the `RCTRootView` has been initialized, since we are using a native navigation. That being said, we need to initialize the SDK within the AppDelegate's `didFinishLaunchingWithOptions`. Otherwise, a crash that happens right before the presentation of the first RN screen will never get reported to the Sentry backend and we will never figure out whether our app is healthy or not. Any thoughts on that?

**Comment by chrs1885** [comment] 2019-07-08 14:27
Furthermore, I'm not quite sure how the SDK will work if the app is managing multiple `RCTRootView`s. The native ta bar might manage multiple `RCTRootView's (1 per tab). The initializitation code on the react native side of things will internally call a bridge function called `startWithDsnString`that will always create a new client instance and set it as the shared instance rather than checking the existence of a shared client first.

**Comment by chrs1885** [comment] 2019-07-09 08:33
@HazAT I was trying to use the beta SDK but came across some issues. The integration (linking) of the new SDK worked great. I added the Sentry `init` to the javascript code and the following block to my app's `applicationDidFinishLaunchingWithOptions`:

```
do {
      Client.shared = try Client(dsn: "https://******@sentry.io/*****")
      try Client.shared?.startCrashHandler()
    } catch let error {
      print("\(error)")
    }
```

the native crash is caught and sent to Sentry even before the javascript code was loaded. However, once the RN screen is displayed (which internally initializes the SDK) the app crashes. I thought this could be useful feedback for the beta.

**Comment by chrs1885** [comment] 2019-07-09 09:05
BTW: The integration of the beta SDK with RN 0.59.0 was pretty straightforward. Also, we are now getting native crashes, even before the js code was loaded. 👍

**Comment by chrs1885** [comment] 2019-07-15 09:43
@HazAT one more question regarding the beta. Is there a way to temporarily disable recording and sending of reports? Unfortunately, I couldn't find a way to do both.

**Comment by HazAT** [comment] 2019-09-04 14:03
Duplicate of https://github.com/getsentry/sentry-react-native/issues/542
Please track and reply there.

**Closed by HazAT** 2019-09-04 14:03 UTC
Labels: 🦔react-native-sentry
