### ISSUE TITLE
Crashes before React-Native initialized are not captured

### ISSUE THREAD

**Issue by cpirich** [getsentry/sentry-react-native#497] opened 2018-11-02 21:07 UTC
OS:
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

_Platform:_
- [x]  iOS
- [ ]  Android

---
@jastanton and I have following issue:

Per https://github.com/getsentry/react-native-sentry/issues/200, our app has no code related to Sentry in `didFinishLaunchingWithOption`. However, we are also not catching any native crashes that occur before React Native is initialized and we start calling `react-native-sentry`. We'd like all crashes to be captured.

By adding this code (per the Sentry Cocoa instructions), we seem to be getting them all now:
```
  NSError *error = nil;
  SentryClient *client = [[SentryClient alloc] initWithDsn:CONFIG_SENTRY_DSN didFailWithError:&error];
  SentryClient.sharedClient = client;
  [SentryClient.sharedClient startCrashHandlerWithError:&error];
  if (nil != error) {
    RCTLog(@"SentryClient error: %@", error);
  }
```

Do you agree that this is needed to catch all crashes? Is there any harm in having the `SentryClient` initialized again by `react-native-sentry` (replacing the existing `SentryClient.sharedClient`?)

Is a similar change required on Android to capture these early crashes in a React Native app?

Thanks

**Comment by manjuy124** [comment] 2018-12-06 14:57
@cpirich Did you find any way to catch the exceptions from Native code?

**Comment by HazAT** [comment] 2019-09-04 14:02
Duplicate of https://github.com/getsentry/sentry-react-native/issues/542
Please track and reply there.

**Closed by HazAT** 2019-09-04 14:02 UTC
Labels: 🦔react-native-sentry
