### ISSUE TITLE
Sentry requires `'APPLICATION_EXTENSION_API_ONLY=YES`

### ISSUE THREAD

**Issue by Mitch528** [getsentry/sentry-react-native#3908] opened 2024-06-20 16:22 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.24.1

**`react-native` version:** 0.74.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

Build fails with:

SentryProfilerState.mm
```
Property 'date' cannot be found in forward class object 'SentryCurrentDateProvider'
```

This is also on Xcode 16.0 Beta, so I'm not sure if it's related or not to #3883

**Actual result:**

Build fails

**Expected result:**

Build does not fail.

**Comment by krystofwoldrich** [comment] 2024-06-21 07:31
Hi @Mitch528,
thank you for the report, we'll check it.

Are your pods up to date, are you using the `'Sentry/HybridSDK', '8.29.1'`? Just want to confirm this since workaround for https://github.com/getsentry/sentry-react-native/issues/3883 was changing manually the Sentry pod version.

**Comment by Mitch528** [comment] 2024-06-21 15:04
Hi @krystofwoldrich yeah, pods are up-to-date. I've tried regenerating my Podfile.lock without luck as well.

I didn't explicitly include the pod in my Podfile but it does seem like it's included in the lockfile:

```
  - RNSentry (5.24.1):
    - hermes-engine
    - React-Core
    - React-hermes
    - Sentry/HybridSDK (= 8.29.1)
...
  - Sentry/HybridSDK (8.29.1)
```

**Comment by krystofwoldrich** [comment] 2024-06-25 07:22
@Mitch528 Thanks for the details.

**Comment by zdtclement** [comment] 2024-07-18 17:18
I'm seeing this same issue issue Xcode 16 beta 3

**Comment by krystofwoldrich** [comment] 2024-08-01 12:25
Hi @zdtclement,
thank you for the message, what version of the SDK are you using?

Are you running Xcode 16 on Sonoma or beta of Sequoia?

**Comment by krystofwoldrich** [comment] 2024-08-02 14:51
Hello everyone we have [tested](https://github.com/getsentry/sentry-react-native/pull/3986) the Xcode 16 Beta 4 and RN 73 and could not reproduce the issue.

If the build is failing for you, could you share a minimal reproducible sample which we can debug?

**Comment by Mitch528** [comment] 2024-08-02 15:59
> Hello everyone we have [tested](https://github.com/getsentry/sentry-react-native/pull/3986) the Xcode 16 Beta 4 and RN 73 and could not reproduce the issue.
> 
> If the build is failing for you, could you share a minimal reproducible sample which we can debug?

@krystofwoldrich 

I found out why the build was failing for me. I had this in my Podfile in order to fix a OneSignal related [issue](https://github.com/OneSignal/react-native-onesignal/issues/1272#issuecomment-904957267).

```
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
```

Changing it to the following resolves the issue for me:

```
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.name != "Sentry"
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
      end
    end
```

**Comment by krystofwoldrich** [comment] 2024-08-02 16:22
@Mitch528 Thank you for the message!

**Comment by krystofwoldrich** [comment] 2024-08-09 12:35
We should add information about `APPLICATION_EXTENSION_API_ONLY` to the docs (RN manual setup on iOS, troubleshooting).

**Comment by adityakmr7** [comment] 2024-09-19 09:14
After adding the above changes in my podFile. https://github.com/getsentry/sentry-react-native/issues/3908#issuecomment-2265703635
```
post_install do |installer|
  config = use_native_modules!
  installer.pods_project.targets.each do |target|
	target.build_configurations.each do |config|
	  if target.name != "Sentry"
		config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
	  end
	end
  end
  # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  react_native_post_install(
    installer,
    config[:reactNativePath],
    :mac_catalyst_enabled => false
  )
end

```

I keep on getting this error. Any one know how to fix this.
```
unexpected service error: The Xcode build system has crashed. Build again to continue.

```

**Comment by kahest** [comment] 2024-09-20 13:13
@adityakmr7 I'm not sure this is related - did you cleaning build caches, derived data, etc.? Which version of macOS/Xcode are you using?

**Comment by krystofwoldrich** [comment] 2024-09-30 13:07
@adityakmr7 Have you used `APPLICATION_EXTENSION_API_ONLY` before? We recommend to explicitly set it to `YES` for Sentry at the end of the post install scripts.

More at: https://docs.sentry.io/platforms/react-native/troubleshooting/#unknown-receiver-somereceiver-use-of-undeclared-identifier-someidentifier

**Comment by krystofwoldrich** [comment] 2024-10-04 11:50
Can we remove the need of `APPLICATION_EXTENSION_API_ONLY=YES` from `sentry-cocoa`?

**Comment by krystofwoldrich** [comment] 2024-10-04 12:18
For reference https://developer.apple.com/documentation/xcode/build-settings-reference#Require-Only-App-Extension-Safe-API

**Comment by sahad00** [comment] 2024-10-09 13:11
```
target.build_configurations.each do |config|
	  if target.name != "Sentry"
		config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
	  end
	end
```

This worked cool ! thanks

ref : https://github.com/getsentry/sentry-react-native/issues/3908#issuecomment-2265703635

**Comment by krystofwoldrich** [comment] 2024-10-11 12:24
- https://forums.swift.org/t/set-application-extension-api-only-on-a-spm-package/39333/57
- https://stackoverflow.com/questions/67494911/unable-to-compile-react-native-share-extension-ios-12-5

**Comment by antonis** [comment] 2024-10-25 15:32
By setting [APPLICATION_EXTENSION_API_ONLY](https://developer.apple.com/documentation/xcode/build-settings-reference#Require-Only-App-Extension-Safe-API) to `YES`, we ensure our library is extension-safe, meaning it doesn’t use any APIs prohibited in app extensions. This is typically expected of libraries to maintain broad compatibility.
[Setting APPLICATION_EXTENSION_API_ONLY = YES in our library’s pod_target_xcconfig](https://github.com/getsentry/sentry-cocoa/blob/main/Sentry.podspec#L24) is considered a good practice to ensure that any code within your library will work in both app and extension contexts without imposing restrictions on the app itself.

My understanding is that the need for the troubleshooting workaround [on Cocoa](https://docs.sentry.io/platforms/apple/troubleshooting/#unknown-receiver-somereceiver-use-of-undeclared-identifier-someidentifier) [and React Native](https://docs.sentry.io/platforms/react-native/troubleshooting/#unknown-receiver-somereceiver-use-of-undeclared-identifier-someidentifier) is due to [a CocoaPods issue](https://github.com/CocoaPods/CocoaPods/issues/12093) ([other related issues](https://github.com/search?q=repo%3ACocoaPods%2FCocoaPods+APPLICATION_EXTENSION_API_ONLY&type=issues))propagating the change to the host application.

There are libraries that do not adopt this restriction. For example [Firebase does not use the APPLICATION_EXTENSION_API_ONLY apart from SwiftLint](https://github.com/search?q=org%3Afirebase+APPLICATION_EXTENSION_API_ONLY&type=code) ([Crashlytics does not set the flag](https://github.com/firebase/firebase-ios-sdk/blob/main/FirebaseCrashlytics.podspec#L77)) . What they do is [marking methods that are unavailable in extensions with `NS_EXTENSION_UNAVAILABLE_IOS`, `NS_EXTENSION_UNAVAILABLE`](https://github.com/search?q=org%3Afirebase+NS_EXTENSION_UNAVAILABLE&type=code) or [`@available(*ApplicationExtension, unavailable)` in Swift](https://github.com/search?q=org%3Afirebase+%22ApplicationExtension%2C+unavailable%22&type=code).

> Can we remove the need of `APPLICATION_EXTENSION_API_ONLY=YES` from `sentry-cocoa`?

I think we should keep the option to ensure compatibility with extensions [on Cocoa](https://developer.apple.com/app-extensions/) and [React Native](https://reactnative.dev/docs/app-extensions).

**Comment by krystofwoldrich** [comment] 2024-10-28 16:22
Yes, make sense to keep it to stay compatible with app extensions.

But I think if possible we should be able to compile also with the flag set to `NO`.

What confuses me is that the Cocoa SDK only compiles with the flag set to `YES`.

If this flag only limits the API set I would expect the code also compile without it.

**Comment by iamthemuhammadirfan** [comment] 2024-11-01 03:54
![Image](https://github.com/user-attachments/assets/7df430d2-6eba-482f-a0e7-217f473ab134)

After Installing Xcode16 and with Mac chip M1 Pro and react native versions "0.72.4" and  "@sentry/react-native": "^6.1.0",
I'm getting this error building. 

Command SwiftVerifyEmittedModuleInterface failed with a nonzero exit code

**Comment by antonis** [comment] 2024-11-01 08:36
Thank you for reporting @iamthemuhammadirfan 🙇 
Does the issue still occur after clearing all build caches including derived data?
Is the issue related with the `APPLICATION_EXTENSION_API_ONLY` build setting? If not, please consider opening a separate issue with more details and we will be glad to continue the investigation there 🙇

**Comment by antonis** [comment] 2024-12-13 11:23
Closing since https://github.com/getsentry/sentry-cocoa/pull/4603 is merged 🎉

**Closed by antonis** 2024-12-13 11:23 UTC
Labels: Platform: React-Native
