### ISSUE TITLE
Underlying Objective-C module 'SentryPrivate' not found

### ISSUE THREAD

**Issue by gvash** [getsentry/sentry-react-native#3756] opened 2024-04-15 09:41 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.72.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```const sentryConfig: Sentry.ReactNativeOptions = {
      attachThreads: true,
      beforeSend: beforeSend,
      debug: __DEV__,
      dist,
      dsn: config.SENTRY_DSN,
      enableAutoSessionTracking: true,
      enableNative: false,
      integrations,
      release,
    };
```

---
**I have the following issue:**

Upon upgrading to 5.20.0, I'm able to build for Android but not for iOS. Below the error that I'm getting while building my app using **Xcode v15.2**

<img width="505" alt="Screenshot 2024-04-15 at 3 10 45 PM" src="https://github.com/getsentry/sentry-react-native/assets/147847420/da51122d-4e3e-4a55-8599-669cbd6c2609">

<img width="1311" alt="Screenshot 2024-04-15 at 3 11 31 PM" src="https://github.com/getsentry/sentry-react-native/assets/147847420/3c722848-e013-4827-b4cb-a19237143675">

**Comment by krystofwoldrich** [comment] 2024-04-15 10:27
@gvash Hi, thank you for the message,
the Sentry RN SDK ships with Sentry cocoapod version`8.21.0`, can you confirm this version is installed, when running `pod install`?

**Comment by gvash** [comment] 2024-04-15 16:45
<img width="290" alt="Screenshot 2024-04-15 at 10 12 59 PM" src="https://github.com/getsentry/sentry-react-native/assets/147847420/81caf650-351c-4194-8da6-33c9a7a1113d">

1. Yes, the cocoapod version is `8.21.0`
2. No, I'm not using any Custom GCC. Already checked that issue raised by MetaMask but no help.

**Comment by krystofwoldrich** [comment] 2024-04-16 17:04
@gvash Would you be able to share a minimal reproducible example that we could investigate?

**Comment by krystofwoldrich** [comment] 2024-04-16 17:05
@brustolin Do you any recommendation on what to try?

**Comment by brustolin** [comment] 2024-04-17 07:26
This is strange. Never seen this before.
Since we have remove SentryPrivate from the cocoa SDK, the next RN release wont have this problem.
Any ETA for the next release?

**Comment by krystofwoldrich** [comment] 2024-04-17 10:02
Thank you that's a good point.

The next release of the React Native SDK that will include the latest `sentry-cocoa` without `SentryPrivate` will be released this week. Most likely version 5.22.0.

**Comment by gvash** [comment] 2024-04-17 16:39
I purely see this as an auto linking issue.
Are you guys removing `SentryPrivate` or what?

**Comment by brustolin** [comment] 2024-04-18 07:41
> I purely see this as an auto linking issue.
Are you guys removing SentryPrivate or what?

I dont know why you're having problems with linking and cocoapod, this is our first issue about this.
We did remove SentryPrivate from our native SDK, so, dont matter what is going on with your build setup, this will be solved as soon we release the next RN SDK.

**Closed** 2024-04-26 11:57 UTC
Labels: Platform: React-Native, Waiting for: Community
