### ISSUE TITLE
main.jsbundle.map not found in bundle phase

### ISSUE THREAD

**Issue by francescov1** [getsentry/sentry-react-native#3723] opened 2024-03-27 23:19 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.73.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

I can build and run my app fine locally, but when trying to archive, I get an error related to finding a `main.jsbundle.map` file

As a temporary fix, I reverted the changes made in the `Bundle React Native code and images` phase.

**Steps to reproduce:**
- Run an archive

**Actual result:**

Error. See logs below:

```
+ [[ true == true ]]
+ HBC_SOURCEMAP_FILE='/Users/francescovirga/Library/Developer/Xcode/DerivedData/LighthouseMobile-clqkvaplifyotcdbrajpghsatkgw/Build/Intermediates.noindex/ArchiveIntermediates/LighthouseMobile (Production)/BuildProductsPath/Release-iphoneos/LighthouseMobile.app/main.jsbundle.map'
+ /Users/francescovirga/Projects/lighthouse-mobile/node_modules/@sentry/cli-darwin/bin/sentry-cli /Users/francescovirga/Projects/lighthouse-mobile/node_modules/react-native/scripts/compose-source-maps.js '/Users/francescovirga/Library/Developer/Xcode/DerivedData/LighthouseMobile-clqkvaplifyotcdbrajpghsatkgw/Build/Intermediates.noindex/ArchiveIntermediates/LighthouseMobile (Production)/BuildProductsPath/Release-iphoneos/main.jsbundle.map' '/Users/francescovirga/Library/Developer/Xcode/DerivedData/LighthouseMobile-clqkvaplifyotcdbrajpghsatkgw/Build/Intermediates.noindex/ArchiveIntermediates/LighthouseMobile (Production)/BuildProductsPath/Release-iphoneos/LighthouseMobile.app/main.jsbundle.map' -o '/Users/francescovirga/Library/Developer/Xcode/DerivedData/LighthouseMobile-clqkvaplifyotcdbrajpghsatkgw/Build/Intermediates.noindex/ArchiveIntermediates/LighthouseMobile (Production)/IntermediateBuildFilesPath/LighthouseMobile.build/Release-iphoneos/LighthouseMobile.build/DerivedSources/main.jsbundle.map'
node:internal/fs/sync:25
  return binding.readFileUtf8(path, stringToFlags(flag));
                 ^

Error: ENOENT: no such file or directory, open '/Users/francescovirga/Library/Developer/Xcode/DerivedData/LighthouseMobile-clqkvaplifyotcdbrajpghsatkgw/Build/Intermediates.noindex/ArchiveIntermediates/LighthouseMobile (Production)/BuildProductsPath/Release-iphoneos/main.jsbundle.map'
    at Object.readFileUtf8 (node:internal/fs/sync:25:18)
    at Object.readFileSync (node:fs:441:19)
    at Object.<anonymous> (/Users/francescovirga/Projects/lighthouse-mobile/node_modules/react-native/scripts/compose-source-maps.js:34:8)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/francescovirga/Library/Developer/Xcode/DerivedData/LighthouseMobile-clqkvaplifyotcdbrajpghsatkgw/Build/Intermediates.noindex/ArchiveIntermediates/LighthouseMobile (Production)/BuildProductsPath/Release-iphoneos/main.jsbundle.map'
}

Node.js v20.9.0
Command PhaseScriptExecution failed with a nonzero exit code

```

**Expected result:**

No error

**Comment by krystofwoldrich** [comment] 2024-04-02 09:59
Hi @francescov1,
thank you for the message.

It seems like the packager source map was not found at the expected location `/Users/francescovirga/Library/Developer/Xcode/DerivedData/LighthouseMobile-clqkvaplifyotcdbrajpghsatkgw/Build/Intermediates.noindex/ArchiveIntermediates/LighthouseMobile (Production)/BuildProductsPath/Release-iphoneos/main.jsbundle.map`.

From the stack trace I don't see why that would happen, can you share the build phase changes, do they match our documentation? https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/#configure-automatic-source-maps-upload

**Comment by francescov1** [comment] 2024-04-02 19:36
@krystofwoldrich  Thanks for the reply. I used the automated CLI setup. Here's the relevant build phases:

Bundle React Native code and images (note the change I made at the end, this is the workaround I had to do to get this to work, essentially skip the Sentry step).
```bash
set -e

# https://github.com/facebook/react-native/issues/25522#issuecomment-509036251
export NODE_BINARY=$(which node)

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"

#/bin/sh -c "$WITH_ENVIRONMENT \"/bin/sh ../node_modules/@sentry/react-native/scripts/sentry-xcode.sh $REACT_NATIVE_XCODE\""
/bin/sh -c "$WITH_ENVIRONMENT $REACT_NATIVE_XCODE"
```

Upload Debug Symbols to Sentry:
```bash
/bin/sh ../node_modules/@sentry/react-native/scripts/sentry-xcode-debug-files.sh
```

**Comment by krystofwoldrich** [comment] 2024-04-04 10:56
Hi @francescov1,
thank you for the build phases they are correct.

The issue is with the white space in your project path `LighthouseMobile (Production)`, this is a known React Native issue, and it will be fixed in RN 0.74, until then you have to adjust the path, in this case, the archive name.

`sentry-xcode.sh` enables source maps automatically that's why the build fails when using the Sentry Script.

- RN PR for more details https://github.com/facebook/react-native/pull/40937

**Closed by krystofwoldrich** 2024-04-04 10:56 UTC
Labels: Platform: React-Native, Waiting for: Product Owner

**Comment by klosowsk** [comment] 2024-04-05 20:04
This is how I fixed the issue after a react native version upgrade:
https://stackoverflow.com/a/78282118/6084008

**Comment by francescov1** [comment] 2024-04-08 18:52
@krystofwoldrich Thanks for your response, what exactly do I need to change to fix this? Do you mean to change the entire project name, or is there some path I can tweak for an easy fix? I suspect I just need to escape the whitespace character somewhere in one of the scripts?

**Comment by pavelglebov** [comment] 2024-09-04 11:11
I have the same error, but I don't have spaces in folder structure. So the issue is in something else
