### ISSUE TITLE
Cannot compile with "use_frameworks"

### ISSUE THREAD

**Issue by hanayashiki** [getsentry/sentry-react-native#1176] opened 2020-11-07 23:43 UTC
**OS:**
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

**Platform:**
- [x ]  iOS
- [ ]  Android

**SDK:**
- [x ]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [ ]  Yes
- [ x]  No

**Are you using sentry.io or on-premise?**
- [x ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
**I have following issue:**

[Description]

**Steps to reproduce:**
- Step 1
`Podfile` with `use_frameworks!`
- Step 2
Install `@sentry/react-native` as documented

**Actual result:**

When compiling `RNSentry.m`
```
'Sentry/SentryFileManager.h' file not found
```
(**Workaround**: remove this line and it works)

**Expected result:**

Successfully compiles.

I think it is probably due to that `Sentry/SentryFileManager.h` is not included in the framework. But in fact it is not needed.

**Comment by sandy2008** [comment] 2020-11-08 03:07
Really need help on this

**Comment by jennmueng** [comment] 2020-11-08 09:42
Closing this as it is a duplicate of https://github.com/getsentry/sentry-react-native/issues/1171. We'll look to fix this soon for now you can use the workaround mentioned in the other issue as you SHOULD NOT remove the line that imports `Sentry/SentryFileManager.h` otherwise uncaught errors in production will not be detected by Sentry.

**Closed by jennmueng** 2020-11-08 09:42 UTC
