### ISSUE TITLE
Manual TTID/TTFD API times out

### ISSUE THREAD

**Issue by serglom21** [getsentry/sentry-react-native#3934] opened 2024-07-09 00:36 UTC
**Platform:**
- [x]  iOS

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.22.0

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

```
export const routingInstrumentation = new Sentry.ReactNavigationInstrumentation(
  {
    enableTimeToInitialDisplay: true,
  },
);


Sentry.init({
  environment: 'development'
  sampleRate: 1.0,
  tracesSampleRate: 0.1,
  enableAppHangTracking: false,
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation,
      tracePropagationTargets: [currentConfig.DOMAIN],
    }),
  ],
});
```
---
**I have the following issue:**

I am seeing some inconsistencies in the data reported and what should be reported based on the SDK behaviour. For example, it is odd to me that some transactions are being marked as '***deadline_exceeded***' when they do not exceed the default value for [[finalTimeoutMs](https://github.com/getsentry/sentry-react-native/blob/main/src/js/tracing/reactnativetracing.ts#L61)]. `finalTimeoutMs` is also not being overridden in the init code block

The default for `finalTimeoutMs` is 600000ms or 10mins, which is way above what the transactions being marked deadline_exceeded are reporting. The amount of failed transactions with this status seems to have increased after updating the SDK version from `5.3.0` to `5.22.0`

More details with links to examples in the [Customer Case](https://www.notion.so/sentry/Increase-in-deadline_exceeded-after-upgrade-9d472c310520417eb9ed4ab72a554dcc?pvs=4)

**Comment by krystofwoldrich** [comment] 2024-07-10 15:09
Hi @serglom21,
thank you for the message,

I agree, it doesn't sound right, that these transaction are marked as `deadline_exceeded`. I'll take a look at the examples and keep you updated.

**Comment by lucas-zimerman** [comment] 2024-08-19 17:13
Are you using something on the screens with `deadline_exceeded` a code called `Stack.Navigator` to switch between different pages? You can usually find it by looking for the term <Stack.Navigator> in your code

**Comment by julianosbentowellhub** [comment] 2024-08-19 17:22
> Are you using something on the screens with `deadline_exceeded` a code called `Stack.Navigator` to switch between different pages? You can usually find it by looking for the term <Stack.Navigator> in your code

Yep, we are using the `Stack.Navigator`.

**Comment by lucas-zimerman** [comment] 2024-08-22 20:44
Hi, I found a potential fix for your case and a solution will be implemented soon on the SDK.

**Comment by julianosbentowellhub** [comment] 2024-08-22 21:03
> Hi, I found a potential fix for your case and a solution will be implemented soon on the SDK.

@lucas-zimerman thanks a lot for it, we are expecting to solve this issue ASAP to normalize our `failure_rate` metrics. When you had an stable version with the fix, could you share it here, pls?

**Comment by kahest** [comment] 2024-08-26 14:07
@julianosbentowellhub definitely, we'll update here when the [fix](https://github.com/getsentry/sentry-react-native/pull/4042) is verified and released.

**Comment by krystofwoldrich** [comment] 2024-09-12 11:41
Hi @jimmysafe,
thank you for the message,

are there any specific span in the transactions, which are causing the deadline_exceeded? For example the Time To Display spans?

**Comment by jimmysafe** [comment] 2024-09-13 07:36
Hi @krystofwoldrich 

The span which hangs and fails is the `navigation` span, i guess the issue is related to the fact we are using the `<Stack.Navigator>` in react native.

Also the Time to inital display is affected too by being always cancelled.

![Image](https://github.com/user-attachments/assets/1827d251-e669-4a53-9cb2-f8f261da249e)


Please let me know if you need more info :)

**Comment by krystofwoldrich** [comment] 2024-09-13 10:59
@jimmysafe Thank you for the confirmation,
- this will be fixed by https://github.com/getsentry/sentry-react-native/pull/4042

At the moment you can use manual TTID APIs https://docs.sentry.io/platforms/react-native/tracing/instrumentation/time-to-display/#time-to-initial-display-overwrite as a workaround or temporarly disable the feature.

**Comment by sregg** [comment] 2024-09-13 11:01
Even with manual ttids we see 80% cancelled or deadline_exceeded with 15s
duration.

**Comment by krystofwoldrich** [comment] 2024-09-13 11:25
Hi @sregg,
thank for the message,

are you experiencing this on iOS or Android?

**Comment by sregg** [comment] 2024-09-13 11:30
iOS and Android.
It's mostly in the wild from now but I can try to repro locally.
I believe last time I was seeing that when I would navigate back to the screen.
I'll report back.

**Comment by sregg** [comment] 2024-09-13 14:34
Also, is it normal that the status is `unknown` when it's not timing out?
![Image](https://github.com/user-attachments/assets/5e6f7be8-d2aa-4bbd-99d2-767137f52b81)
Here's our home screen for example:
![Image](https://github.com/user-attachments/assets/e80dc246-3655-4563-9243-8f429844a205)

**Comment by sregg** [comment] 2024-09-13 14:44
I'm able to repro the `deadline_exceeded` and the 15s timeout every time when navigating back to a screen
![Image](https://github.com/user-attachments/assets/6dc6e1b8-a00d-41aa-bcd2-033607f0e4b9)

**Comment by jimmysafe** [comment] 2024-09-13 16:16
@sregg  same here, we get tons of unknown status and i can confirm that even by using the ` <Sentry.TimeToInitialDisplay record={true} />` the issue of of `deadline_exceeded` persists.

**Comment by sregg** [comment] 2024-09-16 12:03
> Thank you both for the reports, we're working on this. Which versions of the SDK are you using?

v5.31.1

**Comment by krystofwoldrich** [comment] 2024-10-07 14:16
Hi @jimmysafe,
we are still looking into this.

**Closed** 2024-10-30 18:39 UTC
Labels: Platform: React-Native
