### ISSUE TITLE
`react-native-network-logger` breaks `xhr` breadcrumbs

### ISSUE THREAD

**Issue by VitamineC** [getsentry/sentry-react-native#2779] opened 2023-01-23 22:34 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.13.0

**`react-native` version:** 0.66.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
 Sentry.init({
    dsn: 'DNS',
    tracesSampleRate: 1.0,
    environment: Config.TENANT,
    integrations: [
      new Sentry.ReactNativeTracing({
        routingInstrumentation,
      }),
    ],
    debug: true,
    beforeBreadcrumb(event, hint) {
      if (event.category === 'console' && event.level === 'log') {
        return null
      }
      return event
    },
  })
```
---
**I have following issue:**
Http requests ( with axios ) doesn't appear in breadcrumbs in sentry console 

**Steps to reproduce:**
- run app 

part of xcode logs  - I think it can be connected
```
captureFailedRequestsEnabled is disabled
```

**Comment by krystofwoldrich** [comment] 2023-01-24 11:03
The `axios` requests should appear as `xhr` requests in the breadcrumbs.

Could you send a minimal reproducible example?

I've tried this and the request appears in breadcrumbs.

```js
<TouchableOpacity
  onPress={async () => {
    await axios('http://localhost:8081'); //Simple request to the dev server
    console.log('HTTP Request Done');
    Sentry.captureMessage('HTTP Request Done');
  }}>
  <Text style={styles.buttonText}>Capture Message After Axios Request</Text>
</TouchableOpacity>
```

**Comment by VitamineC** [comment] 2023-01-24 11:08
I think it can be problem with installation  because I see captureFailedRequestsEnabled is disabled in console (xcode) 
Can it be reason?

**Comment by VitamineC** [comment] 2023-01-24 12:52
@krystofwoldrich  I found reason and it's really weird 
If application crashed by native (!) for example ```Sentry.nativeCrash()``` I can see system and http and system in breadcrumbs , but if it is crashed by JS for example ```Sentry.captureException('test')``` or ```undefined.test``` It doesn't exist. 
Is it expected behaviour ?

**Comment by krystofwoldrich** [comment] 2023-01-24 14:54
@VitamineC 

This log can be the reason. This is from the underlying `sentry-cocoa` SDK, but the `axios` requests are using `xhr` and these breadcrumbs are recorded in the JS layer.

```log
2023-01-24 13:23:39.096088+0100 ShineMobileApplication[17086:1403422] [Sentry] [debug] [SentryNetworkTracker:296] captureFailedRequestsEnabled is disabled, not capturing HTTP Client errors.
```

Can you share a bit more code on how you test this? Is it possible that no request happened when you called `Sentry.captureException`?

Or can you share a minimal reproducible example?

**Comment by VitamineC** [comment] 2023-01-25 13:44
@krystofwoldrich  I found a reason: 
We are using this library https://www.npmjs.com/package/react-native-network-logger also. If I removed it everything  ok with sentry

**Comment by krystofwoldrich** [comment] 2023-01-26 09:35
Likely `react-native-network-logger` clashes with the Sentry `xhr` instrumentation. But as it's a dev tool in a production environment the breadcrumbs work correctly, @VitamineC?

**Comment by VitamineC** [comment] 2023-01-26 09:36
@krystofwoldrich Yes

**Comment by krystofwoldrich** [comment] 2023-01-26 09:45
Likely the `react-native-network-logger` `xhr` patch clashes with the [Sentry one](https://github.com/getsentry/sentry-javascript/blob/c6f9dfe9570369c9acabec988f8a573d08bd8c82/packages/utils/src/instrument.ts#L216). But as  `react-native-network-logger`is dev tool in production this is not an issue. Is that correct? @VitamineC

**Comment by VitamineC** [comment] 2023-01-26 09:48
50\50 we are using react-native-network-logger together with sentry on stage, so I think It will be better If sentry can works with tools like react-native-network-logger. 
Or At least write in log that if it can't handle xhr because It's a confusing behavior

**Comment by krystofwoldrich** [comment] 2023-01-26 10:55
Okay, thanks for the explanation.

**Comment by krystofwoldrich** [comment] 2023-02-13 14:19
We need to check how to `react-native-network-logger` patches the `xhr` and `fetch` methods and based on that we can either fix it in our SDK or open an issue at the `react-native-network-logger` project.

**Comment by krystofwoldrich** [comment] 2023-05-19 10:50
We have tested the behavior with `@sentry/react-native@5.5.0` and `react-native-network-logger@1.14.1 ` and we are getting both `xhr` breadcrumbs and logs in the app.

<img width="1321" alt="Screenshot 2023-05-19 at 12 49 07" src="https://github.com/getsentry/sentry-react-native/assets/31292499/db09ff15-0eb4-4dec-81c1-2f35197eb405">

If this is still an issue please share with us a minimal reproducible example so we can debug it. For now, I'm closing the issue.

**Closed by krystofwoldrich** 2023-05-19 10:50 UTC
Labels: Status: Backlog, Platform: React-Native
