### ISSUE TITLE
Native crash not reported on Android

### ISSUE THREAD

**Issue by maleking** [getsentry/sentry-react-native#886] opened 2020-05-28 21:09 UTC
**OS:**
`MacOS`

**Platform:**
 `Android`

**SDK:**
  `@sentry/react-native  1.4.0`

**`react-native` version:**  `0.61.5`(Hemes:true)

**Are you using Expo?**
` No`

**Are you using sentry.io or on-premise?**
`on-premise`
**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```
---
**I have following issue:**

`Sentry.captureException(error);` capture js error but `Sentry.nativeCrash();` don't report any error in ours Self-Hosted Sentry  server

**Steps to reproduce:**
1-install  and setup sentry based on  https://docs.sentry.io/platforms/react-native https://docs.sentry.io/platforms/react-native
2-call `Sentry.nativeCrash();` in production apk

**Comment by marandaneto** [comment] 2020-06-05 08:28
hey @maleking thanks for raising this

could you enable the debug mode and copypasta the logs, please? thanks.

**Comment by maleking** [comment] 2020-06-07 04:07
how to enable debug mode in sentry @marandaneto  ?

**Comment by marandaneto** [comment] 2020-06-07 06:43
@maleking 
just pass the `debug` flag on the SDK init.

```
Sentry.init({ 
  dsn: 'dsn...', 
  debug: true
});
```

**Comment by maleking** [comment] 2020-06-11 05:35
this is sentry log 
Sentry Logger [Log]: Integration installed: ReactNativeErrorHandlers
logger.js:31 Sentry Logger [Log]: Integration installed: Release
logger.js:31 Sentry Logger [Log]: Integration installed: InboundFilters
logger.js:31 Sentry Logger [Log]: Integration installed: FunctionToString
logger.js:31 Sentry Logger [Log]: Integration installed: Breadcrumbs
logger.js:31 Sentry Logger [Log]: Integration installed: LinkedErrors
logger.js:31 Sentry Logger [Log]: Integration installed: UserAgent
logger.js:31 Sentry Logger [Log]: Integration installed: DebugSymbolicator
logger.js:31 Sentry Logger [Log]: Integration installed: RewriteFrames
logger.js:31 Sentry Logger [Log]: Integration installed: DeviceContext

**Comment by marandaneto** [comment] 2020-06-14 07:52
@maleking this is the log from react-native (JS layer), I'm more interested in the Android logs (from logcat), you can copy-paste that from AS.

I need to understand the output of the error in order to test and reproduce it, thanks.

**Comment by crobinson42** [comment] 2020-06-30 15:21
I'm experiencing this issue too - let me get some logs today and post them here.

**Comment by marandaneto** [comment] 2020-07-02 06:55
@crobinson42 please share some logs :) thanks

**Comment by maleking** [comment] 2020-07-02 08:31
i created a release apk  and call

**Comment by maleking** [comment] 2020-07-02 08:40
@marandaneto I call  Sentry.nativeCrash() in release apk and this is AS logs

=================================
2020-07-02 12:58:57.434 7090-7150/? E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.maleking.app, PID: 7090
    java.lang.RuntimeException: TEST - Sentry Client Crash (only works in release mode)
        at io.sentry.RNSentryModule.crash(RNSentryModule.java:167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
        at android.os.Looper.loop(Looper.java:237)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
        at java.lang.Thread.run(Thread.java:919)
2020-07-02 12:58:57.448 7090-7186/? D/Sentry: Adding Event to offline storage: /data/user/0/com.maleking.app/cache/sentry/d775f636555641539d4eae327a3aefe6.sentry-event
2020-07-02 12:58:57.479 4689-6646/? W/ActivityManager: crash : com.maleking.app,0
2020-07-02 12:58:57.481 4689-6646/? W/ActivityTaskManager:   Force finishing activity com.maleking.app/.MainActivity
2020-07-02 12:58:57.494 4689-6646/? V/WindowManager: Changing focus from Window{246ddd4 u0 com.maleking.app/com.maleking.app.MainActivity} to null displayId=0 Callers=com.android.server.wm.RootWindowContainer.updateFocusedWindowLocked:203 com.android.server.wm.WindowManagerService.updateFocusedWindowLocked:6099 com.android.server.wm.ActivityDisplay.setFocusedApp:1500 com.android.server.wm.ActivityTaskManagerService.setResumedActivityUncheckLocked:6708 com.android.server.wm.ActivityRecord.moveFocusableActivityToTop:1799 com.android.server.wm.ActivityDisplay.moveHomeActivityToTop:1591 
2020-07-02 12:58:57.541 4499-7527/? D/AppErrorNotification: errorType : 24, process : com.maleking.app , uid : 0
2020-07-02 12:58:57.636 4170-4170/? I/SurfaceFlinger: Display 0 HWC layers:
        type    |    handle    | flag |  format   |   source crop (l,t,r,b)    |         frame       | name 
    ------------+--------------+------+-----------+----------------------------+---------------------+------
         DEVICE | 0x7382869800 | 0002 | RGBA_8888 |   0.0    0.0 1080.0 2340.0 |    0    0 1080 2340 | com.maleking.app/com.maleking.app.MainActivity$_7090#0
         DEVICE | 0x7382868040 | 0000 | RGBA_8888 |   0.0    0.0 1080.0   83.0 |    0    0 1080   83 | StatusBar$_5011#0
         DEVICE | 0x7382867b40 | 0000 | RGBA_8888 |   0.0    0.0 1080.0  126.0 |    0 2214 1080 2340 | NavigationBar0$_5011#0
         DEVICE | 0x73847ec980 | 0000 | RGBA_8888 |   0.0    0.0 1080.0  151.0 |    0    0 1080  151 | ScreenDecorOverlay$_5011#0
         DEVICE | 0x73a4e67880 | 0000 | RGBA_8888 |   0.0    0.0 1080.0  151.0 |    0 2189 1080 2340 | ScreenDecorOverlayBottom$_5011#0
2020-07-02 12:58:57.646 4689-4846/? W/InputDispatcher: channel '246ddd4 com.maleking.app/com.maleking.app.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9, fd=708
2020-07-02 12:58:57.646 4689-4846/? E/InputDispatcher: channel '246ddd4 com.maleking.app/com.maleking.app.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-07-02 12:58:57.693 4689-4861/? I/WindowManager: WIN DEATH: Window{246ddd4 u0 com.maleking.app/com.maleking.app.MainActivity}
2020-07-02 12:58:57.693 4689-4861/? W/InputDispatcher: Attempted to unregister already unregistered input channel '246ddd4 com.maleking.app/com.maleking.app.MainActivity (server)'
2020-07-02 12:58:57.725 4689-5093/? I/ActivityManager: Process com.maleking.app (pid 7090) has died: vis+99 TOP (174,576)
2020-07-02 12:58:57.737 4689-5093/? V/WindowManager: Setting visibility of Window{246ddd4 u0 com.maleking.app/com.maleking.app.MainActivity EXITING}: false, caller=com.android.server.wm.WindowContainer.sendAppVisibilityToClients:640 com.android.server.wm.AppWindowToken.setClientHidden:621 com.android.server.wm.AppWindowToken.onAnimationFinished:3516 com.android.server.wm.AppWindowToken.commitVisibility:859 com.android.server.wm.AppWindowToken.onRemovedFromDisplay:1096 
2020-07-02 12:58:57.741 4689-5093/? E/WindowManager: win=Window{246ddd4 u0 com.maleking.app/com.maleking.app.MainActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1199 com.android.server.wm.AppWindowToken.destroySurfaces:1180 com.android.server.wm.WindowState.onExitAnimationDone:5030 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:3539 com.android.server.wm.AppWindowToken.commitVisibility:859 
....

=============================

**Comment by marandaneto** [comment] 2020-07-03 06:55
@maleking are you running in release mode?
The log states: TEST - Sentry Client Crash `(only works in release mode)`

**Comment by maleking** [comment] 2020-07-03 07:39
> @maleking are you running in release mode?
> The log states: TEST - Sentry Client Crash `(only works in release mode)`

**Comment by maleking** [comment] 2020-07-03 07:42
yes, i created a signed apk with `./gradlew assembleRelease` command and then with `adb logcat `capture the log

**Comment by marandaneto** [comment] 2020-07-03 10:52
@maleking this is likely not the right thing, because logcat is not available on release builds.
I have a question though, when you call `Sentry.nativeCrash()`, do you experience a hard crash or do you get that Redbox screen on your App?

**Comment by maleking** [comment] 2020-07-03 11:04
@marandaneto I get a hard crash of course because its a release build :) 
what do you means logcat not available in release builds  ?
i always check logcat  for debugging crash in release mode

**Comment by tlrobinson** [comment] 2020-09-29 19:12
I am seeing this too. Throwing an uncaught JS error or calling `Sentry.captureException` works, but calling `Sentry.nativeCrash()` is not reported.

```
react-native 0.63.2
@sentry/react-native 1.8.2
```

**Comment by shubhamkes** [comment] 2020-12-16 11:01
Did this issue solved? I am still facing it @^2.1.0

**Comment by marandaneto** [comment] 2020-12-16 11:23
can you double-check that the flag `enableNativeCrashHandling` is still `true`?

@jennmueng could you have a look at this?

**Comment by shubhamkes** [comment] 2020-12-17 11:28
thought its enabled by default. Though added now but still cant see logs in dashboard

**Comment by jennmueng** [comment] 2020-12-17 11:38
@shubhamkes Just to confirm, does the app actually crash for you and nothing is reported, or does the native crash method do nothing? We have tested this out on our end to confirm that it should be working and if it’s not working for you I believe the issue is most likely with the installation or some configuration.

It would greatly help us if you can provide a producible example in a repo for us to try out to be able to give you a clearer answer.

**Comment by yasirtrimulabs** [comment] 2021-02-26 12:38
Hi @marandaneto I am facing the same thing on Android and it shows the error in red box. But on iOS it's working
![Screenshot_20210226-173731_PatientApp](https://user-images.githubusercontent.com/62023757/109301185-68c38a80-7859-11eb-98cd-4d97fd0c7b3e.png)

**Comment by marandaneto** [comment] 2021-02-27 09:46
@yasirtrimulabs well as stated before, and also in the red dialog, it works only on release mode.

**Comment by marandaneto** [comment] 2021-02-27 09:47
@jennmueng could you run a hard crash on the latest RN on Android, please? just to be sure it works.

**Comment by yasirtrimulabs** [comment] 2021-03-04 08:47
@marandaneto I fixed this was following [this](https://github.com/facebook/react-native/issues/17522#issuecomment-357410014)

**Comment by jennmueng** [comment] 2021-03-04 12:34
@yasirtrimulabs That was what I assumed, as the dev menu should never show on release mode.

**Comment by marandaneto** [comment] 2021-03-04 13:05
@jennmueng should we close this issue then?

**Closed** 2021-03-05 08:41 UTC
Labels: Platform: Android
