### ISSUE TITLE
Webpack build broken; 'requireNativeComponent' is not exported from 'react-native'

### ISSUE THREAD

**Issue by fb55** [getsentry/sentry-react-native#3829] opened 2024-05-20 11:28 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android
- [x] Web

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.22.2

**`react-native` version:** 0.74.1

**Are you using Expo?**
- [x]  Yes
- [ ]  No

---
**I have the following issue:**

Webpack builds were broken ([again](https://github.com/getsentry/sentry-react-native/issues/3527)) in a recent version, now with the message:

> Attempted import error: 'requireNativeComponent' is not exported from 'react-native' (imported as 'requireNativeComponent').

from `@sentry/react-native/dist/js/tracing/timetodisplaynative.js`.

First reported in https://github.com/getsentry/sentry-react-native/issues/3527#issuecomment-2093216801.

**Steps to reproduce:**
Run a web build of the `@sentry/react-native` with Webpack (eg. using the Expo Webpack preset).

Reverting to `5.19.2` resolves the issue.

**Actual result:**

> Attempted import error: 'requireNativeComponent' is not exported from 'react-native' (imported as 'requireNativeComponent').

**Expected result:**

Builds successfully.

**Comment by krystofwoldrich** [comment] 2024-05-27 11:17
Hi @fb55,
thank you for the message, 
I'll close this as duplicate of https://github.com/getsentry/sentry-react-native/issues/3823,

I've added the note that this causes a failed build as well depending on the setup.

**Closed by krystofwoldrich** 2024-05-27 11:17 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
