### ISSUE TITLE
TypeError: Cannot convert undefined value to object

### ISSUE THREAD

**Issue by Amurmurmur** [getsentry/sentry-react-native#3160] opened 2023-07-04 11:28 UTC
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.0.0

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`sentry-expo`)
```
  Sentry.init({
    dsn: Constants?.expoConfig?.extra?.sentryDsn,
    enableInExpoDevelopment: true,
    debug: true
  });
```

---
**I have following issue:**

[Description]
Getting a
WARN Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot convert undefined value to object

And a whats shown on a screenshot:
non-std C++ exception

Works just find when using bugsnag, so its 100% this package causing it.

**Steps to reproduce:**
- Step 1
-  Just follow sentry-expo instructions
- start expo-devclient

**Actual result:**

[Actual result]
![image](https://github.com/getsentry/sentry-react-native/assets/8608333/23d516ec-50c6-4fc7-b9f0-d3c9edd8a842)

**Expected result:**

[Expected result]

**Comment by krystofwoldrich** [comment] 2023-07-04 12:46
Hi,
thanks for the reproducible example. Does it include the non-std C++ exception and the Promise.allSettled? Or only one of them?

**Comment by krystofwoldrich** [comment] 2023-07-04 13:10
What are the steps to reproduce the `non-std C++ exception`? Does it also happen in the repro app?

Thanks for the promise repro, we are investigating why it's happening, it's related to our patch of promises. You can disable the patch, but unhandled promise rejections will not be caught by Sentry.

```js
Sentry.init({
  integrations: [
    new Sentry.Native.Integrations.ReactNativeErrorHandlers({
      patchGlobalPromise: false,
    }),
  ]
});
```

**Comment by krystofwoldrich** [comment] 2023-07-05 08:23
I will close this since the original `non-std C++ exception` and the `Promise.allSettled` issues have been resolved.

Regarding the log, those are enabled only if `debug: true` in Sentry Options, so just make sure to turn off debug for production.

**Closed by krystofwoldrich** 2023-07-05 08:23 UTC
Labels: sentry-expo, Platform: React-Native, Waiting for: Product Owner

**Comment by frozencap** [comment] 2024-05-25 10:06
`Promise.allSettled` also fails for us (expo50, react-native 0.73.6)
wrapped in a try/catch, it throws. By design `Promise.allSettled` should never throw! 
Not even sure how to begin debugging this or where the issue is coming from. 
Any ideas ? 

![Screenshot 2024-05-25 at 11 05 16 AM](https://github.com/getsentry/sentry-react-native/assets/81338316/a3641d9f-60a3-455b-95cd-c4bbc11ac683)
