### ISSUE TITLE
Mismatch exception app version

### ISSUE THREAD

**Issue by fcaldarelli** [getsentry/sentry-react-native#3444] opened 2023-12-01 09:05 UTC
I encountered a mismatch in the version associated with the crash if an app update was performed after the crash.

For example, our app has 4.8.1 release version.

1) An exception happened, with 4.8.1 version;
2) Update the app with 4.8.2 version;
3) After open the updated app (4.8.2), the exception is linked to new version (4.8.2), instead right version (4.8.1).

Maybe Sentry attaches current app version when send the exception to server, instead exception occurred app version.

**Comment by fcaldarelli** [comment] 2023-12-01 09:41
I checked on React Native iOS

**Comment by krystofwoldrich** [comment] 2023-12-01 09:47
@fcaldarelli Thank you, what Sentry RN SDK version are you using?

**Comment by fcaldarelli** [comment] 2023-12-01 09:48
sentry.cocoa.react-native: 8.13.0

**Comment by krystofwoldrich** [comment] 2023-12-15 12:38
Since we can't reproduce the issue I'm closing this. In case there is a new context or reproducible example, please, comment here and we can reopen it.

**Closed by krystofwoldrich** 2023-12-15 12:38 UTC
Labels: Platform: React-Native
