### ISSUE TITLE
auto generated release names not accepted

### ISSUE THREAD

**Issue by tijs** [getsentry/sentry-react-native#914] opened 2020-06-05 07:35 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [x]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 1.4.1

**`react-native` version:** 0.61.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

This is an issue regarding source map uploading

**Configuration:**

using the default iOS source map uploading steps in iOS (xcode) & Android (gradle)

---
**I have following issue:**

I have setup react-native sentry using the default setup as outlined in the docs. Using the upload source maps steps as added by the sentry wizard.

for both iOS and Android however the release names generated in the default setup are now allowed by sentry. 

The error message (and generated release name) is the same on both platforms:

```
error: API request failed
  caused by: sentry reported an error: request failure (http status: 400)
  Object({"version": Array([String("Release with name nl.pzc.news@build feature/POPKUBUS-2032 (1591336311)+16656 is not allowed")])})
```

In both cases the builds are created on Bitrise and the builds thus fail on this step.

I would like to keep using the automated source map uploads but perhaps i can add some configuration to make these names fit whatever requirements Sentry apparently has for these names. I cannot find these requirements in the docs btw.

**Steps to reproduce:**
- install "@sentry/react-native"
- run the installation wizard to add builds steps
- run a new build on bitrise

**Actual result:**

build fails with the above error

**Expected result:**

a working build and related source maps for this build in Sentry

**Comment by tijs** [comment] 2020-06-05 08:32
Ideally i would like to configure this part of the sentry.gradle script (and the corresponding iOS one) so it uses a release name of my choosing:

```
def releaseName = "${variant.getApplicationId()}@${variant.getVersionName()}+${versionCode}"
```

I'm guessing what is generated now is not accepted due to the spaces or the length?

**Comment by StarryFire** [comment] 2020-06-09 16:43
Yes, i would also like a way to customize the releaseName via sentry.properties or via passing an argument in the build script for sentry

**Comment by tijs** [comment] 2020-06-09 18:22
@StarryFire yes! indeed. or maybe just an exported RELEASE_NAME variable like it currently passes variables to the cli in the xcode build script.

**Comment by zmnv** [comment] 2020-06-09 19:54
At the last month I sent artifacts from xcode via 
```
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

and then artifacts puts in `Release 2.2.0` (the same semver, different dists in one group)
Today its broken... Artifacts puts outside of 'environment' and has name 'com.app@@2.2.0+333' it's so ridiculous. Nothing changes by me, but it's just broken.... 

selfhosted sentry

**Comment by iBotPeaches** [comment] 2020-10-05 21:51
Just so this isn't abandoned. The automatic uploading of sourcemaps seems so wonderful till you realize it creates its own release and they never get associated properly because of it.

I had to add a plugin to basically sed the build.gradle file on Android so Sentry could even read proper version name/code since it wasn't reading whatever environment fastlane uses to ad-hoc version on the fly.

Sentry then built a release version for me like combing strings in attempt to build one for me. Why can't it just use an environment variable or even properties file of a release I already have? It seems weird that one step of my build process for uploading sourcemaps wants to make all these assumptions.

It gets hardcoded here - https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L66 and https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L168 - Am I doing something wrong?

How do others make this work?

<img width="1181" alt="Screen Shot 2020-10-05 at 5 48 03 PM" src="https://user-images.githubusercontent.com/611784/95135759-ed8afc00-0732-11eb-9004-9643561608b5.png">

I may have releases automated and working well, but this one step ignores all those environment variables and then just makes a version on some old hard-coded version name/code variables.

I would prefer just to tell Sentry to stop uploading these period and do it myself with sentry-cli, but I can't figure that out without some hacky gradle changes (see https://github.com/getsentry/sentry-react-native/issues/1042)

**Comment by jChris85** [comment] 2021-07-12 19:24
@iBotPeaches Did you found a solution for this? I am facing the same issue.

**Comment by iBotPeaches** [comment] 2021-07-12 19:26
> @iBotPeaches Did you found a solution for this? I am facing the same issue.

Nothing pretty. I hack out the job that runs

```
gradle.projectsEvaluated {
    def tasksToSkip = project.tasks.matching {
        it.name.contains("SentryUpload")
    }
    tasksToSkip.all { enabled = false }
}
```

and build/upload my own sourcemaps with sentry-cli.

**Comment by iBotPeaches** [comment] 2021-11-04 15:20
Please don't close. Working around Sentry because it automatically makes release names that don't match our preference is highly annoying. Forcing all these workarounds.

I would hope it could first check if `SENTRY_RELEASE` is defined and use then, then fallback to the auto generated one, then my life would be less stressful :)

**Comment by marandaneto** [comment] 2021-11-05 13:28
seems like we can patch https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L66-L67 to make it as https://github.com/getsentry/sentry-react-native/blob/master/sentry.gradle#L168-L170

I'd need to check if the iOS config actually does the same checking the env. var.

**Comment by marandaneto** [comment] 2021-11-08 13:56
Android and iOS already do respect the `SENTRY_RELEASE` and `SENTRY_DIST` env. var.
@iBotPeaches are you using the latest version? can you give it a try?

**Comment by iBotPeaches** [comment] 2021-11-08 13:59
> Android and iOS already do respect the `SENTRY_RELEASE` and `SENTRY_DIST` env. var. @iBotPeaches are you using the latest version? can you give it a try?

Sorry, there are so many pieces to this. There is the RN package, the individual Android/iOS behind the scenes of it. The fastlane plugin, the gradle plugin, the sentry-cli.

I try and stay up to date with all of them, but clarity which package was affected and then updated would help me track down if its resolved or not. Since I have to undo workarounds to test this.

**Comment by marandaneto** [comment] 2021-11-08 15:01
using the latest RN SDK, you don't have to fiddle with multiple things, but rather export the env. vars. and initing the SDK with custom release and dist, eg:

```
// export vars
export SENTRY_RELEASE="my.custom.release@3.0.0"
export SENTRY_DIST="3"

// init SDK
Sentry.init({ 
  dsn: '...', 
  release: 'my.custom.release@3.0.0',
  dist: '3',
});

// compile and run release mode
npx react-native run-ios --configuration Release
npx react-native run-android --variant release

```

this way it respects your custom release, source maps are uploaded with your custom release and symbolication works.
just tested it on Android and iOS, so closing it.

**Closed by marandaneto** 2021-11-08 15:01 UTC
Labels: Type: :beetle: Bug, Platform: Android, Platform: CLI, Status: Awaiting Response, Status: Backlog

**Comment by marandaneto** [comment] 2021-11-08 15:02
since the issue is about auto-generated names are not accepted due to not respecting Sentry's versioning, the alternative is using custom release as suggested above.
