### ISSUE TITLE
All transactions are marked as deadline_exceeded

### ISSUE THREAD

**Issue by sregg** [getsentry/sentry-react-native#2467] opened 2022-09-13 19:52 UTC
**OS:**
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.3.0

**`react-native` version:** 0.67.2

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your ~~issue~~ transaction so we can take a look:**

https://sentry.io/organizations/properly-homes/discover/react-native:c1e6e537ae1648f8936ce5729b21ab8e/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=6476453&query=transaction.status%3Adeadline_exceeded&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29

**Configuration:**

(`@sentry/react-native`)
```
const sentryRoutingInstrumentation = new Sentry.ReactNavigationInstrumentation();
Sentry.init({
    dsn: '...'
    environment: 'production',
    integrations: [
      new Sentry.ReactNativeTracing({
        tracingOrigins: [
          /^.*images\.goproperly\.com.*/,
          /^.*\.amazonaws\.com.*/,
          /^.*\.algolia.net.*/,
        ],
        routingInstrumentation: sentryRoutingInstrumentation,
      }),
    ],
    tracesSampleRate: 1,
    // Send analytics to Segment when we get a crash or error
    beforeSend(event) {
      const { level, message, exception } = event;
      let errorMessage = message ?? '';
      if (exception?.values?.length) {
        if (errorMessage.length) {
          errorMessage += ' ';
        }
        errorMessage += exception.values.map((v) => v.value).join(' ');
      }
      if (level === 'fatal' || level === 'error') {
        segmentClient.track('Application Crashed', {
          message: errorMessage,
          level,
        });
      }
      return event;
    },
  });
```

---
**I have following issue:**

All the transactions reported by react-native Sentry SDK v4.3.0 are marked as `deadline_exceeded`.
I've tried setting `ReactNavigationInstrumentation.routeChangeTimeoutMs` or `ReactNativeTracing.idleTimeout` to 10,000ms but nothing changed.

### !transaction.status:deadline_exceeded 

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1479283/189995376-6e83914f-51e8-4b11-adc7-150e26004355.png">

### transaction.status:deadline_exceeded 

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/1479283/189995480-fac9b204-9a91-47e6-b805-2c87d1202a18.png">

### example of a transaction

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1479283/189995500-3dda8735-1616-4026-938e-bd598f9ebd92.png">

**Comment by marandaneto** [comment] 2022-09-14 07:21
@sregg seems like a dupe of https://github.com/getsentry/sentry-react-native/pull/2427
See https://github.com/getsentry/sentry-react-native/issues/2426#issuecomment-1219311150
Can you confirm?

**Comment by sregg** [comment] 2022-09-14 11:48
> @sregg seems like a dupe of #2427 See [#2426 (comment)](https://github.com/getsentry/sentry-react-native/issues/2426#issuecomment-1219311150) Can you confirm?

I'm not setting any option and left them to their default.
By default, `maxTransactionDuration` is 600,000ms and `idleTimeout` is 1000ms.

**Comment by marandaneto** [comment] 2022-09-14 12:20
@sregg as a workaround, for now, you can set manually 600 * 1000 till we get it fixed.

**Comment by sregg** [comment] 2022-09-14 13:34
> @sregg as a workaround, for now, you can set manually 600 * 1000 till we get it fixed.

Setting `maxTransactionDuration: 600 * 1000` gives me the status `unknown`.
I'm not sure if that's intended.

See transaction [here](https://sentry.io/organizations/properly-homes/discover/react-native:a310d6d814084405ac431e286fd0e937/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=6476453&query=&sort=-timestamp&statsPeriod=24h&yAxis=count%28%29).

<img width="930" alt="image" src="https://user-images.githubusercontent.com/1479283/190168318-5b9af453-3239-4b94-8058-2a24efa00b8b.png">

**Comment by krystofwoldrich** [comment] 2022-09-14 14:30
> 

We currently don't set any status in RN, so `unknown` is expected. I don't know, if it would make sense to `setStatus` in the RN integration? @marandaneto

**Closed** 2022-09-15 08:17 UTC
Labels: Platform: React-Native
