### ISSUE TITLE
iOS Use of undeclared identifier

### ISSUE THREAD

**Issue by ajouve** [getsentry/sentry-react-native#3863] opened 2024-06-05 18:17 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.23.0

**`react-native` version:** 0.73.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

When I am trying to run or archive on xcode I have the following errors

```
- node_modules/@sentry/react-native/ios/RNSentry.mm:565:27 Use of undeclared identifier 'kSentryLevelFatal'
- node_modules/@sentry/react-native/ios/RNSentry.mm:567:27 Use of undeclared identifier 'kSentryLevelWarning'
- node_modules/@sentry/react-native/ios/RNSentry.mm:569:27 Use of undeclared identifier 'kSentryLevelError'
- node_modules/@sentry/react-native/ios/RNSentry.mm:571:27 Use of undeclared identifier 'kSentryLevelDebug'
- node_modules/@sentry/react-native/ios/RNSentry.mm:573:27 Use of undeclared identifier 'kSentryLevelInfo'; did you mean 'sentryLevel'?
```

I tried to remove node_modules, package-lock.json, ios/Pods, ios/Podfile.lock, then reinstall, install pods and clear cache on xcode and I still have the same issue

I also tried with module version 5.22.0, 5.22.1, 5.22.2 and 5.22.3 and I have the same issue

**Steps to reproduce:**
- Step 1: npx @sentry/wizard -s -i reactNative
- Step 2: install pods
- Step 3: Build or archive

**Actual result:**

Errors

**Expected result:**

Should build

**Comment by MartinGambit** [comment] 2024-06-05 18:23
Same issue when building my project after updating rn sentry to the latest version >>:

› Compiling @sentry/react-native Pods/RNSentry » RNSentry.mm

❌  (node_modules/@sentry/react-native/ios/RNSentry.mm:565:27)

  563 |         SentryLevel sentryLevel;
  564 |         if ([levelString isEqualToString:@"fatal"]) {
> 565 |             sentryLevel = kSentryLevelFatal;
      |                           ^ use of undeclared identifier 'kSentryLevelFatal'
  566 |         } else if ([levelString isEqualToString:@"warning"]) {
  567 |             sentryLevel = kSentryLevelWarning;
  568 |         } else if ([levelString isEqualToString:@"error"]) {


❌  (node_modules/@sentry/react-native/ios/RNSentry.mm:567:27)

  565 |             sentryLevel = kSentryLevelFatal;
  566 |         } else if ([levelString isEqualToString:@"warning"]) {
> 567 |             sentryLevel = kSentryLevelWarning;
      |                           ^ use of undeclared identifier 'kSentryLevelWarning'
  568 |         } else if ([levelString isEqualToString:@"error"]) {
  569 |             sentryLevel = kSentryLevelError;
  570 |         } else if ([levelString isEqualToString:@"debug"]) {


❌  (node_modules/@sentry/react-native/ios/RNSentry.mm:569:27)

  567 |             sentryLevel = kSentryLevelWarning;
  568 |         } else if ([levelString isEqualToString:@"error"]) {
> 569 |             sentryLevel = kSentryLevelError;
      |                           ^ use of undeclared identifier 'kSentryLevelError'
  570 |         } else if ([levelString isEqualToString:@"debug"]) {
  571 |             sentryLevel = kSentryLevelDebug;
  572 |         } else {


❌  (node_modules/@sentry/react-native/ios/RNSentry.mm:571:27)

  569 |             sentryLevel = kSentryLevelError;
  570 |         } else if ([levelString isEqualToString:@"debug"]) {
> 571 |             sentryLevel = kSentryLevelDebug;
      |                           ^ use of undeclared identifier 'kSentryLevelDebug'
  572 |         } else {
  573 |             sentryLevel = kSentryLevelInfo;
  574 |         }


❌  (node_modules/@sentry/react-native/ios/RNSentry.mm:573:27)

  571 |             sentryLevel = kSentryLevelDebug;
  572 |         } else {
> 573 |             sentryLevel = kSentryLevelInfo;
      |                           ^ use of undeclared identifier 'kSentryLevelInfo'; did you mean 'sentryLevel'?
  574 |         }
  575 |         [breadcrumbInstance setLevel:sentryLevel];
  576 |

**Comment by w1ll-dev** [comment] 2024-06-05 18:56
Same here.

**Comment by charlesfsl** [comment] 2024-06-05 20:04
This is happening for me after merging two branches, one of which had Sentry in it. I have made sure the Sentry pod was updated, wiped out `node_modules` and re-ran `yarn install`, re-ran the Sentry NPM install wizard, but the issue persists. It looks like there have been no changes to those identifiers in `ios/RNSentry.mm` since at least 5.19.0.

**Comment by ashadnasim52** [comment] 2024-06-05 20:17
Same issue

**Comment by manfredxu99** [comment] 2024-06-06 01:07
Same issue!

**Comment by ashadnasim52** [comment] 2024-06-06 01:19
Is there any solution tried other version also, but same error 😔

**Comment by LuckyMadu** [comment] 2024-06-06 05:14
Same issue. Do you have any update on this, please?

```
"react-native": "0.72.0",
"@sentry/react-native": "^5.23.0",
```

**Comment by lozyloop12** [comment] 2024-06-06 05:39
Pls update version follow here,it will be fixed: 
` "@sentry/react-native": "5.20.0"`

**Comment by LuckyMadu** [comment] 2024-06-06 06:00
@lozyloop12 Earlier, I tried with `5.20.0` and I had the caret symbol there. Thank you, mate.

**Comment by EricNetsch** [comment] 2024-06-06 07:02
Same issue

**Comment by astikatika** [comment] 2024-06-06 07:03
same issue :"

**Comment by rodrigodiasf1984** [comment] 2024-06-06 07:04
Same issue 
![image](https://github.com/getsentry/sentry-react-native/assets/30758309/40f99ba9-d977-46d3-bcd3-32cae4ea3112)

**Comment by LuckyMadu** [comment] 2024-06-06 07:05
@EricNetsch Try with `"@sentry/react-native": "5.20.0"`. It worked for me.

**Comment by EricNetsch** [comment] 2024-06-06 07:09
Thanks,
I backdated to  `"@sentry/react-native": "5.20.0"` and it looks like its working again for me 

```
yarn install
pod update
```

**Comment by Binishatk** [comment] 2024-06-06 09:21
Same issue 
updating "@sentry/react-native": "5.20.0". is not worked
pod install showing RNSentry version 5.23.0

**Comment by astikatika** [comment] 2024-06-06 09:32
@Binishatk try to delete Podfile.lock file then run pod install

**Comment by camilossantos2809** [comment] 2024-06-06 10:57
`"@sentry/react-native": "5.22.3",` worked for me.

**Comment by charlesfsl** [comment] 2024-06-06 14:10
Confirmed that it's now working for me with `5.22.3`. At the start of this, when this issue first started for me, I was on `5.22.2`. I tried updating to `5.23.0` as a first step to try and fix it. Looks like the OP had this issue on "5.22.0, 5.22.1, 5.22.2 and 5.22.3".

**Comment by slauzinho** [comment] 2024-06-06 15:54
Having the same issue using `5.23.0`:
![CleanShot 2024-06-06 at 16 53 08@2x](https://github.com/getsentry/sentry-react-native/assets/445345/cd6b13a4-f7d9-46ed-9961-de449f80458d)

Removed the `node_modules`, `Pods` and `Podfile.lock`

did `pod install --repo-update`

**Comment by uzegonemad** [comment] 2024-06-06 17:05
At first glance, it looks like this may be the culprit: https://github.com/getsentry/sentry-cocoa/pull/3963

**Comment by w1ll-dev** [comment] 2024-06-06 17:09
5.20.0 worked for me after clean yarn cache.

1 - delete yarn.lock
2 - delete podfile.lock
3 - `yarn cache clean`
4 - `pod install`

**Comment by lazaro-contato** [comment] 2024-06-06 20:55
updates?

**Comment by attarchi** [comment] 2024-06-06 22:46
`@sentry/react-native@5.22.3` is okay

**Comment by Binishatk** [comment] 2024-06-07 01:11
> @Binishatk try to delete Podfile.lock file then run pod install

Already tried, does not work

**Comment by Binishatk** [comment] 2024-06-07 01:45
> 5.22.3

Its work for me

**Comment by Binishatk** [comment] 2024-06-07 01:46
> "@sentry/react-native": "5.22.3",

Work for me

**Comment by krystofwoldrich** [comment] 2024-06-07 10:32
Hello everyone,
this bug was introduced in https://github.com/getsentry/sentry-react-native/releases/tag/5.23.0.

Please use https://github.com/getsentry/sentry-react-native/releases/tag/5.22.3 on iOS until the fix is released.

The bug was fixed in https://github.com/getsentry/sentry-react-native/pull/3854 and will be released shortly.

**Comment by krystofwoldrich** [comment] 2024-06-07 12:04
https://github.com/getsentry/sentry-react-native/releases/tag/5.23.1 was released

**Closed by krystofwoldrich** 2024-06-07 12:04 UTC
Labels: Platform: React-Native
