### ISSUE TITLE
Mismatched number of arguments for setUser

### ISSUE THREAD

**Issue by srishanbhattarai** [getsentry/sentry-react-native#990] opened 2020-07-23 03:33 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** ^1.6.1

**`react-native` version:** ^0.60.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

Not relevant

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have following issue:**

I upgraded from `react-native-sentry` very recently and my app crashed due to `setUser` being called with the incorrect number of parameters. My app crashed at runtime saying that `setUser` expected to be called with two arguments not one.

My initial impression was that the [JS docs](https://docs.sentry.io/platforms/javascript/#capturing-the-user) did not match the [Android](https://github.com/getsentry/sentry-react-native/blob/13ff133bc2b22f481152cf4e3a685e84ac29d9f8/android/src/main/java/io/sentry/RNSentryModule.java#L224) and [iOS](https://github.com/getsentry/sentry-react-native/blob/13ff133bc2b22f481152cf4e3a685e84ac29d9f8/ios/RNSentry.m#L147-L148) method type signatures. 

I did the following to "fix" it on my end:
```diff
-     Sentry.setUser({ id: phoneNumber })
+     Sentry.setUser({ id: phoneNumber }, {})
```

Upon closer inspection, the `setUser` [method](https://github.com/getsentry/sentry-react-native/blob/13ff133bc2b22f481152cf4e3a685e84ac29d9f8/src/js/wrapper.ts#L171-L182) seems to do this under the hood already so I didn't dive any deeper into the issue at that point.

**Steps to reproduce:**
Call `Sentry.setUser` with only a single argument.

**Actual result:**

Exception about mismatched number of arguments at runtime.
```
07-22 15:45:06.165 15701 16304 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
07-22 15:45:06.165 15701 16304 E AndroidRuntime: Process: <redacted>, PID: 15701
07-22 15:45:06.165 15701 16304 E AndroidRuntime: com.facebook.react.bridge.NativeArgumentsParseException: RNSentry.setUser got 1 arguments, expected 2
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:353)
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:789)
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:98)
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
07-22 15:45:06.165 15701 16304 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:764)
```

**Expected result:**
Expected code to not crash.

**Comment by jennmueng** [comment] 2020-07-23 09:03
Hmm this is unusual to say the least. As in your example you only use the `id` field, it should automatically pass an empty object as the second argument to the native Android code.

I've tried it with your example and couldn't reproduce the issue. Also, `Sentry.setUser` doesn't even take a second argument so the fix you used by passing a second argument to the method shouldn't have any effect.

**Comment by srishanbhattarai** [comment] 2020-07-23 20:46
@jennmueng Yes, unusual indeed and agree with you that my change wasn't really a fix there.

The RN bridge still threw that error so possibly something fishy somewhere. I will try with a re-install when I get the chance.

**Comment by jennmueng** [comment] 2020-07-29 09:33
Hey @srishanbhattarai just to follow up, is the issue still there? Thanks.

**Comment by srishanbhattarai** [comment] 2020-07-30 21:05
Sorry, no - I could not replicate.

**Comment by jennmueng** [comment] 2020-07-31 10:25
Ok thanks! I'll close this.

**Closed by jennmueng** 2020-07-31 10:25 UTC
Labels: android
