### ISSUE TITLE
Exception `-[SentryOptions removeEnabledIntegrations:] unrecognized selector sent to instance 0x600001689700' was thrown while invoking initNativeSdk on target RNSentry with params

### ISSUE THREAD

**Issue by 3KINGZ** [getsentry/sentry-react-native#3079] opened 2023-05-18 12:02 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.3.0

**`react-native` version:** 0.64.0

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: SENTRY_DSN,
  environment: __DEV__
    ? 'development'
    : bundleId?.includes('qa')
    ? 'QA'
    : 'production',
  debug: false,
  enableAutoSessionTracking: true,
  enableInExpoDevelopment: true
});
```

or

(`react-native-sentry`)
```
Sentry.config(
  'https://...@sentry.io/...'
  // other options
 ).install();
```

---
**I have following issue:**
after installing [this package](https://www.npmjs.com/package/react-native-metamap-sdk) i started getting this error on startup

Exception `-{SentryOptions removeEnabledIntegrations:] unrecognized selector sent to instance 0x600001689700' was thrown while invoking initNativeSdk on target RNSentry with params

**Steps to reproduce:**
- install react-native-meta-map-sdk 
- run build

**Actual result:**

<img width="360" alt="Screenshot 2023-05-12 at 12 09 28" src="https://github.com/getsentry/sentry-react-native/assets/36764715/653fe4f4-bc79-4e30-ba5d-c60e0e004e5e">

**Expected result:**

**Comment by 3KINGZ** [comment] 2023-05-18 12:24
@krystofwoldrich please help

**Comment by krystofwoldrich** [comment] 2023-05-19 08:18
Hi, 
thank you for the info, I managed to reproduce it with the latest `@sentry/react-native` SDK, 

we will need to investigate where the error is and if our SDK or the other package needs to be patched to fix this.

**Comment by krystofwoldrich** [comment] 2023-05-19 08:46
It looks like the Meta Map iOS SDK uses Sentry and that is causing the App to crash.

https://github.com/GetMetaMap/metamap-ios-sdk/blob/0412c724dd793b4c1b2051ee1e7956659416b0bf/MetaMapSDK.xcframework/ios-arm64/MetaMapSDK.framework/PrivateHeaders/Sentry.h

**Comment by krystofwoldrich** [comment] 2023-05-19 09:51
Hi, I've created an issue in the Meta Map repository you can follow it there.

- https://github.com/GetMetaMap/metamap-ios-sdk/issues/41

I'm closing this as the error is not caused by `sentry-react-native`

**Closed by krystofwoldrich** 2023-05-19 09:51 UTC
Labels: Platform: React-Native

**Comment by 3KINGZ** [comment] 2023-05-19 10:44
@krystofwoldrich i managed to get rid of the error by disabling `autoInitializeNativeSdk`, i just don't know if that's advisable
