### ISSUE TITLE
Replays not masking text correctly

### ISSUE THREAD

**Issue by JoarTaylor** [getsentry/sentry-react-native#3978] opened 2024-07-30 09:44 UTC
**OS:**
- [ ]  Windows
- [* ]  MacOS
- [ ]  Linux

**Platform:**
- [ *]  iOS
- [ ]  Android

**SDK:**
- [ *]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.26.0

**`react-native` version:** 0.74.2

**Are you using Expo?**
- [* ]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [ *]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
 ...,
_experiments: {
        replaysOnErrorSampleRate: 1.0,
        replaysSessionSampleRate: 1.0,
      },
 integrations: [
        Sentry.mobileReplayIntegration({
          maskAllImages: true,
          maskAllText: true,
        }),
]
});
```

---
**I have the following issue:**

Texts are not completely masked. Lines are missing here and there. Also, if there is a modal thats partially covering the screen, the content behind instantly gets unmasked when the modal is opened. 

**Steps to reproduce:**
- Try with text behind modal

**Actual result:**

Texts har not masked behind modal and only partially on some places troughout the app

**Expected result:**

To it to be completely masked, since we cant use this feature yet because of sensitive user information

**Comment by krystofwoldrich** [comment] 2024-07-31 13:20
Hi @JoarTaylor,
thank you for trying out the SR Public Beta, we appreciate the feedback.

We are currently tracking two issues related to what you are experiencing.

- https://github.com/getsentry/sentry-cocoa/issues/4154
- https://github.com/getsentry/sentry-cocoa/issues/4142

We will fix this shorly. Please follow the linked issues for more details. 

I will close this as duplicate of the mentioned.

**Closed by krystofwoldrich** 2024-07-31 13:20 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
