### ISSUE TITLE
Sentry CLI in Xcode build phase fails on spread operator

### ISSUE THREAD

**Issue by mashaalmemon** [getsentry/sentry-react-native#3300] opened 2023-09-21 19:16 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.9.2

**`react-native` version:** 0.66.4

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

No link yet. Problem getting manual setup for iOS.

**Configuration:**

(`@sentry/react-native`)
```typescript
Sentry.init({
  dsn: Config.SentryDsn,
      tracesSampleRate: Config.SentryTracesSampleRate,
      environment: Config.AppEnv,
      integrations: [
        new Sentry.ReactNativeTracing({
          routingInstrumentation: routingInstrumentation
        })
      ],
      normalizeDepth: 5
});
```

---
**I have following issue:**

The `sentry-wizard` did not work for me. As such I had to follow the [manual configuration](https://docs.sentry.io/platforms/react-native/manual-setup/manual-setup/?original_referrer=https%3A%2F%2Fwww.google.com%2F) steps in the documentation. When modifying the `Bundle React Native Code and Images` React Native build phase script in `Xcode` I started with this prior to attempting to install Sentry:

```shell
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```

And now I have this:

```shell
export NODE_BINARY=node
export SENTRY_PROPERTIES=sentry.properties
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
set -e

# RN 0.46 – 0.68
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode \
  ../node_modules/react-native/scripts/react-native-xcode.sh

# All versions
/bin/sh ../node_modules/@sentry/react-native/scripts/collect-modules.sh
```

When the `sentry-cli` runs as part of this script, it seems to fail with this error: 

```shell
<directory>/Development/moio_pr11/typescript/core/frontend_user_mobile/node_modules/@sentry/cli/js/index.js:38
    this.releases = new Releases({ ...this.options, configFile });
                                   ^^^
SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:511:25)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (<directory>/Development/moio_pr11/typescript/core/frontend_user_mobile/node_modules/@sentry/cli/bin/sentry-cli:6:19)
    at Module._compile (module.js:541:32)
Command PhaseScriptExecution failed with a nonzero exit code
```

I have a `sentry.properties` file in the `<project>/ios` directory as I should, which has the following in it:

```shell
defaults.url=https://sentry.io/
defaults.org=<organization slug>
defaults.project=<project name>
auth.token=<auth token>
#cli.executable=../../../node_modules/sentry-cli-binary/bin/sentry-cli
```

Also note that my project is a Typescript project (and so my entry file is called `index.ts` vs `index.js`). I'm wondering if this is causing a problem in terms ofbecause when I compile my project in my environment, the `ENTRY_FILE` environment variable is set to `index.ts`. 

**Steps to reproduce:**

Simply changing above script to user `sentry-cli` as mentioned above. 

**Actual result:**

Error as mentioned above.

**Expected result:**

Expected to compile.

**Comment by mashaalmemon** [comment] 2023-09-25 14:19
@krystofwoldrich Let me know if you need any other details. For now we're deploying our project without debug symbols/source map for iOS only. Our Android setup seems to work without issue.

**Comment by krystofwoldrich** [comment] 2023-09-26 09:28
@mashaalmemon Hi, thank you for the message, and excuse the late response.

The script you shared is correct. Based on the error it looks like that the Sentry CLI was executed with node version that doesn't support the spread operator.

You can add `node -v` to the build phase to check the node version used.

**Comment by krystofwoldrich** [comment] 2023-10-06 10:43
Closing this as the error is caused by an outdated `node` version. 

If this is still an issue feel free to comment here or open a new issue if the context changed.

**Closed by krystofwoldrich** 2023-10-06 10:43 UTC
Labels: Platform: React-Native

**Comment by mashaalmemon** [comment] 2023-10-07 12:11
Hey @krystofwoldrich, thanks for responding. After a bit of time waiting for a response we switched gears in order to get our release out and I missed your eventual message. Apologies for not responding sooner. The problem still isn't solved for us.

We're using `nvm` and are specifically use `Node v16.15.1`. From what I can tell, the spread operator was introduced fully in `Node v8.x.x`. 

I haven't had a chance to add `-v` to the build phase command. Would I modify `NODE_BINARY="node -v"` to see the version using, when the build phase is run? Any guidance on this would be appreciated.

**Comment by krystofwoldrich** [comment] 2023-10-11 07:25
@mashaalmemon You should call `node -v` on it's own in the build phase. 

To set the NVM version you can call `which node` in your terminal and then copy the path to `NODE_BINARY="/path/to/nvm/node"`.
