### ISSUE TITLE
Error on bundling with the latest release

### ISSUE THREAD

**Issue by chgsilva** [getsentry/sentry-react-native#807] opened 2020-03-26 12:51 UTC
OS:
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

Platform:
- [x]  iOS
- [ ]  Android

SDK:
- [ ]  `@sentry/react-native`
- [x]  `react-native-sentry`

SDK version: 0.0.0
`react-native` version: 0.0.0

Are you using Expo?
- [ ]  Yes
- [ x]  No

Description goes here ...

**Steps to reproduce:**
- Step
Install the latest release

**Actual result:**
- Actual
When loading the bundle this error appears on the metro bundle:
```
error: bundling failed: Error: Unable to resolve module `domain` from `node_modules/@sentry/hub/dist/hub.js`: domain could not be found within the project.
```
**Expected result:**
- Result
bundle is loaded

**Comment by grobmeier** [comment] 2020-03-26 14:31
Have the same issue with:
`"@sentry/react-native": "^1.3.4",`

Message:
`Error: Unable to resolve module `domain` from `node_modules/@sentry/hub/dist/hub.js`: domain could not be found within the project.`

My command to reproduce this:

`react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'`

**Comment by HazAT** [comment] 2020-03-26 14:32
We are on it

**Comment by HazAT** [comment] 2020-03-26 15:05
FYI this broke
https://github.com/getsentry/sentry-javascript/pull/2515

**Comment by HazAT** [comment] 2020-03-26 15:52
Potential fix, we need to validate it with webpack but it works for react-native
https://github.com/getsentry/sentry-javascript/pull/2521

Sorry about this issue https://github.com/getsentry/sentry-javascript/pull/2515#issuecomment-604314979
> JS tooling is hard

**Comment by wmarsey** [comment] 2020-03-26 16:11
thanks for this quick work!

it looks like we can't downgrade out of the problem... I've been doing fresh installs etc and `@sentry/react-native@1.3.2` and `1.3.3` are both now resolving to `@sentry/browser@1.15.1` with yarn, so I still can't build -- does that sound right?

**Comment by chgsilva** [comment] 2020-03-26 16:24
For anyone needing a workaround, I did a fork and locked the version.
The branch fix131 has the temporary solution.
https://github.com/PasseiDireto/sentry-react-native/tree/fix131

Thanks

**Comment by HazAT** [comment] 2020-03-26 16:25
Sounds about right, we will do a new release today for sure

**Comment by HazAT** [comment] 2020-03-26 17:03
New version of `@sentry/*` is released, a clean install should install `5.15.2` with the fix
I will release a new `@sentry/react-native` version as well with the bump.

Again, sorry for the inconvenience.

**Closed by HazAT** 2020-03-26 17:03 UTC

**Comment by HazAT** [comment] 2020-03-26 17:16
`1.3.5` has been released

**Comment by aknyazyan** [comment] 2020-03-27 08:12
Hi guys,

I still have the same issue, even with 1.3.5 version.
Could you please check again?

**Comment by HazAT** [comment] 2020-03-27 08:15
@aknyazyan Please clean your node modules and lock file and make sure you get the `@sentry/*` dependencies above `5.15.2`

**Comment by aknyazyan** [comment] 2020-03-27 08:48
Removed node_modules, package-json.lock, installed 1.3.5 version. @sentry/* dependencies version is  5.15.2. Error exists (
