### ISSUE TITLE
<html> <head><title>502 Bad Gateway</title>

### ISSUE THREAD

**Issue by voortexx** [getsentry/sentry-react-native#3280] opened 2023-09-12 15:45 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.8.0

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]: https://sport-heroes-3v.sentry.io/issues/1413805626/?project=1470758&query=is%3Aunresolved&referrer=issue-stream&stream_index=3

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
      dsn: getSentryApiKey(),
      environment: getBuildType(),
      dist: DeviceInfo.getBuildNumber(),
      release: `${getPlatform()}@${olyappversion}`,
      integrations: (defaults) => {
        return [
          ...defaults.filter((integration) => integration.name !== 'Release'),
          new Sentry.ReactNativeTracing({
            tracingOrigins: [/^\//, /^https:\/\//],
            routingInstrumentation,
            enableNativeFramesTracking: true,
            enableStallTracking: true,
            enableAppStartTracking: true,
          }),
        ];
      },
      ignoreErrors: [...ERRORS_VALUE_BLACKLIST],
      beforeSend: (event, hint) => {
        // Filter out failed API calls (only handle Error or message objects)
        if (typeof hint.originalException === 'string' || hint.originalException instanceof Error) {
          return event;
        }
        return null;
      },
      tracesSampleRate: 0.01,
      enableAutoSessionTracking: true,
      normalizeDepth: 5,
    });
```

---

We have a lot of events for API call failing, but it seems that all this call are wrapped by try/catch with no capture.
We don't know why this 502 error are sent to Sentry, and from where ? Maybe Axios.
Is it possible to avoid them ?

<img width="862" alt="Capture d’écran 2023-09-12 à 17 44 03" src="https://github.com/getsentry/sentry-react-native/assets/39954641/7283a76c-5920-4276-96e7-95f23fb3dd96">

**Comment by krystofwoldrich** [comment] 2023-09-13 09:15
Hi, thank you for the message,
you can filter these errors by regex in `ignoreErrors` option.

To discover where are the errors from, we need more information. 

Is there a stack trace in the issue detail, could you share it with us?

**Comment by krystofwoldrich** [comment] 2023-09-15 11:47
> We'd have liked to avoid using ignoreErrors

Do you have any concerns about using ignoreErrors?

> The call in 502 is in a try/catch in our code.

Could you share a code snippet? I'm not sure if I understand, you try/catch this error, but you don't call `Sentry.captureException()`? Or you do?

**Comment by voortexx** [comment] 2023-09-15 12:59
We already use ignoreErrors for certain errors. But the specs I had told me to try not to use it for this cas, but rather to understand where these errors come from.

For example I have something like this

````
  const joinTribe = async () => {
    try {
      setIsJoinButtonLoading(true);
      await joinResourceGroup({ resourceId: tribeId, resourceType: 'tribe', source: 'tribe page' });
      displaySnackBar('success', t('ds-tribes.tribe.join.success'));
    } catch (e) {
      displaySnackBar('error', t('global.error'));
      setIsJoinButtonLoading(false);
    }
  }
````
So I thought that in this case no errors would be sent to Sentry.

**Comment by voortexx** [comment] 2023-09-19 07:49
Unfortunately it's going to be difficult. We have a multi-repo system in our company and that would require a lot of work.
I'll try to use axios interceptors.

**Comment by krystofwoldrich** [comment] 2023-09-22 15:24
@voortexx Let us know if you find out something more.

We will close this since we are not able to reproduce the error. In case anyone else has the same problem or there is any update please leave a comment here so we can reopen the issue and investigate again.

**Closed by krystofwoldrich** 2023-09-22 15:24 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
