### ISSUE TITLE
getDefaultConfig from expo/metro-config compromise the sourceMappingURL and it has a wrong hash when exported for web platform 

### ISSUE THREAD

**Issue by claudioviola** [getsentry/sentry-react-native#3663] opened 2024-03-06 14:18 UTC
**OS:**
- [ ]  Windows
- [ X]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [ ]  Android

```
"@sentry/react-native": "^5.17.0",
"expo": "^50.0.3",
"react-native": "0.73.2",
"react-native-web": "~0.19.6",
"@expo/metro-runtime": "~3.1.2",
"react": "18.2.0",
"react-dom": "18.2.0",
```

**Are you using Expo?**
- [X ]  Yes
- [ ]  No

This is the configuration of my metro.config.js placed in the root folder project

```
// This replaces `const { getDefaultConfig } = require('expo/metro-config');`
const { getSentryExpoConfig } = require('@sentry/react-native/metro');

// This replaces `const config = getDefaultConfig(__dirname);`
const config = getSentryExpoConfig(__dirname);

module.exports = config;
```

**I have the following issue:**

**Steps to reproduce:**
- Build the web project by running this command  npx expo export -p web --dump-sourcemap
- check the dist folder

2 files are created
AppEntry-9c58c4463ca3cfc79b6525f9cc37e942.js
AppEntry-9c58c4463ca3cfc79b6525f9cc37e942.js.map

**Actual result:**
Opening the first file for checking if the sourceMappingURL is correct
Actually the sourceMappingURL is wrong and it contains a different hash for the Javascript bundled file
`//# sourceMappingURL=/_expo/static/js/web/AppEntry-c20e66115809b9d51b0088b809c85f32.js.map`

**Expected result:**

Opening the first file for checking if the sourceMappingURL is correct
the sourceMappingURL should contains the correct hash and it should points to the correct file
`//# sourceMappingURL=/_expo/static/js/web/AppEntry-9c58c4463ca3cfc79b6525f9cc37e942.js.map`

if using in the metro.config.js
`const { getDefaultConfig } = require('expo/metro-config');`
the issue disappears and the sourceMappingURL contains the correct file

**Comment by krystofwoldrich** [comment] 2024-03-07 13:46
Hi @claudioviola,
thank you for the message,
I was able to reproduce it in our sample app, we will investigate it.

**Comment by Fwang36** [comment] 2024-03-28 18:26
Hey Krystof,

Support received a request in Zendesk from a user with the same issue.  Do you have an update for this problem?  

[Link to Zendesk ticket](https://sentry.zendesk.com/agent/tickets/117304)

**Comment by amir-dropit** [comment] 2024-05-01 11:22
@krystofwoldrich is it resolved in v5.22.0?

**Comment by krystofwoldrich** [comment] 2024-05-02 14:59
@amir-dropit No, 5.22.0 doesn't fix this particular issue.

**Comment by amir-dropit** [comment] 2024-05-22 08:02
How is this not fixed yet?

**Comment by YishaiGr** [comment] 2024-05-22 10:24
@krystofwoldrich can you please update on the manner? our source maps were no uploaded for 3 weeks because of this bug

**Comment by krystofwoldrich** [comment] 2024-05-22 16:30
Hi, I'm sorry to hear that, I've opened a PR fixing this today.

- https://github.com/expo/expo/pull/29054

I'll also post here a workaround which you can use until the fix is released.

**Comment by YishaiGr** [comment] 2024-05-22 17:46
Thanks a lot! 🙏

**Comment by krystofwoldrich** [comment] 2024-05-24 08:53
Until the fix is released, you can apply the changes from the [fix PR](https://github.com/expo/expo/pull/29054/files#diff-e51e0a447b1c87524c067bc171823cb544895a690991f436ea3fa1fc96351d38) using https://www.npmjs.com/package/patch-package

**Comment by ricklove** [comment] 2024-11-27 05:17
This breaks dynamic modules with React.lazy

**Comment by krystofwoldrich** [comment] 2024-11-28 13:38
This was fixed in https://github.com/expo/expo/pull/30980

**Closed by krystofwoldrich** 2024-11-28 13:38 UTC
Labels: Type: :beetle: Bug, Platform: React-Native, Waiting for: Product Owner
