### ISSUE TITLE
Problem since artifact bundles introduced

### ISSUE THREAD

**Issue by markholland** [getsentry/sentry-react-native#3058] opened 2023-05-10 10:39 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.3.0

**`react-native` version:** 0.70.9

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

- https://catenda-as.sentry.io/share/issue/79b88509ca9047aa843334447638b7a2/
- https://catenda-as.sentry.io/share/issue/ac24e9b6020648fe919ec2ff402ed4b1/

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  maxValueLength: 1024
});
```

---
**I have following issue:**

When a line of javascript causes an error to be logged to Sentry separate issues are created per platform.

**Steps to reproduce:**
- Log an error to sentry from javascript

**Actual result:**

- One issue on iOS with the correct line of javascript highlighted in the source code.
- One issue on Android with the incorrect line of javascript highlighted in the source code.

**Expected result:**

- One issue with multiple events covering both iOS and Android and the correct line of javascript highlighted in the source code.

**Comment by markholland** [comment] 2023-05-10 10:43
@krystofwoldrich

**Comment by markholland** [comment] 2023-05-10 13:57
Ok, can you confirm then that since Artifact bundling was enabled and despite us not having upgraded this package on our side we now need to set a value for `dist` when targeting more than one platform? Shouldn't this be [documented](https://docs.sentry.io/platforms/react-native/configuration/options/#dist) as a required step?

Detailed instructions for how to correctly set `dist` everywhere that it is needed would be appreciated.

**Comment by markholland** [comment] 2023-05-10 14:10
We are not setting any value for `dist` ourselves. Our build numbers are intentionally aligned across platforms to help with tracking issues.

**Comment by krystofwoldrich** [comment] 2023-05-11 08:11
Im sorry about the link, here is a correct one https://docs.sentry.io/platforms/react-native/sourcemaps/#1-set-the-release-and-distribution

**Comment by markholland** [comment] 2023-05-11 08:53
Thanks for the documentation link.

So to make sure I understand what's needed.

- Generate a distinct value for `dist` per platform (iOS/android/etc)
- Explicitly set it when calling `Sentry.init`.
- Set it to `$SENTRY_DIST` when building each platform.

Would this be enough and does this mean source map uploading would still be automatic?

**Comment by krystofwoldrich** [comment] 2023-05-11 09:03
@markholland Yes, exactly, automatic upload will use the `$SENTRY_DIST`, which needs to match `dist` in `Sentry.init`.

**Comment by krystofwoldrich** [comment] 2023-05-11 11:56
@markholland Yes, I absolutely agree, we will update the docs.

I'll keep this open until I hear from you.

**Comment by krystofwoldrich** [comment] 2023-05-11 12:03
Linking similar issues from discussions:
- https://github.com/getsentry/sentry-react-native/discussions/3060
- https://github.com/getsentry/sentry-react-native/discussions/3019

**Comment by iambriccardo** [comment] 2023-05-11 13:29
Hi @markholland, I have analyzed your situation and might have found the problem. On our side we cache files for symbolication in `url, release, dist` triples that are kept for 1 hour, did you by any chance upload multiple times different bundles with the same `release` and `dist` and that contained the same filenames?

**Comment by markholland** [comment] 2023-05-11 13:55
I am off for the next two weeks but will follow up once I'm back.

**Comment by krystofwoldrich** [comment] 2023-06-02 09:00
@markholland Have you managed to try it again?

**Comment by markholland** [comment] 2023-06-02 09:08
I haven't been able to spend anymore time on this yet as it involves making changes to our build process to set this new `dist` value.

@iambriccardo Through normal usage I don't see how that would happen. We build in CI and the release includes the version number so is unique for each build. The only duplication is from not setting this new `dist` field so we're uploading once per platform with the same release value

**Comment by krystofwoldrich** [comment] 2023-06-02 09:44
@markholland Maybe since this could have been just caching issue, are the Android issue still pointing to the incorrect lines?

**Comment by stachu2k** [comment] 2023-06-06 14:06
Same issue here. Sourcemaps point to incorrect lines on Android, but they are correct on iOS.

**Comment by pawlitos** [comment] 2023-06-07 09:14
@krystofwoldrich Hey. Thank you for your quick response. My setup is:
```
react-native 0.71.8
@sentry/react-native: 5.5.0
SDK: sentry.javascript.react-native 5.5.0
```
I upload sourcemaps automatically. I build iOS app by `XCode -> Archive`. I build Android app by command `./gradlew assembleRelease`.

Here is a screenshot from Sentry with example issue from both iOS and Android.

![sentry](https://github.com/getsentry/sentry-react-native/assets/100161033/39ebf34c-962b-412f-89c4-645ee682bd74)

**Comment by stachu2k** [comment] 2023-06-07 09:16
@krystofwoldrich Hey. Thank you for your quick response. My setup is:
```
react-native 0.71.8
@sentry/react-native: 5.5.0
SDK: sentry.javascript.react-native 5.5.0
```
I upload sourcemaps automatically. I build iOS app by `XCode -> Archive`. I build Android app by command `./gradlew assembleRelease`.

Here is a screenshot from Sentry with example issue from both iOS and Android.

![sentry](https://github.com/getsentry/sentry-react-native/assets/100161033/39ebf34c-962b-412f-89c4-645ee682bd74)

**Comment by krystofwoldrich** [comment] 2023-06-12 12:08
@stachu2k Thank you for the details. I'm sorry for the long response time, I was OoO.

Can you download the uploaded Android source map and run `npx metro-symbolicate downloaded_index.android.bundle.map < stacktrace.txt` to check if the uploaded file is correct?

**Comment by pawlitos** [comment] 2023-06-14 09:52
@krystofwoldrich I downloaded source maps and run the command. But unfortunately the output file stacktrace.txt is empty. The command returned without any error. It's weird.

**Comment by stachu2k** [comment] 2023-06-14 09:53
@krystofwoldrich I downloaded source maps and run the command. But unfortunately the output file stacktrace.txt is empty. The command returned without any error. It's weird.

**Comment by krystofwoldrich** [comment] 2023-06-14 11:44
@stachu2k The `stacktrace.txt` is an input for the `metro-symbolicate`, create the file with the `raw` and `minified` stack trace that you see in Sentry. The output will be visible in the console output.

![Screenshot 2023-06-14 at 13 43 05](https://github.com/getsentry/sentry-react-native/assets/31292499/6fe9d047-51bc-4981-8be2-e3c9d17e7f91)

**Comment by stachu2k** [comment] 2023-06-14 13:00
@krystofwoldrich Now the command worked. It has shown a correct stack trace for my test error. The funny thing is that I had trouble to identyfy the correct artifact associated to 2.13.0 (77) because it turned out to have 22 artifacts instead of 2. So I bumped versionCode to 78 and built a fresh release 2.13.0 (78) with only 2 artifacts uploaded to Sentry. Then I pressed a button to send my test error and not I see that stack trace is correct as seen on the screenshot. So I think the issue is somehow solved. Is it neccesary to have only 2 artifacts per release?
<img width="880" alt="Screenshot 2023-06-14 at 14 47 53" src="https://github.com/getsentry/sentry-react-native/assets/6988196/116569c1-2e15-4ef7-a589-f387c4ba5176">

**Comment by krystofwoldrich** [comment] 2023-06-15 09:15
@stachu2k You can have more than 2 artifacts for one release but it's important to use unique dist values for the different artifacts so we are able to select the correct one for the incoming error.

But seem like that was a mistake anyway, happy to hear it works now.

**Comment by krystofwoldrich** [comment] 2023-06-16 10:12
I'm closing this as from the [latter](https://github.com/getsentry/sentry-react-native/issues/3058#issuecomment-1591164336) comments it seems like the Android source maps are working.

**Closed by krystofwoldrich** 2023-06-16 10:12 UTC
Labels: Type: :beetle: Bug, Status: Awaiting Response, Platform: React-Native

**Comment by markholland** [comment] 2023-07-06 15:09
Hi @krystofwoldrich 

I've finally been able to pick this up again and work on setting `dist` value to be unique per platform. We are following a `platform-buildNumber` format and are setting this value in `Sentry.init` and as environment variables during the native builds.

In Sentry issues the `dist` appears to be correctly set

<img width="132" alt="Screenshot 2023-07-06 at 16 47 01" src="https://github.com/getsentry/sentry-react-native/assets/1764217/da7c332c-33de-423d-8fe4-7daed84e487e">

But when we have a crash we are getting a new error.

<img width="1179" alt="Screenshot 2023-07-06 at 16 47 18" src="https://github.com/getsentry/sentry-react-native/assets/1764217/2ba3b99b-4b5a-40c9-a267-57b024633404">

This is how we are setting dist in Sentry.init

```
import { Platform } from 'react-native';
import { getBuildNumber } from 'react-native-device-info';

Sentry.init({
  dist: `${Platform.OS}-${getBuildNumber()}`,
  dsn: OUR_DSN,
});
````

And this is the output during build for Android as an example

```
Processing react-native sourcemaps for Sentry upload.
> Analyzing 2 sources
> Rewriting sources
> Adding source map references
Uploading sourcemaps for release no.catenda.bimsyncmobile@1.0.0+android-1 distribution android-1
> Bundled 2 files for upload
> Uploaded release files to Sentry
> File upload complete (processing pending on server)
> Organization: catenda-as
> Project: bimsync-mobile
> Release: no.catenda.bimsyncmobile@1.0.0+android-1
> Dist: android-1
> Upload type: artifact bundle
```

No release with value `no.catenda.bimsyncmobile@1.0.0+android-1` has been created in Sentry, only the existing `1.0.0 (1)`

**Comment by krystofwoldrich** [comment] 2023-07-07 08:46
@markholland Hi, thanks for the message.

From the source map upload log, I see you also changed the release name. You can keep the release `no.catenda.bimsyncmobile@1.0.0+1` instead of `no.catenda.bimsyncmobile@1.0.0+android-1` and the dist looks good, keep that `android-1`.

**Comment by markholland** [comment] 2023-07-07 08:56
@krystofwoldrich Thanks for the reply.

I'm not setting the release.

I can see [here](https://github.com/getsentry/sentry-react-native/blob/main/sentry.gradle#L261-L262) that Sentry appends the `SENTRY_DIST` to the release name.

**Comment by krystofwoldrich** [comment] 2023-07-10 08:52
@markholland Thanks, I thought maybe you set the release manually.

So to align the release name you can either use the `SENTRY_RELEASE` env and set it to `no.catenda.bimsyncmobile@1.0.0+1`. Or set `no.catenda.bimsyncmobile@1.0.0+android-1` during the SDK JS init.

**Comment by markholland** [comment] 2023-07-10 08:56
@krystofwoldrich Thanks for the reply.

It probably makes sense to go with the first even though it adds more complexity to our build process as having a release per platform probably isn't the expected way to use Sentry? Especially as doing that would mean there's no need in setting `SENTRY_DIST` as the conflict within a release would no longer exist?

**Comment by markholland** [comment] 2023-07-11 12:33
I'll share below how I've been building the apps as my understanding is this is when `sentry-cli` is executed.

Eventually this would all be in our CI with fastlane setting the environment variables before calling the gradle and xcode build steps.

But as I'm testing all this locally this is how I'm doing it and might highlight why `sentry-cli` isn't getting the correct values.

**Android:** `SENTRY_DIST="android-1" SENTRY_RELEASE="no.catenda.bimsyncmobile@1.0.0+2203" yarn android --variant=release`

**iOS:** I am setting environment variables in Xcode and building with release configuration.
<img width="957" alt="Screenshot 2023-07-11 at 14 32 18" src="https://github.com/getsentry/sentry-react-native/assets/1764217/62a3b77d-de57-4da6-9008-3f2877e3d438">

Thanks for the continued help.

**Comment by markholland** [comment] 2023-07-11 16:50
I have made some progress focusing on using our Fastlane setup in CI.
I will follow up with more detail.

**Comment by markholland** [comment] 2023-07-12 12:44
Here is the follow up and conclusion now that this appears to be working for us.

If you are using React Native and intend to target more than one platform it probably makes sense to use custom `release` and `dist` values from the beginning to avoid any weirdness should the default `release` and `dist` values ever coincide across platforms.

We accomplished this by:

- Calculating dist and release in our js code when we call Sentry.init
```
import * as Sentry from '@sentry/react-native';
import { Platform } from 'react-native';
import { getBuildNumber, getBundleId, getVersion } from 'react-native-device-info';

const buildNumber = getBuildNumber();
const bundleId = getBundleId();
const platform = Platform.OS;
const version = getVersion();
const dist = `${platform}-${buildNumber}`;
const release = `${bundleId}@${version}+${buildNumber}`;
Sentry.init({
  dist,
  dsn: YOUR_DSN,
  release,
});
```
- Calculating dist and release in our fastlane build lanes and setting them as environment variables before calling gradle and Xcode build
```
# Android lane
versionCode = google_play_track_version_codes[0]
versionName = load_json(json_path: "package.json")["version"]
ENV["SENTRY_DIST"] = "android-#{versionCode}"
ENV["SENTRY_RELEASE"] = "YOUR_PACKAGE_NAME@#{versionName}+#{versionCode}"
gradle

# iOS lane
buildNumber = latest_testflight_build_number + 1
version = load_json(json_path: "package.json")["version"]
ENV["SENTRY_DIST"] = "ios-#{buildNumber}"
ENV["SENTRY_RELEASE"] = "YOUR_BUNDLE_ID@#{version}+#{buildNumber}"
build_app
```

Things to look out for when troubleshooting.

- Releases seem to reuse old artifacts if the bundle hasn’t changed. This can be confusing as you may expect your latest release to have artifacts but instead it says 0 artifacts. This could be because an existing artifact from another release is the one being used.
- While testing ensure you change the value of dist every time you build otherwise sentry issues might say things like it can’t find the stack trace or no release is associated.


@krystofwoldrich Thanks for all the help with this and happy to have this working as we wanted again.

**Comment by krystofwoldrich** [comment] 2023-07-14 09:03
@markholland Thank you for the summary, I'm happy that it works for you and I'm sorry for the long debugging.

One note 
> iOS: I am setting environment variables in Xcode and building with release configuration.
The Envs defined here are passed to the app process not to the environment during the build. That's why they are not picked up by the `sentry-cli`.
