### ISSUE TITLE
Reported stack trace not readable

### ISSUE THREAD

**Issue by AlexanderEggers** [getsentry/sentry-react-native#3120] opened 2023-06-14 02:47 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.5.0

**`react-native` version:** 0.71.10

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[[Link to issue]](https://zeller.sentry.io/issues/4238099730/events/ece7ce2b4f5145b9a960f5b055d8ecc7/?project=4504794922549248)

**Configuration:**

(`@sentry/react-native`)
```javascript
Sentry.init({
  dsn: env.SENTRY_DNS,
  autoInitializeNativeSdk: false,
  debug: __DEV__,
  environment: env.SENTRY_ENV,
  enabled: !__DEV__ && !env.IS_MOCK,
  tracesSampleRate: 0.5,
  integrations: [
    new Sentry.ReactNativeTracing({
      routingInstrumentation: SENTRY_ROUTING_INTRUMENTATION,
    }),
    new Sentry.BrowserIntegrations.Breadcrumbs({
      console: false,
      fetch: false,
      xhr: false,
    }),
  ],
  attachStacktrace: true,
  attachThreads: true,
});
```

(`Sentry Android`)
```java
    SentryAndroid.init(this, options -> {
        options.setDsn(BuildConfig.SENTRY_DNS);
        options.setDebug(BuildConfig.DEBUG);
        options.setEnvironment(BuildConfig.SENTRY_ENV);
        options.addIntegration(new FragmentLifecycleIntegration(this, false, false));
        options.setEnableActivityLifecycleBreadcrumbs(false);
        options.setBeforeBreadcrumb((breadcrumb, hint) -> {
            if (Objects.equals(breadcrumb.getCategory(), "http")
                    || Objects.equals(breadcrumb.getCategory(), "Logcat")) {
                return null;
            }
            return breadcrumb;
        });
    });
```

(`Sentry iOS`)
```objective-c
[SentrySDK startWithConfigureOptions:^(SentryOptions * options) {
    options.dsn = [RNCConfig envFor:@"SENTRY_DNS"];
    options.environment = [RNCConfig envFor:@"SENTRY_ENV"];
    options.beforeBreadcrumb = ^SentryBreadcrumb * _Nullable(SentryBreadcrumb * _Nonnull breadcrumb) {
      if([breadcrumb.type isEqualToString:@"http"]) {
        return nil;
      }
      return breadcrumb;
    };
    options.enableSwizzling = NO;
  }];
```

---
**I have following issue:**

When producing errors in one of my build, the attached stack trace is not resolved using the available source maps. I don't see any error messages when displaying the linked event, so I am assuming that the source maps were correctly found but cannot be processed for unknown reasons.

**Steps to reproduce:**
I'm uncertain about the steps. I followed the offcial setup guide line by line. I cannot spot any differences between my project and the sample projects.

**Actual result:**

Reported stack trace on sentry.io is not readable.

**Expected result:**

Readable stack trace on sentry.io.

**Comment by krystofwoldrich** [comment] 2023-06-14 10:32
Thank you for the message, 
I will close this as a duplicate of https://github.com/getsentry/sentry-react-native/issues/3097. 

Can you use `captureException` instead of `captureMessage` until we solve the mentioned issue?

**Closed by krystofwoldrich** 2023-06-14 10:32 UTC
Labels: Status: Untriaged, Platform: React-Native, Waiting for: Product Owner

**Comment by AlexanderEggers** [comment] 2023-06-14 10:51
@krystofwoldrich Thanks for the suggestion. I am not certain if that is going to work for me. That case is creating a lot of events with the title `<global>` which doesn't seem correct.

Do you have an ETA on #3097?

**Comment by krystofwoldrich** [comment] 2023-06-14 13:05
ETA for https://github.com/getsentry/sentry-react-native/issues/3097 is upcoming weeks.

Would something like this not work for you?

```js
// Current
Sentry.captureMessage("Your message");

// Replaced
Sentry.captureException(new Error('Your message'));
```

The stack trace of the error you create manually will be the same as the one attached to the message.
