### ISSUE TITLE
Error: Unable to resolve module `promise/setimmediate/rejection-tracking`

### ISSUE THREAD

**Issue by luisfuertes** [getsentry/sentry-react-native#1926] opened 2021-12-03 12:06 UTC
### Environment

How do you use Sentry?
```
"@sentry/react-native": "^3.2.5",
"react": "16.9.0",
"react-native": "0.61.5",
```

Node and npm versions used:
```
node -v 14.18.1
npm -v 6.14.15

and 

node -v v16.10.0
npm -v 7.24.0
```

### Steps to Reproduce

1. `rm -rf node-modules && ./gradlew clean && npm install && uninstall app && npx react-native run-android`
2. App compile but when try to load javascript get this error:
```
error: bundling failed: Error: Unable to resolve module `promise/setimmediate/rejection-tracking` from `node_modules/@sentry/react-native/dist/js/integrations/reactnativeerrorhandlers.js`: promise/setimmediate/rejection-tracking could not be found within the project.
```

I try to add `"preinstall": "npx npm-force-resolutions",` and resolutions on package.json but have same error.
```
  "resolutions": {
    "promise": "^7.1.1"
  }
```

**Comment by LFMAKER** [comment] 2021-12-03 12:27
Yesterday I reported the same problem, they released a 3.2.5 that possibly solved the problem, but it didn't!

If this doesn't work in old versions of the RN they should have alerted the breaking change and not simply released and not commented on it.

**Comment by marandaneto** [comment] 2021-12-03 12:29
looks similar to https://github.com/getsentry/sentry-react-native/issues/1922 but a different promise library

**Comment by LFMAKER** [comment] 2021-12-03 12:34
in IOS:

`Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: Error: Requiring unknown module "react-native/Libraries/promiseRejectionTrackingOptions".', reason: 'Unhandled JS Exception: Error: Requiring unknown module "react-native/Libraries/promiseRejectionTrackingOptions"., stack:`

**Comment by marandaneto** [comment] 2021-12-03 12:35
@jennmueng apparently we've to do the same with those 2 lines.

https://github.com/getsentry/sentry-react-native/blob/master/src/js/integrations/reactnativeerrorhandlers.ts#L71
https://github.com/getsentry/sentry-react-native/blob/master/src/js/integrations/reactnativeerrorhandlers.ts#L123

@LFMAKER your comment in the other issue was before 3.2.5, it's a bug and not a breaking change, we're not aware that it'd not work for an older version.

**Comment by luisfuertes** [comment] 2021-12-03 12:35
@marandaneto i come from that issue.

But i update sentry to new version with fix and have the same problem that with sentry 3.2.3 and 3.2.2

**Comment by marandaneto** [comment] 2021-12-03 12:36
> @marandaneto i come from that issue.
> 
> But i update sentry to new version with fix and have the same problem that with sentry 3.2.3 and 3.2.2

that is likely caching or dirty node modules, that line of code never existed on 3.2.3 so it can't an issue.
you'd need to revert your upgrade.

**Comment by luisfuertes** [comment] 2021-12-03 12:38
But i delete node_modules, use gradlew clean, uninstall app, set version fixed on package.json, etc.

How it can cache module?

**Comment by marandaneto** [comment] 2021-12-03 12:39
> 3.2.3

not sure, but this is not related to this issue or the previous one at all, create an empty project, use Sentry `3.2.3` and you won't experience the same issue.

**Comment by marandaneto** [comment] 2021-12-03 12:40
> But i delete node_modules, use gradlew clean, uninstall app, set version 3.2.3 on package.json, etc.
> 
> How it can cache module?

not sure, but this is not related to this issue or the previous one at all, create an empty project, use Sentry 3.2.3 and you won't experience the same issue.

**Comment by LFMAKER** [comment] 2021-12-03 12:42
> not sure, but this is not related to this issue or the previous one at all, create an empty project, use Sentry 3.2.3 and you won't experience the same issue.


I literally installed everything on another macOs and had the same problem, it's not caching

**Comment by marandaneto** [comment] 2021-12-03 12:44
@LFMAKER can you provide a minimal reproducible example using Sentry 3.2.3?

**Comment by luisfuertes** [comment] 2021-12-03 13:02
I started new project with `npx react-native init AwesomeProject --version 0.61.5` and install `"@sentry/react-native": "3.2.3"` and it works ...

But dont know what can be wrong on my project :s

**Comment by LFMAKER** [comment] 2021-12-03 13:22
I started a new project too and it worked, but in my real project it doesn't work

**Comment by jennmueng** [comment] 2021-12-03 16:07
@LFMAKER @luisfuertes Make sure you [completely reset the React Native build cache.](https://stackoverflow.com/a/51375437/9287775)

This dependency has been present since `@sentry/react-native: 1.0.0` for 2 years, it was not caused by the recent change:
Now: https://github.com/getsentry/sentry-react-native/blob/d2438b6ad45a4ab08a9ca730fb79f93da0a67685/src/js/integrations/reactnativeerrorhandlers.ts#L71
2 years ago: https://github.com/getsentry/sentry-react-native/blob/419cf967a37bb0694523c5c2658afc4ca8995e5a/src/js/integrations/reactnativeerrorhandlers.ts#L47

**Comment by LFMAKER** [comment] 2021-12-03 18:10
@jennmueng 
I've done this several times, I've cloned the project into another Macos too, and I still have this problem. Unfortunately, this only happens when I build the project in release mode.

**Comment by johnsoncwb** [comment] 2021-12-03 18:16
Same issue here guys, always i try to build my project or run it in release mode it crashes. 
Macbook air M1 - BigSur 11.6.1 
"react-native": "0.63.4"
"sentry-expo": "^4.0.3"
"@sentry/react-native": "^3.1.1"

**Comment by jennmueng** [comment] 2021-12-03 19:29
@LFMAKER @johnsoncwb I just tried a release build with `react-native: 0.63.1` and `@sentry/react-native: 3.2.5` and couldn't reproduce this issue. What promise version are you using? Have you tried clearing the build cache for both XCode and Gradle? Can I have a reproducible example?

**Comment by johnsoncwb** [comment] 2021-12-03 21:28
@jennmueng i got `react-native/Libraries/promiseRejectionTrackingOptions` when i try do build the app.
![Screen Shot 2021-12-03 at 18 28 37](https://user-images.githubusercontent.com/80973949/144675118-090128a6-441b-4f86-aae0-8bb3dd2adcd3.png)

**Comment by jennmueng** [comment] 2021-12-03 22:15
@johnsoncwb What version of `"@sentry/react-native": "^3.1.1"` are you actually on, can I get the lockfile entry?

**Comment by LFMAKER** [comment] 2021-12-03 22:19
https://github.com/expo/sentry-expo is what causes the crash and error.

**Comment by LFMAKER** [comment] 2021-12-03 22:33
I set an old version of the sentry dependencies in the lib and it worked.
https://github.com/LFMAKER/sentry-expo

**Comment by LFMAKER** [comment] 2021-12-03 22:34
But now, I would like to know if you support this lib, as it is from the expo.

**Comment by luisfuertes** [comment] 2021-12-09 09:49
I have the problem in debug mode in android. Doing the init and not doing it

**Comment by marandaneto** [comment] 2021-12-09 13:51
thanks, closing it then.
@luisfuertes please upgrade to the latest version and if it still happens, a minimal reproducible example would help.

**Closed by marandaneto** 2021-12-09 13:51 UTC
Labels: Status: Awaiting Response, Effort: Medium, Impact: Large
