### ISSUE TITLE
Multiple commands produce PrivacyInfo.xcprivacy

### ISSUE THREAD

**Issue by chrs1885** [getsentry/sentry-react-native#3599] opened 2024-02-14 16:08 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.19.0

**`react-native` version:** 0.73.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

-

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

Building the iOS app causes the following issue 

Multiple commands produce '/Users/JohnDoe/Library/Developer/Xcode/DerivedData/AwesomeProject-ccrefsqqbzdwoefvcsygajfvyqlw/Build/Products/Debug-iphonesimulator/AwesomeProject.app/PrivacyInfo.xcprivacy'

**Steps to reproduce:**

1. Create React Native project: npx react-native@latest init AwesomeProject
2. Open AwesomeProject.xcworkspace
	- Create Privacy Manifest (New -> File)
	- Set target membership of the Privacy Manifest to AwesomeProject
3. Build the app

**Actual result:**

-

**Expected result:**

Project builds, Privacy Manifest files get merged successfully.

**Comment by krystofwoldrich** [comment] 2024-02-16 13:09
@brustolin The manually create `PrivacyInfo.xcprivacy` clashes with https://github.com/getsentry/sentry-cocoa/pull/3206

Do users have to set up something to merge the files? Or can we detect this automatically?

**Comment by brustolin** [comment] 2024-02-19 07:15
This will be fixed with this [PR](https://github.com/getsentry/sentry-cocoa/pull/3651)

**Comment by fatlinesofcode** [comment] 2024-02-28 03:49
when can we expect this to released for react native? its blocking us including a xcprivacy file in our app

**Comment by kahest** [comment] 2024-02-28 08:49
@fatlinesofcode we will release a stable version of sentry-cocoa in the next few days, then we can bump the dependency and release a RN version with the fix.

I'm reopening this issue to track when the fix landed in RN.

cc @krystofwoldrich @philipphofmann

**Comment by Evan-Fisher** [comment] 2024-03-14 04:15
When would this make it's way into [@sentry/react-native](https://www.npmjs.com/package/@sentry/react-native?activeTab=readme)? Version 5.19.2 seems to still point to 8.20.0.

**Comment by akuznetsov-md** [comment] 2024-03-14 08:30
`@sentry/react-native@5.19.2` with the following patch helped me workaround the issue

```patch
diff --git a/node_modules/@sentry/react-native/RNSentry.podspec b/node_modules/@sentry/react-native/RNSentry.podspec
index f9eafb6..1d0fc2f 100644
--- a/node_modules/@sentry/react-native/RNSentry.podspec
+++ b/node_modules/@sentry/react-native/RNSentry.podspec
@@ -33,7 +33,7 @@ Pod::Spec.new do |s|
   s.preserve_paths = '*.js'
 
   s.dependency 'React-Core'
-  s.dependency 'Sentry/HybridSDK', '8.20.0'
+  s.dependency 'Sentry/HybridSDK', '8.21.0'
 
   s.source_files = 'ios/**/*.{h,mm}'
   s.public_header_files = 'ios/RNSentry.h'

```

**Comment by krystofwoldrich** [comment] 2024-03-14 10:06
`@sentry/react-native@5.19.3` will include the `sentry-cocoa` bump and will be released today.

**Comment by Evan-Fisher** [comment] 2024-03-14 14:34
> `@sentry/react-native@5.19.2` with the following patch helped me workaround the issue
> 
> ```diff
> diff --git a/node_modules/@sentry/react-native/RNSentry.podspec b/node_modules/@sentry/react-native/RNSentry.podspec
> index f9eafb6..1d0fc2f 100644
> --- a/node_modules/@sentry/react-native/RNSentry.podspec
> +++ b/node_modules/@sentry/react-native/RNSentry.podspec
> @@ -33,7 +33,7 @@ Pod::Spec.new do |s|
>    s.preserve_paths = '*.js'
>  
>    s.dependency 'React-Core'
> -  s.dependency 'Sentry/HybridSDK', '8.20.0'
> +  s.dependency 'Sentry/HybridSDK', '8.21.0'
>  
>    s.source_files = 'ios/**/*.{h,mm}'
>    s.public_header_files = 'ios/RNSentry.h'
> ```

I actually tried that, I get this 
<img width="519" alt="Screenshot 2024-03-14 at 7 34 03 AM" src="https://github.com/getsentry/sentry-react-native/assets/57010682/3fa4dce0-4f2d-42ed-8bd6-13b632cd7846"> for some reason. Didn't spend much time trying to debug.

**Comment by akuznetsov-md** [comment] 2024-03-14 15:07
@Evan-Fisher you need update `Sentry/HybridSDK` explicitly 

```sh
pod update Sentry/HybridSDK
```

**Comment by aliza-khu** [comment] 2024-03-15 08:45
@sentry/react-native@5.19.3 fix this issue.

**Comment by mluiten** [comment] 2024-03-15 08:52
Might be coincidence, but when I upgraded to 8.21.0 yesterday, I started receiving emails from Apple that I'm not declaring my PrivacyInfo.xcprivacy -- and it actually explicitly mentions NSPrivacyAccessedAPICategoryFileTimestamp, which I think should be covered by this library... are you sure this file can be bundled as a `resource_bundles` instead of a `resource`?

**Comment by krystofwoldrich** [comment] 2024-03-15 09:52
Fixed in https://github.com/getsentry/sentry-react-native/releases/tag/5.19.3, please upgrade to this or newer releases.

**Closed by krystofwoldrich** 2024-03-15 09:52 UTC
Labels: Platform: React-Native, Waiting for: Product Owner

**Comment by michtntbrighte** [comment] 2024-04-03 03:49
Hi, after upgrading to `@sentry/react-native` version `5.19.3` i have issues with the archiving part on fastlane (but archive works fine locally), it failed in my pipeline, and i've narrowed down that it only happens `sentry-cocoa` version after `8.21.0` is anyone having the same issue? thanks

**Comment by delphinebugner** [comment] 2024-04-03 14:33
Worked for me after upgrading to 5.19.3, thanks @krystofwoldrich! 🌟

**Comment by harisbaig100** [comment] 2024-05-08 09:57
checking for install build only check box in copy bundle resources under build phases can help

**Comment by julian-gargicevich** [comment] 2024-05-09 16:39
Getting this error after upgrading to expo SDK 51

**Comment by a-eid** [comment] 2024-06-20 11:27
we don't use sentry and we're still facing this issue.

**Comment by krystofwoldrich** [comment] 2024-06-20 12:00
Hi @julian-gargicevich,
what version of `@sentry/react-native` are you using? Can you try it with the latest release?

**Comment by krystofwoldrich** [comment] 2024-06-20 12:02
@michtntbrighte 
If the archive is still not working could you open a new issue with more details?

**Comment by HarshitMadhav** [comment] 2024-07-09 12:21
after updating sentry to the 5.19.3 version, issue is fixed but I am facing this issue after the update:
`caused by: sentry reported an error: You do not have permission to perform this action. (http status: 403)`
