### ISSUE TITLE
Error: Unable to resolve module react-native/Libraries/promiseRejectionTrackingOptions

### ISSUE THREAD

**Issue by ejain** [getsentry/sentry-react-native#1927] opened 2021-12-04 04:53 UTC
Encountered the issue described in https://github.com/getsentry/sentry-react-native/issues/1922 after upgrading @sentry/react-native from 2.6.1 to 3.2.5 in a React Native app (0.64.2).

The app builds and runs fine in dev mode, but crashes on startup in release mode.

**Comment by ejain** [comment] 2021-12-04 05:13
Just downgraded to @sentry/react-native 3.2.3, this version appears to be fine.

**Comment by TomCorvus** [comment] 2021-12-04 09:08
Hi,

same problem since `^3.2.5` or `^3.2.4` with `react-native ~0.64.3`. App works fine in dev mode but crash in release mode only on Android.
Need to force 3.2.4 version. `"@sentry/react-native": "3.2.4",` and it works fine.

**Comment by marandaneto** [comment] 2021-12-04 09:32
does this help https://docs.sentry.io/platforms/react-native/troubleshooting/#unhandled-promise-rejections ?

**Comment by marandaneto** [comment] 2021-12-04 09:32
cc @jennmueng

**Comment by marandaneto** [comment] 2021-12-04 09:33
related to https://github.com/getsentry/sentry-react-native/issues/1926 and the other linked issue

**Comment by TomCorvus** [comment] 2021-12-04 12:13
> does this help https://docs.sentry.io/platforms/react-native/troubleshooting/#unhandled-promise-rejections ?

No, not for me.

**Comment by jennmueng** [comment] 2021-12-05 06:43
I'm still not able to reproduce the crash only in release mode, even though I could reproduce the crash from version `3.2.4` in both development and release mode, version `3.2.5` works in both release and development mode for me.

@TomCorvus This is very surprising as version `3.2.4` is the one that should be crashing.

@marandaneto Maybe the simplest solution is to remove the dependency on `react-native/Libraries/promiseRejectionTrackingOptions` altogether. All it does is to prettify the promise rejection error message, before my PR we didn't prettify the message.

**Comment by marandaneto** [comment] 2021-12-06 08:19
@jennmueng agreed, let's remove the `promiseRejectionTrackingOptions` dep then.

**Comment by mrusmanali** [comment] 2021-12-06 08:23
@marandaneto should we expect a release soon. I just commented the try block from `reactnativeerrorhandlers.js` to make my app work, but we need to make this change every time some one make an app release in the team.

**Comment by marandaneto** [comment] 2021-12-06 08:25
yes, later today, @jennmueng needs to confirm if its ready to be merged

**Comment by TomCorvus** [comment] 2021-12-06 08:33
> @TomCorvus This is very surprising as version `3.2.4` is the one that should be crashing.

@jennmueng yes me too, when I saw previous comments, but since the 3.2.5 update, my production release crash on app launch. I tried to downgrade to `^3.2.4` but it crashed too, and when I force the `3.2.4`, it's working.

**Closed** 2021-12-06 20:15 UTC
Labels: Type: :beetle: Bug, Status: Backlog
