### ISSUE TITLE
Gradle sync failed: java.lang.NullPointerException when syncing in Android Studio

### ISSUE THREAD

**Issue by quarryman** [getsentry/sentry-react-native#656] opened 2019-09-06 21:48 UTC
OS:
- [ ]  Windows
- [x ]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [ x]  Android

SDK:
- [x ]  `@sentry/react-native`
- [ ]  `react-native-sentry`

`react-native` version: 0.59.3

Init Code:

```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  release: "3.0.11",
  environment: "production",
});
```

---
I have following issue:

Description goes here ...

**Steps to reproduce:**
- add @sentry/react-native to package.json
- npm i
- npx jetify (for AndroidX support)
- generate sentry.properties for android and add credentials
- add next code to settings.gradle
`include ':@sentry/react-native'
project(':@sentry/react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@sentry/react-native/android')`

**Actual result:**
- Gradle sync failed: java.lang.NullPointerException when syncing in Android Studio

**Expected result:**
- Successful sync in Android studio

If I implement full linking process, result is the same. It breaks after adding those lines and never changes further

**Comment by bhollander-root** [comment] 2019-09-30 14:57
I believe I am having this issue as well. I am on react-native version `0.59.9` and I have not been able to successfully sync Gradle since we updated from `react-native-sentry`.

I found the following `NullPointerException` stacktrace in the Android Studio logs:
```
WARN - ject.sync.ng.SyncResultHandler - Gradle sync failed
java.lang.NullPointerException
    at com.intellij.openapi.roots.impl.ContentEntryImpl.<init>(ContentEntryImpl.java:46)
    at com.intellij.openapi.roots.impl.RootModelImpl.addContentEntry(RootModelImpl.java:416)
    at com.android.tools.idea.gradle.project.sync.setup.module.android.ContentRootsModuleSetupStep.findContentEntries(ContentRootsModuleSetupStep.java:71)
    at com.android.tools.idea.gradle.project.sync.setup.module.android.ContentRootsModuleSetupStep.doSetUpModule(ContentRootsModuleSetupStep.java:58)
    at com.android.tools.idea.gradle.project.sync.setup.module.android.ContentRootsModuleSetupStep.doSetUpModule(ContentRootsModuleSetupStep.java:41)
    at com.android.tools.idea.gradle.project.sync.setup.module.ModuleSetupStep.setUpModule(ModuleSetupStep.java:35)
    at com.android.tools.idea.gradle.project.sync.setup.module.common.BaseSetup.setUpModule(BaseSetup.java:41)
    at com.android.tools.idea.gradle.project.sync.ng.ModuleSetup.setupModuleModels(ModuleSetup.java:143)
    at com.android.tools.idea.gradle.project.sync.ng.SyncProjectModelsSetup.createAndSetUpModules(SyncProjectModelsSetup.java:205)
    at com.android.tools.idea.gradle.project.sync.ng.SyncProjectModelsSetup.setUpModules(SyncProjectModelsSetup.java:141)
    at com.android.tools.idea.gradle.project.sync.ng.ProjectSetup$ProjectSetupImpl.setUpProject(ProjectSetup.java:69)
    at com.android.tools.idea.gradle.project.sync.ng.SyncResultHandler.setUpProject(SyncResultHandler.java:154)
    at com.android.tools.idea.gradle.project.sync.ng.SyncResultHandler.onSyncFinished(SyncResultHandler.java:86)
    at com.android.tools.idea.gradle.project.sync.ng.SyncResultHandler.lambda$onCompoundSyncModels$5(SyncResultHandler.java:267)
    at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:312)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by HazAT** [comment] 2019-10-02 13:51
I am not entirely sure this has to do with our SDK, starting a clean `react-native init` project doesn't have this error, therefore, it most likely has something to do with your project setup.
Can you provide a minimal repro case for this since I suppose you cannot share you project to debug it?!

**Comment by bhollander-root** [comment] 2019-10-02 15:04
@HazAT Thank you for taking the time to troubleshoot this with me. I was able to reproduce this issue by making the following changes after running `react-native init` in order to recreate our project's configuration:

1. In `package.json`, set the `react` version to `16.8.3` and `react-native` to `0.59.9`
2. On the command line, run `yarn add @sentry/react-native`
3. Open the Android project in Android Studio
4. Open `settings.gradle` and replace the lines below `rootProject.name` with the following:
```
include ':@sentry/react-native'
project(':@sentry/react-native').projectDir = new File(rootProject.projectDir, '../node_modules/@sentry/react-native/android')
```
5. Open `File -> Project Structure` in Android Studio
6. Set Gradle Plugin Version to `3.3.1` and Gradle Version to `4.10.3`
7. Click `File -> Sync Project with Gradle Files`

**Comment by HazAT** [comment] 2019-10-08 09:15
@bhollander-root Thanks for the repro.
Why are you replacing these lines in the first place in `settings.gradle`?
For a `react-native init` app the content looks something like this:
```
rootProject.name = 'RN061'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
```
Our docs might be completly out of sync here.

**Comment by bhollander-root** [comment] 2019-10-08 20:46
@HazAT Thanks for updating the docs, but I'm not sure I understand the fix. If I do not define the project in `settings.gradle` and do not include the project in the dependencies in `build.gradle`, it appears that the Java code cannot reference the Sentry library.

**Comment by HazAT** [comment] 2019-10-09 11:01
Is it possible for you to upgrade to a new `react-native` version?
TBH I can't really tell you where exactly the issue is, your repo case by just downgrading the dependencies in `package.json` after a clean `react-native init` doesn't work because it creates a completely different project structure. Can you create a repo somewhere with the broken project which I can just run and see the same error?

**Comment by bhollander-root** [comment] 2019-10-09 14:35
@HazAT Unfortunately, it is not feasible for us to upgrade our react-native version at this time. 
Though I did realized after I posted the original repro instructions that you can run the following command to create a new react-native project with the version we are on:
```
react-native init --version="react-native@0.59.9" ProjectName
```

**Comment by HazAT** [comment] 2019-10-10 07:58
@bhollander-root Did you try these instructions https://github.com/getsentry/sentry-react-native/issues/675#issuecomment-537704167, I think there was `/` too much in our docs.

**Comment by lobsterkatie** [comment] 2019-10-17 14:16
The fix in #675 has been added into the docs in https://github.com/getsentry/sentry-docs/pull/1266.

@quarryman - Can you confirm if this fixes your problem as well? If so I'll close this issue.

**Comment by quarryman** [comment] 2019-10-18 07:34
Will try today and report here. 
Thanx you guys.

**Comment by quarryman** [comment] 2019-10-18 19:06
@lobsterkatie As far as I understand the fix, my app/build.gradle and settings.gradle had required lines initially, nothing I can additionally fix here.

My problem is still there.
If you want extra info from me I am willing to help

**Comment by lobsterkatie** [comment] 2019-10-18 20:31
Drat. But good to know, thanks. Would you be able to provide a minimal repro for us to poke at?

**Closed** 2020-02-12 07:57 UTC
