### ISSUE TITLE
[iOS] Packager source map not found when composing final source map

### ISSUE THREAD

**Issue by yzlin** [getsentry/sentry-react-native#3751] opened 2024-04-09 03:52 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.20.0

**`react-native` version:** 0.73.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

Failed to upload source maps while archiving

```
+ HBC_SOURCEMAP_FILE=/Users/yzlin/Library/Developer/Xcode/DerivedData/ClientSlatedNative-cmygoxgvryogdofjmxlmlhicsmoz/Build/Intermediates.noindex/ArchiveIntermediates/ClientSlatedNative/BuildProductsPath/Release-iphoneos/Slated.app/main.jsbundle.map
+ /Users/yzlin/dev/hajimari-labs/client-slated-native/node_modules/@sentry/cli-darwin/bin/sentry-cli /Users/yzlin/dev/hajimari-labs/client-slated-native/node_modules/react-native/scripts/compose-source-maps.js /Users/yzlin/Library/Developer/Xcode/DerivedData/ClientSlatedNative-cmygoxgvryogdofjmxlmlhicsmoz/Build/Intermediates.noindex/ArchiveIntermediates/ClientSlatedNative/BuildProductsPath/Release-iphoneos/main.jsbundle.map /Users/yzlin/Library/Developer/Xcode/DerivedData/ClientSlatedNative-cmygoxgvryogdofjmxlmlhicsmoz/Build/Intermediates.noindex/ArchiveIntermediates/ClientSlatedNative/BuildProductsPath/Release-iphoneos/Slated.app/main.jsbundle.map -o /Users/yzlin/Library/Developer/Xcode/DerivedData/ClientSlatedNative-cmygoxgvryogdofjmxlmlhicsmoz/Build/Intermediates.noindex/ArchiveIntermediates/ClientSlatedNative/IntermediateBuildFilesPath/ClientSlatedNative.build/Release-iphoneos/ClientSlatedNative.build/DerivedSources/main.jsbundle.map
node:internal/fs/utils:351
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/yzlin/Library/Developer/Xcode/DerivedData/ClientSlatedNative-cmygoxgvryogdofjmxlmlhicsmoz/Build/Intermediates.noindex/ArchiveIntermediates/ClientSlatedNative/BuildProductsPath/Release-iphoneos/main.jsbundle.map'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at Object.<anonymous> (/Users/yzlin/dev/hajimari-labs/client-slated-native/node_modules/react-native/scripts/compose-source-maps.js:34:8)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/yzlin/Library/Developer/Xcode/DerivedData/ClientSlatedNative-cmygoxgvryogdofjmxlmlhicsmoz/Build/Intermediates.noindex/ArchiveIntermediates/ClientSlatedNative/BuildProductsPath/Release-iphoneos/main.jsbundle.map'
}

Node.js v18.19.0
Command PhaseScriptExecution failed with a nonzero exit code
```

**Comment by krystofwoldrich** [comment] 2024-04-10 08:21
Hi @yzlin,
thank you for the message,
reading from the error the Metro packager didn't produce source map to the expected path and the RN tooling failed when composing packager and Hermes source map.

Typically this is caused by white space characters on the path, but I don't see those in the log.

Can you share steps how you step your application and how does your `Bundle React Native code and images` build phase looks like?

**Comment by lab900-guillian-bouchier** [comment] 2024-04-24 07:27
I'm also facing this issue after upgrading both RN (0.73.6) & Sentry (5.22.0)

Here the command and output from metro bundling
`+ /Users/runner/work/1/s/node_modules/@sentry/cli-darwin/bin/sentry-cli /Users/runner/work/1/s/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/BuildProductsPath/Release-iphoneos/main.jsbundle --assets-dest /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/BuildProductsPath/Release-iphoneos/BITS.app --sourcemap-output /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/BuildProductsPath/Release-iphoneos/main.jsbundle.map --minify false --sourcemap-output /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/IntermediateBuildFilesPath/BITS.build/Release-iphoneos/bits.build/DerivedSources/main.jsbundle.map
warning: the transform cache was reset.
                Welcome to Metro v0.80.8
              Fast - Scalable - Integrated


info Writing bundle output to:, /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/BuildProductsPath/Release-iphoneos/main.jsbundle
info Writing sourcemap output to:, /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/IntermediateBuildFilesPath/BITS.build/Release-iphoneos/bits.build/DerivedSources/main.jsbundle.map
`

And then later on when Sentry tries to load the files
`+ /Users/runner/work/1/s/node_modules/@sentry/cli-darwin/bin/sentry-cli /Users/runner/work/1/s/node_modules/react-native/scripts/compose-source-maps.js /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/BuildProductsPath/Release-iphoneos/main.jsbundle.map /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/BuildProductsPath/Release-iphoneos/BITS.app/main.jsbundle.map -o /Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/IntermediateBuildFilesPath/BITS.build/Release-iphoneos/bits.build/DerivedSources/main.jsbundle.map
node:internal/fs/utils:356
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/BuildProductsPath/Release-iphoneos/main.jsbundle.map'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at Object.<anonymous> (/Users/runner/work/1/s/node_modules/react-native/scripts/compose-source-maps.js:34:8)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/runner/Library/Developer/Xcode/DerivedData/bits-bczlxsvjhhkhefbbqhxyanfvbkeo/Build/Intermediates.noindex/ArchiveIntermediates/bits/BuildProductsPath/Release-iphoneos/main.jsbundle.map'
}

Node.js v18.20.2
Command PhaseScriptExecution failed with a nonzero exit code`

So it seems like the main.jsbundle.map file is being put in a different directory by metro compared to the main.jsbundle file which is causing Sentry to fail?

Is there any fix for this?

**Comment by krystofwoldrich** [comment] 2024-04-24 16:19
Hi @yzlin excuse the delayed reply,

the issue is `export EXTRA_PACKAGER_ARGS="--sourcemap-output $TMPDIR/$(md5 -qs "$CONFIGURATION_BUILD_DIR")-main.jsbundle.map"
set -e` if you remove this line the source maps will be created correctly and will be located.

Alternatively you if you want to specify your path to the source maps use `SOURCEMAP_FILE` variable.
https://reactnative.dev/docs/debugging-release-builds#enabling-source-maps

**Comment by krystofwoldrich** [comment] 2024-04-24 16:22
@lab900-guillian-bouchier Can you share with use your Xcode `Bundle React Native code and images` build phase?

If you are using `EXTRA_PACKAGER_ARGS` switch to `SOURCEMAP_FILE` and the source map should be located correctly.

**Comment by lab900-guillian-bouchier** [comment] 2024-04-25 05:55
> @lab900-guillian-bouchier Can you share with use your Xcode `Bundle React Native code and images` build phase?
> 
> If you are using `EXTRA_PACKAGER_ARGS` switch to `SOURCEMAP_FILE` and the source map should be located correctly.

Hi @krystofwoldrich,

Below is my build phase script

```
set -x
export SENTRY_PROPERTIES="$PROJECT_DIR/sentry.properties"
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"

set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
SENTRY_XCODE="../node_modules/@sentry/react-native/scripts/sentry-xcode.sh"
BUNDLE_REACT_NATIVE="/bin/sh $SENTRY_XCODE $REACT_NATIVE_XCODE"

/bin/sh -c "$WITH_ENVIRONMENT \"$BUNDLE_REACT_NATIVE\""
```

So should I change the 2nd export to `SOURCEMAP_FILE` or does something else need to be changed?

**Comment by Elvinra** [comment] 2024-04-25 14:10
I was having the same problem.

So after migrating from the variable "EXTRA_PACKAGER_ARGS" to

`
export SOURCEMAP_FILE="$DERIVED_FILE_DIR/main.jsbundle.map"
`

Everything works normally

And be care like it was said earlier, any **space** in the path of the file, broke the script.
Generally if you have custom scheme on Xcode.

**Closed** 2024-04-26 11:55 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
