### ISSUE TITLE
XCode Build Fails: PhaseScriptExecution failed with a nonzero exit code

### ISSUE THREAD

**Issue by karlludwigweise** [getsentry/sentry-react-native#948] opened 2020-07-01 20:06 UTC
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [ ]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 15.0.0

**`react-native` version:** 0.62.2

**Are you using Expo?**
- [ ]  Yes
- [X]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
**I have following issue:**

Building an iOS App Sentry fails with: `env: node: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code`

Executing `/bin/sh -c /Users/{USERNAME}/Library/Developer/Xcode/DerivedData/{ID}/Build/Intermediates.noindex/{APP}.build/Release-iphoneos/{APP}.build/Script-00DD1BFF1BD5951E006B06BC.sh` in on the console will throw the following error: `line 5: ../node_modules/@sentry/cli/bin/sentry-cli: No such file or directory`

**Steps to reproduce:**

Following the setup on https://docs.sentry.io/platforms/react-native/
- Step 1: `yarn add @sentry/react-native`
- Step 2: `yarn sentry-wizard -i reactNative -p ios android`
- Step 3: `cd ios && pod install`
- Setp 4: Setting up JS Error handling

Connecting the SDK to Sentry and verifying it in DEV Mode works fine.

In XCode:
- Step 5: Clean Build Folder
- Step 6: Build Configuration Release
- Step 7: Removing `localhost` from `App Transport Security Settings`
- Step 8: Run Build

**Actual result:**

Build fails `env: node: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code`

**Expected result:**

Build runs successfully.

**Comment by sprotymo** [comment] 2020-07-02 10:40
@karlludwigweise do You have any solutions? 

I have this errors to.
My env:

System:
    OS: macOS 10.15.5
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.1/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.9.3 - /usr/local/bin/pod
    Homebrew: 2.4.2 - /usr/local/bin/brew
    pip3: 10.0.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  SDKs:
    iOS SDK:
      Platforms: iOS 13.5, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
  IDEs:
    Xcode: 11.5/11E608c - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 1.8.0_171 - /usr/bin/javac
    Ruby: 2.6.3 - /usr/bin/ruby
  
REACT_NATIVE: 
    "react-native": "0.62.2",
    "@sentry/react-native": "^1.5.0",

**Comment by karlludwigweise** [comment] 2020-07-02 12:37
@sprotymo sadly no. There is Issue #108, but none of the work arounds work for me.

**Comment by sprotymo** [comment] 2020-07-02 12:46
@karlludwigweise 
I found fixes for my issue. 
`watchman watch-del-all && rm -rf node_modules/ && rm -rf /tmp/metro-bundler-cache-* && rm -rf /tmp/haste-map-react-native-packager-* && yarn && cd ios && rm -rf Pods && rm -rf Podfile.lock && pod install && cd ../`

remove derivedData, clean build.

**build phases**
Upload Debug Symbols to Sentry =>
`export SENTRY_PROPERTIES=sentry.properties

# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"

$NODE_BINARY ../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
`

Bundle React Native code and images =>
`export SENTRY_PROPERTIES=sentry.properties

# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"
n=$(which node);n=${n%/bin/node}; chmod -R 755 $n/bin/*; sudo cp -r $n/{bin,lib,share} /usr/local


../node_modules/@sentry/cli/bin/sentry-cli react-native xcode
../node_modules/react-native/scripts/react-native-xcode.sh
`

**Comment by karlludwigweise** [comment] 2020-07-02 14:50
@sprotymo what's the *build phases* part? Is that your `.zshrc`?

**Comment by sprotymo** [comment] 2020-07-02 14:55
@karlludwigweise 
build phases part of Xcode.

<img width="772" alt="Screenshot 2020-07-02 at 17 51 50" src="https://user-images.githubusercontent.com/44286086/86374295-0f389b00-bc8d-11ea-88a0-8d025fb4c42c.png">

**Comment by karlludwigweise** [comment] 2020-07-02 15:21
Well, that works like a charm. Where did you get that info?

I guess it is a problem when using Node with a version manager. Thanks 🙏

**Comment by jennmueng** [comment] 2020-07-03 07:46
Hi guys, looks like everything is solved, are we good to close this?

**Comment by sprotymo** [comment] 2020-07-03 07:49
> Well, that works like a charm. Where did you get that info?
> 

found by chance, in the link to the official documentation and possible problems with nvm

**Comment by karlludwigweise** [comment] 2020-07-03 07:51
I would throw in a missing documentation on https://docs.sentry.io/platforms/react-native/ but otherwise I'm good with closing it. 👍

**Closed** 2020-07-03 07:50 UTC

**Comment by karlludwigweise** [comment] 2020-07-05 20:22
Getting back to it a few days later: **This is not a sufficient fix** for me, because it destroyes my development build on the simulator.

**Comment by andrekovac** [comment] 2020-07-31 11:55
I am working on an ejected Expo App in the bare workflow and applied the first part of @sprotymo solution and it works! Thanks!

 In `build phases` I changed the `Upload Debug Symbols to Sentry` script to match the one he describes. I also had the line `export SENTRY_PROPERTIES=sentry.properties` in my original script, so it eventually looked like this:

```
# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"

export SENTRY_PROPERTIES=sentry.properties
$NODE_BINARY ../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

I don't have a `Bundle React Native code and images` script in `build phases` so I didn't add it.

**Comment by anubhavsahoo** [comment] 2020-10-16 11:03
@sprotymo - this guys solution worked for me. though i didnt have to clean adn reinstall everything
I had to add the following scripts to the beginning of the **Build Phase** sections called
1. Bundle react native code and images
2. upload debug symbols to sentry

```
# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"
```

Note append the above to the beginning of those sections - before the existing script that must already be present in those sections.

I am guessing the issue is with using nvm. scripts added by sentry wizard are not able to locate node binaries when you use nvm

**Comment by andru1989** [comment] 2020-12-03 17:47
I was using nvm and non of solutions worked for me

So looking in docs I found this solution: https://docs.sentry.io/clients/react-native/manual-setup/#using-node-with-nvm-or-notion

Basically I set the scripts like this

**Bundle React Native code and images**

```# First set the path to sentry.properties
export SENTRY_PROPERTIES=sentry.properties

# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

# Set up the nodenv node version manager if present
if [[ -x "$HOME/.nodenv/bin/nodenv" ]]; then
eval "$("$HOME/.nodenv/bin/nodenv" init -)"
fi

# Trying notion
if [ -z "$NODE_BINARY" ]; then
if [[ -s "$HOME/.notion/bin/node" ]]; then
export NODE_BINARY="$HOME/.notion/bin/node"
fi
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"

$NODE_BINARY ../node_modules/@sentry/cli/bin/sentry-cli react-native xcode \
  ../node_modules/react-native/scripts/react-native-xcode.sh
```

**Upload Debug Symbols to Sentry**

```
# First set the path to sentry.properties
export SENTRY_PROPERTIES=sentry.properties

# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

# Set up the nodenv node version manager if present
if [[ -x "$HOME/.nodenv/bin/nodenv" ]]; then
eval "$("$HOME/.nodenv/bin/nodenv" init -)"
fi

# Trying notion
if [ -z "$NODE_BINARY" ]; then
if [[ -s "$HOME/.notion/bin/node" ]]; then
export NODE_BINARY="$HOME/.notion/bin/node"
fi
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"

# Run sentry cli script to upload debug symbols
$NODE_BINARY ../node_modules/@sentry/cli/bin/sentry-cli upload-dif "$DWARF_DSYM_FOLDER_PATH"
```

**Comment by karlludwigweise** [comment] 2020-12-04 07:49
@andru1989 thank you. I prefer this one over the solutions above, because it does not mess with local development.

**Comment by Duduzera1997** [comment] 2021-03-31 14:22
`sudo ln -s "$(which node)" /usr/local/bin/node`

This is made my xcode see the node.

**Comment by ptdien** [comment] 2021-04-05 16:35
xcode 12
react-native@0.6.32
sentry/react-native@2.4.0

Took a few hours to debug, finally got it working with the following scripts:

#### Bundle React Native code and images

```
cd $PROJECT_DIR/..

export SENTRY_PROPERTIES=ios/sentry.properties

# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

# Set up the nodenv node version manager if present
if [[ -x "$HOME/.nodenv/bin/nodenv" ]]; then
eval "$("$HOME/.nodenv/bin/nodenv" init -)"
fi

# Trying notion
if [ -z "$NODE_BINARY" ]; then
if [[ -s "$HOME/.notion/bin/node" ]]; then
export NODE_BINARY="$HOME/.notion/bin/node"
fi
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"

$NODE_BINARY ./node_modules/@sentry/cli/bin/sentry-cli react-native xcode ./node_modules/react-native/scripts/react-native-xcode.sh
```

#### Upload Debug Symbols to Sentry

```
cd $PROJECT_DIR/..

export SENTRY_PROPERTIES=ios/sentry.properties

# Setup nvm and set node
[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"

if [[ -s "$HOME/.nvm/nvm.sh" ]]; then
. "$HOME/.nvm/nvm.sh"
elif [[ -x "$(command -v brew)" && -s "$(brew --prefix nvm)/nvm.sh" ]]; then
. "$(brew --prefix nvm)/nvm.sh"
fi

# Set up the nodenv node version manager if present
if [[ -x "$HOME/.nodenv/bin/nodenv" ]]; then
eval "$("$HOME/.nodenv/bin/nodenv" init -)"
fi

# Trying notion
if [ -z "$NODE_BINARY" ]; then
if [[ -s "$HOME/.notion/bin/node" ]]; then
export NODE_BINARY="$HOME/.notion/bin/node"
fi
fi

[ -z "$NODE_BINARY" ] && export NODE_BINARY="node"
$NODE_BINARY ./node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

Hope these help guys!

**Comment by rogerkerse** [comment] 2021-04-25 13:14
> `sudo ln -s "$(which node)" /usr/local/bin/node`
> 
> This is made my xcode see the node.

Very good and clean solution. Worked

**Comment by roycehe** [comment] 2021-06-15 07:11
delete this line `cd $PROJECT_DIR/..`

**Comment by tronin** [comment] 2021-12-15 14:24
Hi folks!

Just replace this `export NODE_BINARY=node` on this `export NODE_BINARY="$(which node)"`

**Comment by sakshiigoyal** [comment] 2021-12-16 06:15
Facing this same issue in my CLI.

`The following build commands failed:
	PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/runner/Library/Developer/Xcode/DerivedData/HomeRunners-gnosqomczzsndwbomqrbflglxvle/Build/Intermediates.noindex/ArchiveIntermediates/HomeRunners/IntermediateBuildFilesPath/HomeRunners.build/Release-iphoneos/HomeRunners.build/Script-00DD1BFF1BD5951E006B06BC.sh (in target 'HomeRunners' from project 'HomeRunners')
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65`

**Comment by tandonpushkar** [comment] 2022-01-08 04:43
This solution worked for me :

**Comment by truongqt** [comment] 2022-04-02 15:25
I fixed my problem: undo rename the project in: Project Settings / PROJECT DETAILS. Hope this help anyone.
<img width="799" alt="Screen Shot 2022-04-02 at 22 24 20" src="https://user-images.githubusercontent.com/7710076/161389954-0e8ab94c-b6bf-4f4f-a5ae-70b3f00a4ebc.png">

**Comment by JeffPatricio** [comment] 2022-04-06 14:44
> `sudo ln -s "$(which node)" /usr/local/bin/node`
> 
> This is made my xcode see the node.

Best solution, it worked for me, thank you very much

**Comment by bwoodlt** [comment] 2022-05-08 19:00
Worked for me

> `sudo ln -s "$(which node)" /usr/local/bin/node`
> 
> This is made my xcode see the node.

Nice one man! Worked for me!
