### ISSUE TITLE
Unhandled Promise rejection causes UnexpectedNativeTypeException

### ISSUE THREAD

**Issue by Matthias-Pichler** [getsentry/sentry-react-native#653] opened 2019-09-05 14:14 UTC
OS:
- [x]  Windows
- [x]  MacOS
- [ ]  Linux

_Platform:_
- [ ]  iOS
- [x]  Android

SDK:
- [ ]  `@sentry/react-native`
- [x]  `react-native-sentry`

`react-native` version: 0.60.5

Init Code:

```javascript
Sentry.init({
  dsn: Config.SENTRY_DSN,
  environment: process.env.NODE_ENV || 'development'
});
```

---
I have following issue:

When a promise rejection is not handled the sentry sdk crashes with an UnexpectedNativeTypeException. But only if the promise rejects with an object that is not of type `Error`. So `Promise.reject({bar: 'foo'});` will crash but `Promise.reject(new Error('foo'));` and `Promise.reject('foo');` will not.

react-native info
```
info Fetching system and libraries information...
System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 105.25 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.9.0 => 16.9.0 
    react-native: ^0.60.5 => 0.60.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

screenshot:
![image](https://user-images.githubusercontent.com/48183213/64341803-6deba480-cfe9-11e9-9fdf-a81fd6b3a278.png)

stacktrace in logcat:
```
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: Exception in native call
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: com.facebook.react.bridge.UnexpectedNativeTypeException: Value for message cannot be cast from ReadableNativeMap to String
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:141)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:129)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:163)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at io.sentry.RNSentryModule.sendEvent(RNSentryModule.java:209)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:873)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:193)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
09-05 13:56:09.528  7448  7530 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)
```

**Steps to reproduce:**
- 
```javascript
Promise.reject({bar: 'foo'});
```

**Actual result:**
- App crashes with UnexpectedNativeTypeException

**Expected result:**
- Report promise rejection

**Comment by HazAT** [comment] 2019-09-05 15:01
Thanks for clarifying the other issue and thanks for the detailed and helpful bug report.
I will fix this and let you know when the new release is out.

**Comment by agarant** [comment] 2019-09-16 01:43
With previous versions, it was possible to set handlePromiseRejection: false. Is there any way to work around this issue with v1 ?

**Comment by HazAT** [comment] 2019-09-16 11:23
@agarant 
You should be able to do:
```js
Sentry.init({
  ...
  integrations: [
    new Sentry.BrowserIntegrations.GlobalHandlers({
      onerror: true,
      onunhandledrejection: false
    })
  ]
});
```

**Comment by HazAT** [comment] 2019-09-16 11:45
Please test `1.0.5` the issue should be fixed there.

**Closed by HazAT** 2019-09-16 11:45 UTC

**Comment by edo1493** [comment] 2019-10-10 14:13
Hey guys,

I am getting the same in production on react-native 0.61.2 and sentry 1.0.7.

I am not able to reproduce on a device, but it seems to be Android only. 

I can see a few of these events showing up in production. 

```
com.facebook.react.bridge.UnexpectedNativeTypeException: Value for level cannot be cast from ReadableNativeMap to String
    at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:139)
    at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:127)
    at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:161)
    at io.sentry.RNSentryModule.eventLevel(RNSentryModule.java:436)
    at io.sentry.RNSentryModule.sendEvent(RNSentryModule.java:175)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
    at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
    at android.os.Looper.loop(Looper.java:193)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
    at java.lang.Thread.run(Thread.java:764)
```
The error is the following.

```
UnexpectedNativeTypeException
Value for level cannot be cast from ReadableNativeMap to String
```

**Comment by matt-dalton** [comment] 2019-10-11 09:24
I'm seeing the same error. react-native 0.60.6 and sentry 1.0.7.

**Comment by edo1493** [comment] 2019-10-11 09:27
I have got this straight after upgrading from react-native 0.59.5 to 0.61.2

**Comment by acollazomayer** [comment] 2019-10-15 15:47
same here with react version 0.61.2 adn sentry 1.0.9

**Comment by mimitch2** [comment] 2019-10-24 23:19
Same here react native version 0.60.6 sentry 1.0.9

**Comment by paul-doherty** [comment] 2019-11-07 10:59
Also seeing it here RN 0.61.2 Sentry 1.0.9

**Comment by MikeWoots** [comment] 2019-11-12 10:27
Also happening for me on RN 0.60.5 Sentry 1.0.9

Error message `Value for level cannot be cast from ReadableNativeMap to String`

**Comment by MikeWoots** [comment] 2019-11-12 12:42
Fixed this issue by changing 

``        Sentry.captureMessage('My message', {
          level: Sentry.Severity.Debug,
        });``

to

``Sentry.captureMessage('My message', Sentry.Severity.Debug);``

**Comment by HaswinVidanage** [comment] 2020-09-21 01:53
I'm seeing this error  on RN 0.60
I've commented out all logs but this occurs when calling init.
any solution for this ?
