### ISSUE TITLE
[Feature] Return 'onEventSentSuccessfully' callbacks.

### ISSUE THREAD

**Issue by NathanielWaggoner** [getsentry/sentry-react-native#810] opened 2020-03-27 18:39 UTC
OS:
- [ ]  Windows
- [ ]  MacOS
- [ ]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 0.39.1 upgrading to 1.3.6
`react-native` version: 0.61.5

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

Hi,

We're upgrading from a very old version of the SDK (0.39.1) and have run into two problems.

First, it looks like Java exceptions are not propagated up to JS layer event handlers (onBeforeSend or EventProcessors).  The JS event emission was removed [here](https://github.com/getsentry/sentry-react-native/pull/589/files/17dfb2452153fc68f1278d81a4d84ccd38d6a5c0#diff-2c23c9bdba652ccf3c4f364415d1c35cL110).  

Second - the onEventSent API looks like it's been replaced by onBeforeSend and EventProcessors. 

Our use case:  We use Sentry to look at JS and Java crashes and wanted to bring in your NDK and ANR support.  We report all sentry metrics to DataDog as well as we find their metrics and visualization tools much more useful for identifying trends across releases for example.  We use the technique of spinning up native sentry ourselves early in the app boot process and then having RNSentry take over once JS has booted - we catch crashes which happen between Application launches and JS readiness.

The two new API's both seem based around adding data to events and filtering out what events are actually sent, but they don't give us any information about what event is successfully reported to sentry.  We've identified a few possible workarounds, but given that Native crashes don't report to sentry we're looking at having to do both JS and native implementations to inspect each and every event sentry reports, determining if it seems likely to actually be sent, and then reporting metrics there (which we suspect will not cleanly align). 

It would be great if you could bring back the old API or something similar so that we can know exactly what event was sent and then pass that along to our other interested consumers.

If there's a way to do this that I missed, please advise!

**Comment by marandaneto** [comment] 2021-11-10 08:12
> First, it looks like Java exceptions are not propagated up to JS layer event handlers (onBeforeSend or EventProcessors). The

correct

> Second - the onEventSent API looks like it's been replaced by onBeforeSend and EventProcessors.

also correct

> The two new API's both seem based around adding data to events and filtering out what events are actually sent, but they don't give us any information about what event is successfully reported to sentry. We've identified a few possible workarounds, but given that Native crashes don't report to sentry we're looking at having to do both JS and native implementations to inspect each and every event sentry reports, determining if it seems likely to actually be sent, and then reporting metrics there (which we suspect will not cleanly align).

there's no API for detecting if an event has been sent or not, there are multiple requests for that but we're still discussing it, since there are some trade-offs, you can start the SDKs manually:
https://docs.sentry.io/platforms/react-native/manual-setup/native-init/

and use the hooks that you've mentioned, I'll follow up on this later

**Comment by marandaneto** [comment] 2022-01-20 13:15
That's won't fix, the transport is fire and forget by design.

**Closed by marandaneto** 2022-01-20 13:15 UTC
Labels: Type: Feature Request, js, Status: Backlog, Platform: React-Native
