### ISSUE TITLE
Ability to know if previous run ended in a crash

### ISSUE THREAD

**Issue by brandonpearcy** [getsentry/sentry-react-native#3473] opened 2023-12-15 00:48 UTC
We are trying to better understand our user behavior before and after they experience crashes, and to do that we would like to log a crash event to a 3rd party service whenever our app crashes. Sentry currently handles crashes for us, however there doesn't seem to be any React Native SDK feature available to detect if the previous run of the app resulted in a crash. Other SDKs like Crashlytics support this, and it is perfect for our use-case.

**Comment by krystofwoldrich** [comment] 2023-12-15 11:47
- I'm closing this as a duplicate of https://github.com/getsentry/sentry-react-native/issues/2797.

We agree this is a good addition to the SDKs API. Please leave a thumbs up and comment on the original issue.

**Closed by krystofwoldrich** 2023-12-15 11:47 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
