### ISSUE TITLE
RNSentry.fetchNativePackageName is not a function (it is undefined)

### ISSUE THREAD

**Issue by TreeOfLearning** [getsentry/sentry-react-native#3506] opened 2024-01-09 11:15 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.15.2

**`react-native` version:** 0.72.6

**Are you using Expo?**
- [x]  Yes
- [ ]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

N/A

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: "http://blah@blah/3",
  debug: true,
  integrations: [
    new Sentry.ReactNativeTracing(),
  ],
  tracesSampleRate: 1.0,
});
```

---
**I have the following issue:**

The following error is thrown when I try to use `Sentry.captureException`:

```
 WARN  Sentry Logger [warn]: [SentryError: Event processing pipeline threw an error, original event will not be sent. Details have been sent as a new event.
Reason: TypeError: RNSentry.fetchNativePackageName is not a function (it is undefined)]
```

I have also tried using `sentry-expo` and get the same issue.

**Steps to reproduce:**
- Call the following code: `Sentry.captureException(new Error("Test error"));`

**Actual result:**

The above error is spammed to the console many times.

**Expected result:**

The captured exception is sent to sentry, and no error is printed in the console.

**Comment by kahest** [comment] 2024-01-11 09:15
Hi @TreeOfLearning thanks for reporting, we'll investigate! Do you know if this also occurs on Android?

@krystofwoldrich I kinda suspected this to be related to https://github.com/getsentry/sentry-react-native/issues/3497, but as this is reported for iOS it's likely something different.

**Comment by krystofwoldrich** [comment] 2024-01-11 10:00
@TreeOfLearning This error could be caused by the native `RNSentry` not being initialized.

Have you rebuilt your native app after adding Sentry to your project (or are you using Expo Go)?

Note: We are working on new Expo experience currently in pre-release https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0-alpha.4

**Comment by wilmxre** [comment] 2024-02-02 19:40
I have also encountered this both on Android and iOS after upgrading from Expo SDK 47 -> 48 -> 49. 

When i call, `Sentry.Native.captureException(new Error(new Date().toUTCString()));`  i get this error on Sentry: `RNSentry.fetchNativePackageName is not a function (it is undefined)`, without any other report or info.

this is my setup: 
```ts
Sentry.init({
  dsn: <redacted>
  enableInExpoDevelopment: true,
  enableAppHangTracking: true,
  tracesSampleRate: 1.0,
  debug: false,
  release: `${Application.applicationId}@${Application?.nativeApplicationVersion}+${Application?.nativeBuildVersion}`,
});
```
package.json:
```log
"expo": "^49.0.0",
"react-native": "0.72.6",
"@sentry/react-native": "5.5.0",
"sentry-expo": "^7.0.1",
"@sentry/cli": "2.20.6", // dev dependency
```
sentry.properties for both Android and iOS:
```log
defaults.url=https://sentry.io/
defaults.org=<redacted>
defaults.project=<redacted>
auth.token=<redacted>
```

After i upgraded to the higher versions i made a new build. (using expo-dev-client). I tested this in development mode, if it would help the case i can also test it in a release build.

The interesting thing is that i have another app where i have upgraded to Expo SDK 49 like 4 months ago and Sentry is set up with the same exact configuration as my current app,  where i encountered this issue, with the same version numbers too and the error reporting works well.

**Comment by krystofwoldrich** [comment] 2024-02-05 15:09
@wilmxre This is likely caused by the deps mismatch, you have to use at least `sentry-react-native@5.10.0`, which is the dependency of `sentry-expo`. The native code used `5.5.0`, but your JS is expecting `5.10.0`.

Please migrate to the newer `@sentry/react-native`, as the latest version supports Expo applications out of the box, `sentry-expo` is not deprecated.

- https://docs.sentry.io/platforms/react-native/migration/sentry-expo/

**Comment by wilmxre** [comment] 2024-02-06 17:49
thanks for the reply @krystofwoldrich, i will try it out

**Comment by krystofwoldrich** [comment] 2024-02-08 12:43
This issue is resolved by https://github.com/getsentry/sentry-react-native/releases/tag/5.16.0

When using with Expo please follow the https://docs.sentry.io/platforms/react-native/migration/sentry-expo/

**Closed by krystofwoldrich** 2024-02-08 12:43 UTC
Labels: Platform: React-Native, Waiting for: Community
