### ISSUE TITLE
Issue with source maps and missing artifacts

### ISSUE THREAD

**Issue by darrylyoung** [getsentry/sentry-react-native#1350] opened 2021-02-17 13:18 UTC
### Environment

How do you use Sentry?
* Sentry SaaS (sentry.io)

Which SDK and version?

* `sentry-expo`: `3.0.4`
* `@sentry/react-native`: `2.2.0`

### Steps to Reproduce

1. Run my app (either via `yarn ios` or from within Xcode) – let's say version `0.0.35`, build `76`
2. See a new release called `0.0.35 (76)` in the Sentry project
3. Check the release and see that there are **0 artifacts**

### Expected Result

Artifacts would be available.

### Actual Result

There are 0 artifacts in the release.

### Setup information

I started my project as an Expo managed app and eventually ejected to the bare workflow.

Everything was working as expected (source maps and artifacts were available) while on `@sentry/react-native` version `1.9.0` but things broke when I upgraded to `2.1.0` and they haven't been right since, regardless of what I've tried. Looking through the Source Maps section in Sentry, I last see a release with artifacts just before I did the `1.9.0` -> `2.1.0` upgrade but none since. Looking back at my changes then, I know I did something wrong – I started using:

`import * as Sentry from '@sentry/react-native'` instead of `import { Native as Sentry } from 'sentry-expo'`

Since then, I've resorted to using `import { Native as Sentry } from 'sentry-expo'` again after trying to debug this with somebody from Expo – I was told that I _didn't need to_ use `sentry-expo` as well as `@sentry/react-native` but that it'd give some extra features if I did.

Here's some setup information:

**sentryConfig.ts**
```ts
import { Platform } from 'react-native'
import { Native as Sentry } from 'sentry-expo'

const SENTRY_DSN_IOS = 'xxx'
const SENTRY_DSN_ANDROID = 'xxx'

export const sentryConfig: Sentry.ReactNativeOptions = {
  dsn: Platform.OS === 'ios' ? SENTRY_DSN_IOS : SENTRY_DSN_ANDROID,
  enableAutoSessionTracking: true,
  debug: __DEV__ ? true : false,
  environment: __DEV__ ? 'development' : 'production',
}

```

**App.tsx**
```tsx
import { Native as Sentry } from 'sentry-expo'

Sentry.init(sentryConfig)

// Sentry.captureException(error)
```

**sentry.properties**
```properties
defaults.url=https://sentry.io/
defaults.org=xxx
defaults.project=xxx
auth.token=xxx
cli.executable=node_modules/@sentry/cli/bin/sentry-cli
```

_Xcode – **Bundle React Native code and images**_
```sh
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh
../node_modules/expo-constants/scripts/get-app-config-ios.sh
../node_modules/expo-updates/scripts/create-manifest-ios.sh
```

_Xcode – **Upload Debug Symbols to Sentry**_
```sh
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli upload-dsym
```

Am I missing a manual step here or is there maybe an issue with my setup? I thought that when running/building a new version/build, a new Sentry release would automatically be created and everything would be handled. Here's a screenshot of the Tags in a recent issue (from a release that has 0 artifacts):

<img width="686" alt="Screenshot 2021-02-17 at 14 04 27" src="https://user-images.githubusercontent.com/1460800/108208409-5050c300-7129-11eb-842b-f95854f9211f.png">

I can see that `dist` is clearly taken from my `build` number and `release` is a combination of the `version` and the `build` numbers. This is clearly done automatically as I don't set that explicitly anywhere.

The only way I've been able to create a new release _and_ get artifacts/source maps is if I run `expo publish` manually. When doing this, I get a new release created but it has a name like `0.0.35-r.-DrbHnWJw` and no issues seem to show up under that release. That release, however, does have artifacts, e.g.

<img width="563" alt="Screenshot 2021-02-17 at 14 09 55" src="https://user-images.githubusercontent.com/1460800/108208874-e08f0800-7129-11eb-8473-3bd798738d2c.png">

whereas the automatically-created releases don't:

<img width="565" alt="Screenshot 2021-02-17 at 14 09 42" src="https://user-images.githubusercontent.com/1460800/108208900-e71d7f80-7129-11eb-93f0-39dd584369c1.png">

Apologies for the length of this issue but I've been stuck with this for a while now and I wanted to give as much context as possible, hoping that it's simply a setup issue on my side. Thanks in advance! Have a a nice day.

**Comment by jennmueng** [comment] 2021-02-19 09:07
What pops out to me as unusual is `0.0.35 (76)` should not be automatically generated by us as this does not match our release name scheme of `{app_identifier}@{version}+{dist}`: [as you can see here](https://github.com/getsentry/sentry-cli/blob/0e28981524241e707451b198f9cc8b68528dd748/src/commands/react_native_xcode.rs#L274-L279). So I'm not sure where this is coming from. 

Also, given that it's what's being set inside the event as well, means this value is being set during runtime somewhere as well, maybe auto-set by sentry-expo?

The team over at `sentry-expo` would probably know more about this than I do, so cc @cruzach.

**Comment by cruzach** [comment] 2021-02-19 16:07
In sentry-expo, we default to Sentry's default (because we want all the errors for build-time sourcemaps to be mapped correctly 😄 ), as you can see [here](https://github.com/expo/sentry-expo/blob/master/src/sentry.ts#L64):
```
nativeOptions.release = `${Application.applicationId}@${Application.nativeApplicationVersion}+${Application.nativeBuildVersion}`;
```

So maybe you are passing in a `release` somewhere to your sentry initialization? Or is there an environment variable that is maybe overwriting the default (this is probably more relevant for the actual artifacts that are being uploaded, since env vars in react native apps aren't really a thing)

Is there anything in the xcode build logs that indicate those build scripts for uploading sourcemaps are failing?

**Comment by jennmueng** [comment] 2021-02-19 16:10
Now that I looked at this a second time with fresh eyes, I'm reminded that Sentry dashboard creates a new release for events with release names that don't match any existing ones. So that's probably what you're seeing with the empty releases, so I would look at whatever is setting that value during runtime.

**Comment by darrylyoung** [comment] 2021-02-19 17:20
Hi, guys. Thanks for looking into this for me – it's very much appreciated!

> So maybe you are passing in a release somewhere to your sentry initialization?

I'm not explicitly passing `release` anywhere as far as I can see, nor do I remember ever doing so. My Sentry config is shown above.

> Or is there an environment variable that is maybe overwriting the default

As with the previous point, I haven't explicitly set anything like that so unless a version of `sentry-expo` or `@sentry/react-native` did that, I can't see this being the issue.

Does my overall setup look correct? Also, do you have any specific places where you suggest I could look for anything else? I've covered as much as I can in the original post above but if there's anything else then I'd be happy to send it as well.

Thanks again, guys. Have a great day and weekend ahead.

**Comment by darrylyoung** [comment] 2021-02-20 08:57
Could it maybe be related to how I'm updating builds? Right now, let's say I'm on version `0.0.35` with build number `81` and I want to increment my build number but keep the same version, I'd do the following:

1. Increment `buildNumber` in `app.json`
2. Open the project in Xcode and bump `Build` in my project target
3. Run the app locally and/or create an Archive and upload to App Store Connect for TestFlight, etc.

Whether the last step is running locally or building an Archive for upload, a new Release will be created in Sentry. In the case of this example, it'd be `0.0.35 (82)`.

**app.json**
```json
{
  "name": "xxx",
  "displayName": "xxx",
  "expo": {
    "name": "xxx",
    "slug": "xxx",
    "version": "0.0.35",
    "sdkVersion": "40.0.0",
    "description": "xxx",
    "privacy": "unlisted",
    "platforms": ["ios", "android"],
    "orientation": "portrait",
    "icon": "./assets/images/icon.png",
    "scheme": "xxx",
    "splash": {
      "image": "./assets/images/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#f9f9f9"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "buildNumber": "82",
      "bundleIdentifier": "xxx",
      "supportsTablet": false,
      "usesAppleSignIn": true,
      "infoPlist": {
        "LSApplicationQueriesSchemes": ["instagram", "twitter", "fb"]
      },
      "config": {
        "usesNonExemptEncryption": false,
        "googleSignIn": {
          "reservedClientId": "xxx"
        }
      }
    },
    "hooks": {
      "postPublish": [
        {
          "file": "sentry-expo/upload-sourcemaps",
          "config": {
            "organization": "xxx",
            "project": "xxx-ios",
            "authToken": "xxx"
          }
        }
      ]
    },
    "android": {
      "package": "xxx"
    }
  }
}
```

Xcode – **Increment Build**
<img width="342" alt="Screenshot 2021-02-20 at 09 50 12" src="https://user-images.githubusercontent.com/1460800/108589973-72348a80-7361-11eb-8ef4-5f68bf50a179.png">

**Comment by cruzach** [comment] 2021-02-20 21:14
Just reproduced this on a blank-ish bare workflow app @darrylyoung - but only on iOS (Android sourcemaps were uploaded perfectly fine during `./gradlew assembleRelease`) 

Will update here if I figure out what's going on here

**Comment by cruzach** [comment] 2021-02-20 21:17
Actually, looks like the issue I'm running into is https://github.com/getsentry/sentry-react-native/issues/888

**Comment by jennmueng** [comment] 2021-02-24 12:36
Ok I've successfully reproduced it as well, if you add the flag `--force-foreground` to the build script in Xcode it seems to work.

So try replacing the "Bundle React Native code and images" build script with this, and see if it works? @darrylyoung @cruzach 

```bash
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export SENTRY_PROPERTIES=sentry.properties
export SENTRY_LOG_LEVEL="info"

# If you are using RN 0.46+
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode --force-foreground
```

I'll be raising this issue to others internally I don't know why it does this.

**Comment by darrylyoung** [comment] 2021-02-24 15:38
Hi, @jennmueng. Thanks for the suggestion. I just tried that and I can see 2 artifacts in the new release. There have been 0 artifacts in previous releases so this clearly helped.

For context, I used the following and the only change was the addition of `--force-foreground`.

```
export NODE_BINARY=node
export EXTRA_PACKAGER_ARGS="--sourcemap-output $DERIVED_FILE_DIR/main.jsbundle.map"
export SENTRY_PROPERTIES=sentry.properties
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode --force-foreground ../node_modules/react-native/scripts/react-native-xcode.sh
../node_modules/expo-constants/scripts/get-app-config-ios.sh
../node_modules/expo-updates/scripts/create-manifest-ios.sh
```

<img width="590" alt="Screenshot 2021-02-24 at 16 35 06" src="https://user-images.githubusercontent.com/1460800/109025062-ac35c180-76be-11eb-960f-b1e2fe13bb77.png">

Thanks to both of you for your help so far with this.

**Comment by jennmueng** [comment] 2021-02-24 19:12
@darrylyoung That error at the top looks like the source map filename was not mapped correctly, it should be replaced to `app:///main.jsbundle` by sentry-expo: https://github.com/expo/sentry-expo/blob/86b93c845fa66f0fc20e16b175793058e6a861e1/src/sentry.ts#L52

**Comment by darrylyoung** [comment] 2021-02-25 09:15
Hi again, @jennmueng. Thanks for the suggestion. I've just made that change and I still have that same issue.

```
There was 1 error encountered while processing this event

Source code was not found

Url | /var/mobile/Containers/Data/Application/xxx/Library/Application Support/.expo-internal/bundle-xxx
```

For context, here's my setup after your suggestion:

**sentry.config**
```
import { Platform } from 'react-native'

const SENTRY_DSN_IOS = 'xxx'
const SENTRY_DSN_ANDROID = 'xxx'

export const sentryConfig = {
  dsn: Platform.OS === 'ios' ? SENTRY_DSN_IOS : SENTRY_DSN_ANDROID,
  enableInExpoDevelopment: true,
  enableAutoSessionTracking: true,
  debug: __DEV__ ? true : false,
  environment: __DEV__ ? 'development' : 'production',
}
```

**App.tsx**
```tsx
import * as Sentry from 'sentry-expo'

Sentry.init(sentryConfig)

// Sentry.Native.captureException(error)
```

**package.json**
```
"@sentry/react-native": "^2.2.1",
"sentry-expo": "^3.0.4",
```

I'm also seeing the following in the issue, in case that helps:

<img width="553" alt="Screenshot 2021-02-25 at 10 07 50" src="https://user-images.githubusercontent.com/1460800/109130459-0b90e180-7752-11eb-8809-ce9619a74cc5.png">

**Comment by RishabhKarnad** [comment] 2021-03-22 20:45
I'm facing this issue too with SDK 1.9.0 as well as 2.1.0. My setup is more similar to the one in #888 though.

Unfortunately, using `--force-foreground` didn't help.

In my case, after looking through the Xcode build logs, I found this warning in the `Bundle React Native code and images` step:

```
Warning: build produced no sourcemaps.
```

It seems to be coming from [this line in Sentry CLI](https://github.com/getsentry/sentry-cli/blob/master/src/commands/react_native_xcode.rs#L242-L245).

I'm not very good at Rust, but hopefully this might help someone debug the issue.

**Comment by leonskim** [comment] 2021-04-09 10:52
Hi @darrylyoung, Have you found out what causes the URL pointing to the device path instead of the uploaded artifact? I'm not using Expo but having the same issue.

**Comment by darrylyoung** [comment] 2021-04-11 07:49
Hi, @leonskim. No, unfortunately not. Have you tried the `--force-foreground` suggestion mentioned above?

**Comment by leonskim** [comment] 2021-04-12 22:38
@darrylyoung Still the same. Didn't work with `--force-foreground` option unfortunately.

**Comment by KochMario** [comment] 2021-06-14 14:19
The same happens for me as well. I'm not using expo, but a raw RN project. Android works perfectly fine and source maps are uploaded automatically. On iOS I do see the info "Sentry: React Native symbol handling started" when archiving with XCode, but they never show up as artifacts in an iOS Release on Sentry.

![image](https://user-images.githubusercontent.com/12862194/121906892-d83b8800-cd2b-11eb-8ff3-c48ce9af4e6f.png)

![image](https://user-images.githubusercontent.com/12862194/121906873-d40f6a80-cd2b-11eb-897c-c567100ab4b8.png)
![image](https://user-images.githubusercontent.com/12862194/121904503-88f45800-cd29-11eb-8d3d-94420d3d0af0.png)

After reading through this issue I tried using `--force-foreground` as well - as can be seen in the above XCode configuration -, but to no avail.
I'm using `@sentry/react-native v2.4.2 `currently.

**Comment by zackify** [comment] 2021-08-12 23:42
This is a big problem.

There's nothing in the docs about it, just says "by default sourcemaps are uploaded with the react native sdk"

luckily found this issue, and was able to add `--force-foreground` and now i can see errors and the stack trace.

I just installed the latest version today and it wasn't working, would be good to get this patched.

**Comment by ghasemikasra39** [comment] 2021-09-14 10:11
I am using ` "@sentry/react-native": "^3.0.3"`. Adding `--force-foreground` did not help:
![Screenshot 2021-09-14 at 12 09 21](https://user-images.githubusercontent.com/24314029/133239101-3105d86e-605f-4272-8123-66883db90c93.png)
![Screenshot 2021-09-14 at 11 08 29](https://user-images.githubusercontent.com/24314029/133239152-1e9b2c05-c260-47b8-b625-be57585de4ca.png)
![Screenshot 2021-09-14 at 11 07 21](https://user-images.githubusercontent.com/24314029/133239201-3e617776-a87d-44ee-8082-dccbb103ed97.png)
![Screenshot 2021-09-14 at 11 05 46](https://user-images.githubusercontent.com/24314029/133239206-853ace90-800a-4d27-910d-97b3e2916456.png)

**Comment by likrot** [comment] 2021-09-21 08:47
@ghasemikasra39 hi, what kind of build have you done? For me, it works only with release/archived versions. When I build debug version dysm file is not uplaoded.

**Comment by ghasemikasra39** [comment] 2021-09-21 12:54
@likrot It only works on `release` versions. If you upload the source maps manually (like me), remove the steps above from your build phases.

**Comment by shaondebnath** [comment] 2021-12-14 23:15
Currently I am using "@sentry/react-native": "^3.2.8" with react-native 0.60.6, I am also having same issue as mention @ghasemikasra39. I have tried with --force-foreground, but it did not solve the issue for me.

**Comment by jennmueng** [comment] 2021-12-16 03:57
@marandaneto This issue seems to me to also be just https://github.com/getsentry/sentry-react-native/issues/1424, which relies on https://github.com/getsentry/sentry-cli/issues/932#issuecomment-986658868. Let's close this one in favor of https://github.com/getsentry/sentry-react-native/issues/1424.

**Closed by jennmueng** 2021-12-16 03:57 UTC
Labels: Platform: iOS/Mac, Status: Awaiting Response, sentry-expo, Status: Backlog

**Comment by biomancer** [comment] 2022-04-19 18:29
In my case adding --force-foreground did not help, but removing NODE_ARGS environment variable did — https://github.com/getsentry/sentry-cli/issues/1039
