### ISSUE TITLE
Task :app:bundleReleaseJsAndAssets_SentryUpload FAILED

### ISSUE THREAD

**Issue by dori871992** [getsentry/sentry-react-native#830] opened 2020-04-27 22:00 UTC
OS:
- [ ]  Windows
- [ ]  MacOS
- [x]  Linux

Platform:
- [ ]  iOS
- [x]  Android

SDK:
- [x]  `@sentry/react-native`
- [ ]  `react-native-sentry`

SDK version: 1.3.7
`react-native` version: 0.61.3"

Are you using Expo?
- [ ]  Yes
- [x]  No

Are you using sentry.io or on-premise?
- [x]  sentry.io (SaaS)
- [ ]  on-premise

I have following issue:

CicrleCi build is failing due to error:
* What went wrong:
```
Execution failed for task ':app:bundleReleaseJsAndAssets_SentryUpload'.
> Process 'command '/root/project/yeppik-react-native/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1
```

**Steps to reproduce:**
- run `./gradlew assembleRelease` for android

**Actual result:**
```
Loading dependency graph, done.
 ▸ Task :app:bundleReleaseJsAndAssets FAILED
 ▸ Task :app:bundleReleaseJsAndAssets_SentryUpload FAILED
Processing react-native sourcemaps for Sentry upload.
error: No such file or directory (os error 2)
```

**Expected result:**
```
Loading dependency graph, done.
 ▸ info Writing bundle output to:, /root/project/android/app/build/generated/assets/react/release/index.android.bundle
 ▸ info Writing sourcemap output to:, /root/project/android/app/build/intermediates/sourcemaps/react/release/index.android.bundle.packager.map
 ▸ info Done writing bundle output
 ▸ info Done writing sourcemap output
 ▸ info Copying 2 asset files
 ▸ info Done copying assets
```

**Comment by storerjeremy** [comment] 2020-05-24 08:17
@dori871992 I'm having the same issue, did you manage to sort it out?

**Comment by dori871992** [comment] 2020-05-24 15:55
@storerjeremy That was related due to assembleRelease failing due to CircleCi running out of memory because it needed more ram to build the project. The error related to sentry was just an aftereffect of assemble process failing.

**Comment by robbycp** [comment] 2020-05-27 04:19
@dori871992 do you set enableHermes true? For me it works fine when enableHermes false

**Comment by dori871992** [comment] 2020-05-27 08:58
@robbycp  yes, hermes is enabled.

**Comment by lukhol** [comment] 2020-05-31 10:50
I have the same issue but it's not memory related. Im running build on my own computer with 8gb xmx for gradle... Is definitely has to be enough. Hermes is disabled.

**Comment by robbycp** [comment] 2020-05-31 14:12
I think it is related with this PR when hermes is enabled. In my case, when i try to build locally in my laptop and hermes enabled, the sourcemap path is changed. So just wait until this PR is merged. https://github.com/getsentry/sentry-react-native/pull/823

**Comment by iagormoraes** [comment] 2020-07-08 04:23
Guys, the issue is solved on: https://github.com/getsentry/sentry-react-native/issues/822, check the PR.

**Comment by tststs** [comment] 2020-07-26 12:12
Also having the issues when hermes is disabled

**Comment by jennmueng** [comment] 2021-09-29 17:44
Closing this on the basis of being more than a year old with no updates. If the issue still persists, feel free to reopen.

**Closed by jennmueng** 2021-09-29 17:44 UTC
Labels: Platform: Android, gradle
