### ISSUE TITLE
React Navigation Ref Object Can Change

### ISSUE THREAD

**Issue by gegana** [getsentry/sentry-react-native#2164] opened 2022-03-26 02:45 UTC
## Summary
This SDK has built in integration with React Navigation. A navigation ref object can actually change, but the integration does not take that into account. As such the subscriptions registered in [this code](https://github.com/getsentry/sentry-react-native/blob/4f97e940a96576457cd7a5b0c7acf884768ded07/src/js/tracing/reactnavigation.ts#L120-L127) no longer become effective, and Sentry.io does not receive new transactions.

### Environment

How do you use Sentry?
Sentry SaaS (sentry.io)

Which SDK and version?
https://github.com/getsentry/sentry-react-native/releases/tag/3.3.5

### Steps to Reproduce
To trigger a change in the navigation ref object, the most obvious way is to replicate this [example](https://reactnavigation.org/docs/5.x/auth-flow) from React Navigation for creating authentication flow.

```js
const routingInstrumentation = new Sentry.ReactNavigationInstrumentation();
Sentry.init({
  ...
  integrations: [
    new Sentry.ReactNativeTracing({
      // Pass instrumentation to be used as `routingInstrumentation`
      routingInstrumentation,
      // ...
    }),
  ],
})

function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const navigation = useRef();
  
  useEffect(() => console.log("Navigation ref mutated"), [navigation ]);
  
  const onReady = useCallback(() => routingInstrumentation.registerNavigationContainer(navigation), []);
  
  return (
    <Stack.Navigator ref={navigation} onReady={onReady}>
      <Stack.Navigator>
        {!isAuthenticated ? <Stack.Screen name="SignIn" component={SignInScreen} /> : <Stack.Screen name="Home" component={HomeScreen} />}
      </Stack.Navigator>
    </Stack.Navigator>
  );
}
```

In the example above, when isAuthenticated changes to true, the navigation ref will mutate. This will cause the subscriptions created by `routingInstrumentation.registerNavigationContainer(navigation), [])` call to be voided. Navigation to the home screen or any other screen in that branch will not get picked up by Sentry.io.

### Expected Result

Navigation to the home screen or any other screen in the` isAuthenticated === true` branch should get picked up by Sentry.io.

### Actual Result

Only navigation to the screens (SignInScreen) in the `isAuthenticated === false` branch shows up in Sentry.io.

### Proposed Solution
Create a ` routingInstrumentation.reinstateNavigationContainer(navigation)` function that will reinstate the subscriptions to the navigation object. Update the documentation to reference how to handle such scenario:

```js
const routingInstrumentation = new Sentry.ReactNavigationInstrumentation();
Sentry.init({
  ...
  integrations: [
    new Sentry.ReactNativeTracing({
      // Pass instrumentation to be used as `routingInstrumentation`
      routingInstrumentation,
      // ...
    }),
  ],
})

function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const navigation = useRef();
 
  useEffect(() => routingInstrumentation.reinstateNavigationContainer(navigation), [navigation ]);
  
  const onReady = useCallback(() => routingInstrumentation.registerNavigationContainer(navigation), []);
  
  return (
    <Stack.Navigator ref={navigation} onReady={onReady}>
      <Stack.Navigator>
        {!isAuthenticated ? <Stack.Screen name="SignIn" component={SignInScreen} /> : <Stack.Screen name="Home" component={HomeScreen} />}
      </Stack.Navigator>
    </Stack.Navigator>
  );
}
```

### Temporary Solution
This is how I workaround the problem temporarily, but it is hacky:

```js
const routingInstrumentation = new Sentry.ReactNavigationInstrumentation();
Sentry.init({
  ...
  integrations: [
    new Sentry.ReactNativeTracing({
      // Pass instrumentation to be used as `routingInstrumentation`
      routingInstrumentation,
      // ...
    }),
  ],
})

function App() {
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const navigation = useRef();
 
  useEffect(() => {
    global.__sentry_rn_v5_registered = false;
    routingInstrumentation.registerNavigationContainer(navigation)
  }, [navigation]);
  
  const onReady = useCallback(() => routingInstrumentation.registerNavigationContainer(navigation), []);
  
  return (
    <Stack.Navigator ref={navigation} onReady={onReady}>
      <Stack.Navigator>
        {!isAuthenticated ? <Stack.Screen name="SignIn" component={SignInScreen} /> : <Stack.Screen name="Home" component={HomeScreen} />}
      </Stack.Navigator>
    </Stack.Navigator>
  );
}
```

**Comment by marandaneto** [comment] 2022-03-26 07:43
Thanks for the detailed report @gegana 
We'll look into it.

**Comment by jennmueng** [comment] 2022-03-28 18:28
@gegana I have not been able to reproduce an issue regarding navigation refs, tried a `useState` with an authenticated ternary like your example. But I see a couple issues with your code here, first you want to pass the ref and onReady to the `NavigationContainer` not the `Stack.Navigator`.

Also,
```js
 useEffect(() => console.log("Navigation ref mutated"), [navigation ]);
```
the useEffect would be called on every re-render because `navigation` will always be mutated (a different reference pointer) because of how `useRef` works, you would rather be concerned with `navigation.current` instance being mutated, even with this, I still am not able to reproduce this issue.

I will be closing this for now unless a new reproducable example is presented.

**Closed** 2022-03-28 18:28 UTC
Labels: performance, Platform: React-Native

**Comment by gegana** [comment] 2022-03-30 01:00
> @gegana I have not been able to reproduce an issue regarding navigation refs, tried a `useState` with an authenticated ternary like your example. But I see a couple issues with your code here, first you want to pass the ref and onReady to the `NavigationContainer` not the `Stack.Navigator`.
> 
> Also,
> 
> ```js
>  useEffect(() => console.log("Navigation ref mutated"), [navigation ]);
> ```
> 
> the useEffect would be called on every re-render because `navigation` will always be mutated (a different reference pointer) because of how `useRef` works, you would rather be concerned with `navigation.current` instance being mutated, even with this, I still am not able to reproduce this issue.
> 
> I will be closing this for now unless a new reproducable example is presented.

Out of curiosity which React Navigation version did you use? In my example I used V5, I haven't tested the behavior with V6 yet.

> But I see a couple issues with your code here, first you want to pass the ref and onReady to the `NavigationContainer` not the `Stack.Navigator`.

I'm simply following the example [here](https://docs.sentry.io/platforms/react-native/performance/instrumentation/automatic-instrumentation/).

> the useEffect would be called on every re-render because `navigation` will always be mutated (a different reference pointer) because of how `useRef` works

I'm pretty sure that is not how a useRef works, you get the same reference pointer, but you are right I made a typo in my example. In any case the issue here is that the `navigation.current` changes on my end, maybe because I'm using V5? I'll see how V6 behaves.

**Comment by gegana** [comment] 2022-03-30 01:24
@marandaneto @jennmueng I have traced the issue in React Navigation https://github.com/react-navigation/react-navigation/issues/9213. It looks like it is a bug on their end, but it is still useful to mention it in the Sentry documentation in case there are users out there using v5.

**Comment by marandaneto** [comment] 2022-03-30 07:10
@gegana that's a very good point, thanks for coming back to us.

https://github.com/getsentry/sentry-docs/pull/4886/files
I've added an entry to our troubleshooting page.
