### ISSUE TITLE
XCode Build Error - Sentry Cocoa 6.0.8

### ISSUE THREAD

**Issue by ericschaal** [getsentry/sentry-react-native#1186] opened 2020-11-10 21:27 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [x]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 2.0.0

**`react-native` version:** 0.63.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have following issue:**

My app is failing to build (release) on Xcode 12.1 since Sentry Cocoa 6.0.8 got released.

**Steps to reproduce:**
- Generate a standalone RN app.
- Integrate sentry-react-native
- Build in release 

**Actual result:**

```
/[...]/node_modules/@sentry/react-native/ios/RNSentry.m:151:54: No visible @interface for 'SentryClient' declares the selector 'fileManager'
```

**Expected result:**

App should build without error.

**Workaround:**

I was able to build my app by modifying `node_modules/@sentry/react-native/ios/RNSentry.podspec`:

```
- s.dependency 'Sentry', '~> 6.0.3'
+ s.dependency 'Sentry', '6.0.7'
```

**Comment by mcchrish** [comment] 2020-11-11 00:34
Can confirm the work around fixes the error.

**Comment by ugglr** [comment] 2020-11-11 07:07
I have the same issue

**Comment by vitalyiegorov** [comment] 2020-11-11 07:08
Also facing the same issue

**Comment by bergiusj** [comment] 2020-11-11 10:44
Facing this as well.

**Comment by notjulian** [comment] 2020-11-11 13:54
I have same error and workaround works for me

edit Podfile.lock

```
  - Sentry (6.0.7):
    - Sentry/Core (= 6.0.7)
  - Sentry/Core (6.0.7)
```

then
`npx pod-install`

maybe it is not the cleanest way ...

**Comment by nbolender** [comment] 2020-11-12 00:38
I was able to specify the Sentry version in my project Podfile then run `pod update`. This is probably the cleanest workaround until whatever is wrong is fixed.

```
target 'MyApp' do
    pod 'Sentry', '6.0.7'

    config = use_native_modules!

    ...
    
end
```

**Comment by jennmueng** [comment] 2020-11-12 08:22
Sentry Cocoa `6.0.8` is supposed to be used with this PR https://github.com/getsentry/sentry-react-native/pull/1188 and wouldn't work with prior versions.

I apologize for this, next time we should explicitly state which version of Cocoa instead of using ~>

**Comment by freedomzzzii** [comment] 2020-11-13 10:14
I have save issue (fail on release mode but on debug mode is success)

detail error: No visible @interface for 'SentryClient' declares the selector 'fileManager'

environment:
"react": "16.13.1",
"react-native": "0.63.3",
"@sentry/react-native": "^2.0.0",

**Comment by SahilPawar1994** [comment] 2020-11-15 14:51
I had this same issue, I was using v.1.7.1 and after upgrading to 2.0.0, I am facing the issue "No visible @interface for 'SentryClient' declares the selector 'fileManager'"

I simply **delete the RNSentry folder from ios/Pods** and then again I did **pod install** and it was working as expected.

**Comment by anthlasserre** [comment] 2020-11-16 22:29
I think a PR is actually trying to fix this issue.
https://github.com/getsentry/sentry-react-native/pull/1188

**Comment by sperezm97** [comment] 2020-11-17 02:59
Still persists on Cocoa `6.0.9` when i try to run it using Github Actions

**Comment by RodolfoGS** [comment] 2020-11-17 14:14
@freedomzzzii @SahilPawar1994 @anthlasserre @sperezm97 
Add `pod 'Sentry', '6.0.7'` to your Podfile file. Like this:

```
target 'MyApp' do
    pod 'Sentry', '6.0.7' # <-- Add this line

    config = use_native_modules!
    ...    
end
```

**Comment by jennmueng** [comment] 2020-11-19 10:05
This issue has been fixed in version [2.0.1](https://github.com/getsentry/sentry-react-native/releases/tag/2.0.1).

**Closed by jennmueng** 2020-11-19 10:05 UTC
Labels: Platform: iOS/Mac, Status: Awaiting Fix, Type: :beetle: Bug

**Comment by diegolmello** [comment] 2020-11-19 13:45
I can confirm 2.0.1 works. Thank you.

**Comment by ecgreb** [comment] 2020-11-19 20:08
Thanks for the quick fix!

v2.0.1 works for me as well - although I did have to run `pod update Sentry` after upgrading from 2.0.0 to resolve transitive dependencies on `Sentry` and `Sentry/Core` 6.0.8

just wanted to share in case anyone else runs into the same issue when running `pod install`

**Comment by eridr** [comment] 2020-11-20 15:35
RNSentry 2.0.0 kept crashing but updating to 2.0.2 fixed it for me:

npm install --save @sentry/react-native
# OR
yarn add @sentry/react-native
