### ISSUE TITLE
npm run ios hang by 'Bundle React Native code and images'

### ISSUE THREAD

**Issue by Bob-MYMC** [getsentry/sentry-react-native#3401] opened 2023-11-16 01:06 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.13.0

**`react-native` version:** 0.71.7

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

`npx react-native run-ios` hang on step
▸ Running script 'Bundle React Native code and images'

```
		00DD1BFF1BD5951E006B06BC /* Bundle React Native code and images */ = {
			isa = PBXShellScriptBuildPhase;
			buildActionMask = 2147483647;
			files = (
			);
			inputPaths = (
				"$(SRCROOT)/.xcode.env.local",
				"$(SRCROOT)/.xcode.env",
			);
			name = "Bundle React Native code and images";
			outputPaths = (
			);
			runOnlyForDeploymentPostprocessing = 0;
			shellPath = /bin/sh;
			shellScript = "set -e\n\nWITH_ENVIRONMENT=\"../node_modules/react-native/scripts/xcode/with-environment.sh\"\nREACT_NATIVE_XCODE=\"../node_modules/react-native/scripts/react-native-xcode.sh\"\nSENTRY_XCODE=\"../node_modules/@sentry/react-native/scripts/sentry-xcode.sh\"\nBUNDLE_REACT_NATIVE=\"/bin/sh $SENTRY_XCODE $REACT_NATIVE_XCODE\"\n\n/bin/sh -c \"$WITH_ENVIRONMENT \\\"$BUNDLE_REACT_NATIVE\\\"\"";
		};
```

running the app in Xcode does not have the issue

**Comment by krystofwoldrich** [comment] 2023-11-17 09:56
Thank you for the message,
could you share the tail of the log what is the last thing before it hangs?

Does the same happen without Sentry?

**Comment by kekami** [comment] 2023-11-24 09:52
After upgrading to 5.14.1 I'm also experiencing it.

Here is the tail of the build log:
```
Node found at: /Users/cicd/.nvm/versions/node/v18.17.1/bin/node
+ '[' -z sentry.properties ']'
+ '[' -z '' ']'
+ export SOURCEMAP_FILE=/Users/xxxx/Library/Developer/Xcode/DerivedData/xxxx-bisovmqybajklqbcxckinulkxczi/Build/Intermediates.noindex/ArchiveIntermediates/xxxx-Beta/IntermediateBuildFilesPath/xxxx.build/Beta-iphoneos/xxxx.build/DerivedSources/main.jsbundle.map
+ SOURCEMAP_FILE=/Users/xxxx/Library/Developer/Xcode/DerivedData/xxxx-bisovmqybajklqbcxckinulkxczi/Build/Intermediates.noindex/ArchiveIntermediates/xxxx-Beta/IntermediateBuildFilesPath/xxxx.build/Beta-iphoneos/xxxx.build/DerivedSources/main.jsbundle.map
+ '[' -z '' ']'
+ SENTRY_CLI_EXECUTABLE=../node_modules/@sentry/cli/bin/sentry-cli
+ REACT_NATIVE_XCODE=../node_modules/react-native/scripts/react-native-xcode.sh
+ [[ true != true ]]
+ ARGS='  '
+ REACT_NATIVE_XCODE_WITH_SENTRY='"../node_modules/@sentry/cli/bin/sentry-cli" react-native xcode    "../node_modules/react-native/scripts/react-native-xcode.sh"'
+ '[' '' '!=' true ']'
+ /bin/sh -c '"../node_modules/@sentry/cli/bin/sentry-cli" react-native xcode    "../node_modules/react-native/scripts/react-native-xcode.sh"'

```

My `Bundle React Native code and images`
```
set -e

WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh --log-level=debug --force-foreground"
SENTRY_XCODE="../node_modules/@sentry/react-native/scripts/sentry-xcode.sh"
BUNDLE_REACT_NATIVE="/bin/sh $SENTRY_XCODE $REACT_NATIVE_XCODE"

# RN 0.69+
/bin/sh -c "$WITH_ENVIRONMENT \"$BUNDLE_REACT_NATIVE\""

```

**Comment by esenbi** [comment] 2023-11-25 08:15
have the same problem

**Comment by Reeywhaar** [comment] 2023-11-25 23:20
I has the same problem in xcode cloud but can't reproduce locally both on m1 and intel macs.

**Comment by hstaudacher** [comment] 2023-11-26 18:11
Same problem

**Comment by krystofwoldrich** [comment] 2023-11-27 13:17
Thank you all for the messages, I can't reproduce this locally.

What is the log output when using this:

```bash
export SENTRY_CLI_EXTRA_ARGS="--force-foreground --log-level debug"
```

**Comment by kekami** [comment] 2023-11-27 13:40
It seems to be related to this: https://github.com/getsentry/sentry-cli/issues/1820 Something is going on with x86-84 and/or CI builds.

Managed to resolve it by adding a dependency resolution in `package.json`
```
  "resolutions": {
    "@sentry/cli": "2.21.2"
  },
```

**Comment by timqha** [comment] 2023-11-27 17:54
It can't be reproduced locally only on the Xcode cloud.

**Comment by krystofwoldrich** [comment] 2023-11-27 22:17
`@sentry/react-native` version `5.14.1` comes bundled with `@sentry/cli@2.21.3`. We are currently investigating the issue.

Reverting to `@sentry/cli@2.21.2` should prevent the hang-up.

```bash
npm i @sentry/cli@2.21.2 --save --dev
yarn add @sentry/cli@2.21.2 --save-dev
```

**Comment by Bob-MYMC** [comment] 2023-11-28 12:56
> `@sentry/react-native` version `5.14.1` comes bundled with `@sentry/cli@2.21.3`. We are currently investigating the issue.
> 
> Reverting to `@sentry/cli@2.21.2` should prevent the hang-up.
> 
> ```shell
> npm i @sentry/cli@2.21.2 --save --dev
> yarn add @sentry/cli@2.21.2 --save-dev
> ```

The solutions works. Thanks @krystofwoldrich @kekami

**Comment by krystofwoldrich** [comment] 2023-12-01 12:30
This is a duplicate of https://github.com/getsentry/sentry-cli/issues/1820

- https://github.com/getsentry/sentry-cli/issues/1820

Please follow the progress there.

**Closed by krystofwoldrich** 2023-12-01 12:30 UTC
Labels: Platform: React-Native

**Comment by stianjensen** [comment] 2023-12-06 10:53
A new version of the cli with a fix is released now:
https://github.com/getsentry/sentry-cli/releases/tag/2.23.0
