### ISSUE TITLE
sentry is too havy for JS bundle (adds 500Kb prod)

### ISSUE THREAD

**Issue by vovkasm** [getsentry/sentry-react-native#3826] opened 2024-05-18 16:08 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.22.2

**`react-native` version:** 0.73.8

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```typescript
const routingInstrumentation = new Sentry.ReactNavigationInstrumentation({
  enableTimeToInitialDisplay: true,
});

    Sentry.init({
      dsn: Config.SENTRY_DSN,
      environment: Config.ENVIRONMENT,
      // enabled: !__DEV__,
      enableNative: true,
      tracesSampleRate: Config.ENVIRONMENT === "development" ? 1.0 : 0.01,
      integrations: [new Sentry.ReactNativeTracing({routingInstrumentation})],
    });
```

---
First of all, I want to thank the team for a wonderful product that greatly helps the entire community.

However, in recent years the product has become too heavy. Its total size in the production JS bundle is equal to the size of the entire RN, about to 500Kb. This can lead to slowdown at startup for highly optimized applications.

**Steps to reproduce:**
- Create empty RN application
- Just add `@sentry/react-native` to package.json and link it according to documentations
- Build JS bundle, for ex: `npx react-native bundle --entry-file index.js --platform android --dev false --bundle-output bundle0.dat --sourcemap-output bundle0.map`
- Show the results: `npx source-map-explorer --no-border-checks bundle0.dat bundle0.map`

**Actual result:**

In out real application it looks like this
<img src="https://github.com/getsentry/sentry-react-native/assets/95272/f25bb969-1e67-491d-8c0a-27e3037f8c06" width="480" alt="sentry weight in real RN project" />

In clean RN project (as in repro)
<img width="480" alt="sentry weight in clean RN project" src="https://github.com/getsentry/sentry-react-native/assets/95272/d7250693-1ad7-4490-9e2b-4987e7afb83d">

**Expected result:**
I think it would be very good if the sentry weight was no more than 150Kb. I'm worried that people will stop using the sentry because it's so heavy, but it's a very good tool.

**Comment by vovkasm** [comment] 2024-05-18 17:44
Potentially relative issues: #3718, #1818, #1733

**Comment by krystofwoldrich** [comment] 2024-05-24 09:23
Hi @vovkasm,
thank you for the kind words as well for expressing the worries.

Our browsers and core JS packages rely heavily on tree shaking which is not supported our of the box in React Native.

We realize that and are looking for other options to optimalize the size of the SDK.

- https://github.com/getsentry/sentry-react-native/issues/3718

I'll close this as a duplicate of https://github.com/getsentry/sentry-react-native/issues/3718, we take this serious, I just want to keep all the discussion at one place. Please feel free to comment there as well as up vote the issue, that helps us prioritizing.

**Closed by krystofwoldrich** 2024-05-24 09:23 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
