### ISSUE TITLE
Automatic Instrumentation don't track correctly navigation with react-native-navigation 

### ISSUE THREAD

**Issue by ludwig-pro** [getsentry/sentry-react-native#2066] opened 2022-02-16 08:39 UTC
Hello ! I have some struggle with **Automatic Instrumentation** and `react-native-navigation`  ! 

I currently have only one screen tracked with the correct name. Other don't appear in the performance dashboard.

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/62896243/154224752-2b63d6e4-1291-4797-b381-28b6e743df64.png">

it's look like other navigation events are capture as Error by sentry

![image](https://user-images.githubusercontent.com/62896243/154224844-94e765cd-9066-499b-9cf6-fc84bb220f6a.png)

### Environment

How do you use Sentry?
**Sentry SaaS (sentry.io)**

Which SDK and version?
```js
// package.json
    "@sentry/react-native": "3.2.14-beta.1", <= to fix route name problem

// podfile.lock
  - RNSentry (3.2.14-beta.1):
    - React-Core
    - Sentry (= 7.9.0)
     
  - Sentry (7.9.0):
    - Sentry/Core (= 7.9.0)
  - Sentry/Core (7.9.0)
```

**Comment by ludwig-pro** [comment] 2022-02-16 08:47
Also, it's look like sometimes transaction still keep **Route Name** name

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/62896243/154227771-1cfdfada-0f75-440c-88b6-95293e5f5ab5.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/62896243/154228200-33407575-08f1-4d36-ae01-c647b61507c8.png">

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/62896243/154227348-de05a1a3-d727-4d7f-9d50-e126bab18e5a.png">

**Comment by saintpepsicola** [comment] 2022-02-21 04:30
Is this fixed in beta? I am still seeing 'Route Change'

**Comment by ludwig-pro** [comment] 2022-02-21 08:54
Partially fixed! I started to see some screen name but not all the time

**Comment by marandaneto** [comment] 2022-02-22 08:06
cc @jennmueng please have a look at it, apparently there's still edge cases for https://github.com/getsentry/sentry-react-native/pull/2053

**Comment by jennmueng** [comment] 2022-03-04 21:08
I will take a look at reproducing this, looks like a similar issue as https://github.com/getsentry/sentry-react-native/pull/2053 but for `react-native-navigation`

**Closed** 2022-03-08 08:17 UTC
Labels: Status: Awaiting Response, Platform: React-Native
