### ISSUE TITLE
options.initialScope is not supported

### ISSUE THREAD

**Issue by jennmueng** [getsentry/sentry-react-native#1661] opened 2021-07-09 15:04 UTC
Passing `initialScope` in the options does not work on RN or any of the JS-Hybrid SDKs as the scope's `update` method sets each value individually and does not call the extended methods that send the scope down to the native layer.

**Comment by pke** [comment] 2021-10-01 23:06
I can confirm, it took me an hour to play with initial scope but it does not seem to allow me to add tags.
However, `Sentry.configureScope` also does not allow me to add tags.

```
Sentry.init({
 //...,
 initialScope(scope) {
   return scope.setTag("test", true)
 }
```

The `test` tag never shows up on any issue.

**Comment by marandaneto** [comment] 2021-11-26 13:26
figure out if this is part of the unified API and if we should add to the SDKs that don't.

workaround for now would be calling `Sentry.init{...}` and then later `Sentry.configureScope { it -> it.setTag(x, y) }`

**Comment by marandaneto** [comment] 2021-12-02 12:49
the reason is that when you call eg `Sentry.serUser(...)` or `Sentry.configureScope { it -> it.setUser(...) }`, the RN SDK forwards the call to the Native SDKs so the scope gets synced, See https://github.com/getsentry/sentry-react-native/blob/master/src/js/wrapper.ts#L340

we'd need to do the same when setting context via `initialScope`

**Comment by philipphofmann** [comment] 2021-12-02 14:36
`initialScope` was only added to JavaScript, because it was needed for Electron. We don't have a real use case for other SDKs and therefore we want to remove it from ReactNative.

**Comment by marandaneto** [comment] 2021-12-03 08:27
closing in favor of https://github.com/getsentry/sentry-react-native/issues/1925

**Closed by marandaneto** 2021-12-03 08:27 UTC
Labels: Type: :beetle: Bug, Status: Awaiting Fix, Status: Backlog
