### ISSUE TITLE
Linked errors are not symbolicated (RewriteFrames and LinkedErrors are not in correct order)

### ISSUE THREAD

**Issue by doronpr** [getsentry/sentry-react-native#3468] opened 2023-12-14 08:49 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` 5.12.0 (also reproduceble in 5.15.1)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.71.8

**Are you using Expo?**
- [x]  Yes
- [x]  No
(reproduceable in both)

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

[[Link to issue]](https://wix-o.sentry.io/discover/mobile-dev:6f55f6250cec4e43ae9fa9476db47f15/)

---
**I have the following issue:**
After upgrading to `sentry-react-native@5.12.0` all linked errors became unminified.
This is a big problem for us as it creates duplicate issues in Sentry.

[Description]

**Steps to reproduce:**
- Step 1: install version 5.12.0
- Step 2: Send error as follows:
```
  const e1 = new Error('inner')
  const e = new Error('TRY3', {cause: e1});
  Sentry.captureException(e, );
```

**Actual result:**
Linked frame (inner) looks like this:
```
  File "/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.name.sentryplain", line 101276, col 25, in ?anon_0_

```
[[Link to issue same code w/ 5.12.0]](https://wix-o.sentry.io/discover/mobile-dev:6f55f6250cec4e43ae9fa9476db47f15/)

**Expected result:**
```
  File "app:///main.jsbundle", line 101276, col 25, in ?anon_0_
```
[[Link to issue same code w/ 5.11.0]](https://wix-o.sentry.io/discover/mobile-dev:4b0730533f7945d9b0cf41e6ab81d614/)

**Comment by krystofwoldrich** [comment] 2023-12-14 13:24
Hi, 
thank you for the message,

there were no changes to the error frames processing in the SDK between 5.11.0 and 5.12.0.

From the examples you shared the `File "app:///main.jsbundle", line 101276, col 25, in ?anon_0_` is from a Release build of your application. And `File "/index.bundle//&platform=ios&dev=true&minify=false&modulesOnly=false&runModule=true&app=org.name.sentryplain", line 101276, col 25, in ?anon_0_` is from Debug build. 

The Local Symbolication in Debug builds only symbolicates the first Error. -> https://github.com/getsentry/sentry-react-native/issues/2118 This is to be fixed in our backlog.

If you run the application in Release build with 5.12.0 or newer the stack trace should match the one from 5.11.0.

**Comment by doronpr** [comment] 2023-12-14 16:46
Hi @krystofwoldrich thanks for looking into this.
I didn't notice the env change , BUT - it's very weird, I haven't changed anything between the two versions.
It seems that Sentry sets the env as `production` in `5.12.0` and `dev` in `5.15.1`.

I created a minimum reproduce repo where I can consistently reproduce it.
Can you please check it at https://github.com/doronpr/sentry-plain/tree/main#reproduce-instructions?

**Comment by krystofwoldrich** [comment] 2023-12-15 12:34
@doronpr Thank you for the reproducer, we'll check it.

**Comment by doronpr** [comment] 2024-01-03 08:40
> @doronpr Thank you for the reproducer, we'll check it.

Hey @krystofwoldrich did you have a chance to look into this?

**Comment by krystofwoldrich** [comment] 2024-01-04 10:35
Hi, thanks for the bump, due to my Christmas Vacation I didn't, I'll keep you updated.

**Comment by krystofwoldrich** [comment] 2024-01-04 18:22
Integration refactoring changed the order in which the integration's event processors are called. This caused the `NativeLinkedErrors` integration to run after `RewriteFrames` so linked errors are never rewritten.

Before https://sentry-sdks.sentry.io/share/issue/b6229460f55e445ba7dacb608d97ed18/
<img width="952" alt="Screenshot 2024-01-04 at 19 18 19" src="https://github.com/getsentry/sentry-react-native/assets/31292499/30f6f18e-b871-46f6-ae4d-f5e63001df0b">

After https://sentry-sdks.sentry.io/share/issue/4cb6e456336a47d595f5813cc05ffc4a/
<img width="958" alt="Screenshot 2024-01-04 at 19 18 07" src="https://github.com/getsentry/sentry-react-native/assets/31292499/db677703-7a03-4aa9-b0b4-0e8cc01b948c">

- Suspect PR: https://github.com/getsentry/sentry-javascript/pull/9021

**Closed** 2024-01-25 05:08 UTC
Labels: Type: :beetle: Bug, Platform: React-Native
