### ISSUE TITLE
Sourcemaps not parsed correctly, using 5.4.2 with sentry-expo

### ISSUE THREAD

**Issue by jongbelegen** [getsentry/sentry-react-native#3064] opened 2023-05-12 12:19 UTC
**OS:**
- [ ]  Windows
- [X]  MacOS
- [ ]  Linux

**Platform:**
- [X]  iOS
- [X]  Android

**SDK:**
- [X]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.4.2

**`react-native` version:** 0.71.7

**Are you using Expo?**
- [X]  Yes **(With eas build, so not the premade runtime)**
- [ ]  No

**Are you using sentry.io or on-premise?**
- [X]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
ios: https://fastlane-festivals.sentry.io/issues/4177600521/?project=4505164525535232&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
android: https://fastlane-festivals.sentry.io/issues/4177474793/?project=4505164525535232&query=is%3Aunresolved&referrer=issue-stream&stream_index=3

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: "https://7299b45869854e44be478ad0fdfe6c43@o1366760.ingest.sentry.io/4505164525535232",
  enableInExpoDevelopment: true,
});
```

---
**I have the following issue:**
Sourcemaps are not parsed correctly. 
Firstly I spoke with @krystofwoldrich about a problem [relating to an older use of sentry-react-native](https://github.com/expo/sentry-expo/issues/292#issuecomment-1521695389).
[As discussed I created a reproducible demo of a minimal setup using sentry-expo using a newer version of sentry-react-native](https://github.com/jongbelegen/sentry-expo-minimal). You can see the steps that I took to create this demo on the repo.
It also consists of builds and source maps.

I also made the expo config compatible with the new sentry version. You can see those changes [here](https://github.com/expo/sentry-expo/compare/main...jongbelegen:sentry-expo:fix/update-sentry-android-support)

This consisted of the following for ios:
- Use debug-files instead of upload-dsym
- Add /scripts/collect-modules.sh to the build phase

It would be awesome if we could make a version of sentry-expo with the latest version of Sentry that does not have the mono repo issues from the currently used version + all the new goodies you guys have been working on.

I'll do my best to get this merged upstream to sentry-expo as soon as we have figured out how to make everything work.

Thanks in advance!

**Comment by krystofwoldrich** [comment] 2023-05-12 16:47
Hi,
thank you for following up on the comment from `sentry-expo`, I'll try out the sample and let you know what have I found.

Also the upgrade to `@sentry/react-native@5` in `sentry-expo` looks good and we will be happy to help to make it work and get merged.

**Comment by krystofwoldrich** [comment] 2023-05-26 10:54
Hi,
following up on the sample app. Thank you for the detailed guide. 

I've successfully built the iOS app and got [a correctly symbolicated stack trace](https://krystofs-org.sentry.io/share/issue/0d3845c495eb4f6e8ae1061661775d6a/) as you did, plus Sentry UI doesn't show any error. 

I will test the Android soon.

**Comment by krystofwoldrich** [comment] 2023-06-02 10:11
I'm closing this for now, because I wasn't able to reproduce the issue. If there will be any new information/ideas we can reopen the issue.

Please look at the upgrade PR https://github.com/expo/sentry-expo/pull/337

**Closed by krystofwoldrich** 2023-06-02 10:11 UTC
Labels: Platform: React-Native, Team: Mobile Platform
