### ISSUE TITLE
[iOS] Upload Debug Symbols to Sentry

### ISSUE THREAD

**Issue by skinnynpale** [getsentry/sentry-react-native#3582] opened 2024-02-07 14:39 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.18.0

**`react-native` version:** 0.73.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

---
**I have the following issue:**

[Description]

**Steps to reproduce:**
- Step 1
- Step 2

**Actual result:**

The Sentry logging itself works fine, but when I enable upload  Upload Debug Symbols to project.pbxproj with a build in xcode 15.2 I get the error "Command PhaseScriptExecution failed with a nonzero exit code".
We use new arch + hermes

<img width="1308" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/52371356/1218a468-3f44-453e-aa5b-8178878b4d2c">
<img width="1232" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/52371356/6173fb69-21ed-4209-9a5a-c48d3857a3d9">
<img width="1236" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/52371356/112eb037-070d-4d5f-9b90-e767a3041afe">
<img width="1243" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/52371356/b9c5d043-b2c3-4dc6-a002-d0f4256cf5ed">

**Expected result:**

[Expected result]

**Comment by latobibor** [comment] 2024-02-08 05:22
On Android I have the same problem:
`Process 'command '/Users/XXX/XXX/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1`

**Comment by aliza-khu** [comment] 2024-02-08 05:31
What went wrong?

API request failed
  caused by: sentry reported an error: request failure (http status: 500)
  Object({"detail": String("Internal Error"), "errorId": String("xxx")})

**Comment by deepanshu-ample** [comment] 2024-02-08 07:09
error: API request failed
  caused by: sentry reported an error: request failure (http status: 500)
  Object {"detail": String("Internal Error"), "errorId": String("xxxx")}

* Where:
Script '.../app/node_modules/@sentry/react-native/sentry.gradle' line: 142

* What went wrong:
Execution failed for task ':app:bundleReleaseJsAndAssets_SentryUpload_com.app'.
Process 'command '.../app/node_modules/@sentry/cli/bin/sentry-cli'' finished with non-zero exit value 1

**Comment by pax-k** [comment] 2024-02-08 09:41
Same here, trying to build an iOS app on Expo. 

```
› Executing DevKin » Upload Debug Symbols to Sentry

❌  error: API request failed

⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » DevKin/DevKin » Build Phases » 'Upload Debug Symbols to Sentry'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/expo/Library/Developer/Xcode/DerivedData/DevKin-aczgjgpuztfeptgjumyzymjcejrl/Build/Intermediates.noindex/ArchiveIntermediates/DevKin/IntermediateBuildFilesPath/DevKin.build/Debug-iphoneos/DevKin.build/Script-50BEE7372E3D4B0A9587D43A.sh (in target 'DevKin' from project 'DevKin')
▸ (1 failure)
** ARCHIVE FAILED **
```

Yesterday was ok.

**Comment by aliza-khu** [comment] 2024-02-09 07:30
The issue is resolved now.

**Comment by aliza-khu** [comment] 2024-02-09 09:06
@skinnynpale, I am using CI/CD for build generation and only found an issue under the Android platform. For iOS it was already working.

**Comment by krystofwoldrich** [comment] 2024-02-09 11:25
Hello everyone,
we experienced a degradation of service on the file-based API yesterday, more information here https://status.sentry.io/incidents/5k3pjs416qnn.

Can anyone confirm the `500` API errors are not happening anymore?

**Comment by krystofwoldrich** [comment] 2024-02-09 11:28
@skinnynpale Thank you for the detailed screenshots of your changes. Everything is correct. 

Was your issue related to the `500` server response?

In case it wasn't could you add `export SENTRY_CLI_EXTRA_ARGS="--force-foreground --log-level=debug"` to your environment and share with us the log output of the build phase so we can investigate the issue?

**Comment by AlejandroGutierrezB** [comment] 2024-02-23 14:11
This is failing on my end to:
    "@sentry/react-native": "4.15.2",
    "expo": "~48.0.21",
    "react-native": "0.71.14",

**Comment by krystofwoldrich** [comment] 2024-02-23 15:39
Hi @AlejandroGutierrezB,
thank you for the message, are you getting a status 500 response?

**Comment by AlejandroGutierrezB** [comment] 2024-02-26 18:27
> Hi @AlejandroGutierrezB, thank you for the message, are you getting a status 500 response?

@krystofwoldrich the issue is that that is the only thing I get from the cli:

```
› Executing myapp » Upload Debug Symbols to Sentry

❌  error: API request failed

CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
CommandError: Failed to build iOS project. "xcodebuild" exited with error code 65.
    at Object.buildAsync (/user/myapp/node_modules/@expo/cli/build/src/run/ios/XcodeBuild.js:241:19)
    at async runIosAsync (/user/myappnode_modules/@expo/cli/build/src/run/ios/runIosAsync.js:56:25)
   
```

**Comment by krystofwoldrich** [comment] 2024-02-27 14:59
The failing API requests were caused by https://status.sentry.io/incidents/bt27tt1h1wsd

The incident was resolved. Uploads are working.

We will close the issue. Feel free to comment here in case this happens again.

**Closed by krystofwoldrich** 2024-02-27 14:59 UTC
Labels: Platform: React-Native, Waiting for: Product Owner

**Comment by coopersamuel** [comment] 2024-04-24 07:49
Hello @krystofwoldrich, I think I'm running into this issue. Could there have been a regression?

Expo EAS build is failing both on the EAS server and locally. It _does_ work, however, when I pass `SENTRY_ALLOW_FAILURE=true` as an env var. Here is a screenshot of my build logs (without the added env var). Any help would be appreciated!

<img width="1146" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/31891454/d9c65d8a-4a09-4ade-9921-f7f723b11c5e">

**Comment by appsgenie** [comment] 2024-05-11 23:14
I've also just received this error that @coopersamuel reported, building with Expos EAS and SDK 49.
Does anyone know how to fix this?

**Comment by anshul-flyfin** [comment] 2024-05-12 06:59
@krystofwoldrich this issue seems to be happening again can confirm if there is a regression ?

```
error: API request failed
  caused by: sentry reported an error: request failure (http status: 500)
  Object {"detail": String("Internal Error"), "errorId": String("eb2d2943a6404dfd99c16faff66e30b3")}

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.

GenerateDSYMFile /Users/runner/Library/Developer/Xcode/DerivedData/flyfinApp-ghsymviuejdlwkgwtreqwuzdlnvh/Build/Intermediates.noindex/ArchiveIntermediates/flyfinApp-org-production/BuildProductsPath/Org\ Production\ Release-iphoneos/FlyFin.app.dSYM /Users/runner/Library/Developer/Xcode/DerivedData/flyfinApp-ghsymviuejdlwkgwtreqwuzdlnvh/Build/Intermediates.noindex/ArchiveIntermediates/flyfinApp-org-production/InstallationBuildProductsLocation/Applications/FlyFin.app/FlyFin (in target 'flyfinApp' from project 'flyfinApp')
    cd /Users/runner/work/1/s/ios
    /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/runner/Library/Developer/Xcode/DerivedData/flyfinApp-ghsymviuejdlwkgwtreqwuzdlnvh/Build/Intermediates.noindex/ArchiveIntermediates/flyfinApp-org-production/InstallationBuildProductsLocation/Applications/FlyFin.app/FlyFin -o /Users/runner/Library/Developer/Xcode/DerivedData/flyfinApp-ghsymviuejdlwkgwtreqwuzdlnvh/Build/Intermediates.noindex/ArchiveIntermediates/flyfinApp-org-production/BuildProductsPath/Org\ Production\ Release-iphoneos/FlyFin.app.dSYM

warning: Run script build phase 'Start Packager' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'flyfinApp' from project 'flyfinApp')
warning: Run script build phase 'Bundle React Native code and images' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'flyfinApp' from project 'flyfinApp')
warning: Run script build phase 'Upload Debug Symbols to Sentry' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'flyfinApp' from project 'flyfinApp')
warning: Run script build phase '[CP-User] [RNFB] Core Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'flyfinApp' from project 'flyfinApp')
warning: Run script build phase '[CP-User] [RNFB] Crashlytics Configuration' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'flyfinApp' from project 'flyfinApp')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'fmt' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-bridging' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'React-Codegen' from project 'Pods')
warning: Run script build phase 'Create Symlinks to Header Folders' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'RCT-Folly' from project 'Pods')
** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Upload\ Debug\ Symbols\ to\ Sentry /Users/runner/Library/Developer/Xcode/DerivedData/flyfinApp-ghsymviuejdlwkgwtreqwuzdlnvh/Build/Intermediates.noindex/ArchiveIntermediates/flyfinApp-org-production/IntermediateBuildFilesPath/flyfinApp.build/Org\ Production\ Release-iphoneos/flyfinApp.build/Script-13606D41F60548F7B47E3F63.sh (in target 'flyfinApp' from project 'flyfinApp')
(1 failure)
##[error]Error: /usr/bin/xcodebuild failed with return code: 65
```

**Comment by coopersamuel** [comment] 2024-05-13 19:43
I was able to fix it on my end. My build process was not pulling my `SENTRY_AUTH_TOKEN` in properly. Make sure your build is providing the token correctly

**Comment by appsgenie** [comment] 2024-05-14 22:33
I was able to build once, not sure if it was just a retry or an updated token, but now I am getting `A required debug information file was missing`. Did you get this issue as well @coopersamuel?

**Comment by charlestbell** [comment] 2024-08-31 19:35
Happening again today.

**Comment by sergioisidoro** [comment] 2024-09-18 22:45
I think it is quite unacceptable that a service makes uploading the source code and symbols (a non critical task) fail the entire build if the step fails. The same happens if some error like `Project not found. Please check that you entered the project and organization slugs correctly.` 

It's effectively making thousands of build processes dependent on Sentry's service availability.

This should be a warning, not a failure, or should be `SENTRY_ABORT_BUILD_IF_FAIL` or something similar.
