### ISSUE TITLE
[Expo, iOS] When native enabled events are not sent

### ISSUE THREAD

**Issue by timmyjose** [getsentry/sentry-react-native#3961] opened 2024-07-22 10:03 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** **~5.22.0**

**`react-native` version:** **0.74.3**

**Are you using Expo?**
- [x]  Yes (CNG - Continuous Native Generation, `android` and `ios` directories in version control, previously called "bare" workflow).
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:** **N/A**

**Configuration:**

(`@sentry/react-native`)
```
import { getVersion, getBuildNumber } from 'react-native-device-info'
...

Sentry.init({
  dsn: SENTRY_DSN,
  environment: ENV_NAME,
  normalizeDepth: 7,
  integrations: [
    new Sentry.ReactNativeTracing({
      enableAppStartTracking: false
    })
  ],
  enabled: !__DEV__,
  enableNative: Platform.OS === 'android',
  enableNativeCrashHandling: Platform.OS === 'android',
  release: `${getVersion()} (${getBuildNumber()})`, // workaround because of the current issue
  dist: getBuildNumber(), // workaround because of the current issue
  ignoreErrors: [/network-error error/]
})

```

**I have the following issue:**

Two issues. possibly both related to the same underlying issue.

**Main issue**:  If `enableNative: true`, then notifications are **not** sent for `iOS`. No error logs.
**Secondary Issue**: No Device Information coming through for `iOS`. (Possibly related to the main issue?)

**Steps to reproduce:** N/A (possibly project-specific since the setup works in an `expo` 51 prototype).

Some possibly helpful information:

**Logs** (with `debug: true`:

No errors in logs.

```
 LOG  Sentry Logger [log]: Unhandled promise rejections will be caught by Sentry.
 LOG  Sentry Logger [log]: Integration installed: ReactNativeErrorHandlers
 LOG  Sentry Logger [log]: Integration installed: NativeLinkedErrors
 LOG  Sentry Logger [log]: Integration installed: InboundFilters
 LOG  Sentry Logger [log]: Integration installed: FunctionToString
 LOG  Sentry Logger [log]: Integration installed: Breadcrumbs
 LOG  Sentry Logger [log]: Integration installed: Dedupe
 LOG  Sentry Logger [log]: Integration installed: HttpContext
 LOG  Sentry Logger [log]: Integration installed: Release
 LOG  Sentry Logger [log]: Integration installed: EventOrigin
 LOG  Sentry Logger [log]: Integration installed: SdkInfo
 LOG  Sentry Logger [log]: Integration installed: ReactNativeInfo
 LOG  Sentry Logger [log]: Integration installed: DebugSymbolicator
 LOG  Sentry Logger [log]: Integration installed: RewriteFrames
 LOG  Sentry Logger [log]: Integration installed: DeviceContext
 LOG  Sentry Logger [log]: Integration installed: ModulesLoader
 LOG  Sentry Logger [log]: [ReactNativeTracing] Native frames instrumentation initialized.
 LOG  Sentry Logger [log]: [ReactNativeTracing] Not instrumenting route changes as routingInstrumentation has not been set.
 LOG  Sentry Logger [log]: Integration installed: ReactNativeTracing
 LOG  Sentry Logger [log]: Integration installed: ReactNativeProfiler

....

 LOG  Sentry Logger [log]: [TouchEvents] Touch event within element: TextInput
 LOG  Sentry Logger [log]: [ReactNativeTracing] User Interaction Tracing is disabled
```

**Is Native SDK initialised?**

If I try with this code:

```
Sentry.init({
   ...
   onReady: ({ didCallNativeInit}) => {
     if (didCallNativeInit) {
       console.log('Native SDK initialised successfully')
   }
   ...
}
```

then I see that the native SDK was initialised correctly.

[sentry.json](https://github.com/user-attachments/files/16331334/sentry.json)

**Is auto-linking happening?**

Yes:

```
Auto-linking React Native modules for target `<redacted>`: RNCAsyncStorage, RNDeviceInfo, RNFBApp, RNFBMessaging, RNGestureHandler, RNLocalize, RNNotifee, RNSVG, RNScreens, RNSentry, react-native-cloud-storage, react-native-compat, react-native-get-random-values, react-native-netinfo, react-native-quick-base64, react-native-rust-bridge, and react-native-safe-area-context
```

**Is notification packet captured in `beforeSend`?**

Yes. Please see the attachment, `sentry.json`.

**Actual result:**

* If `enableNative: true`, then **no** notifications sent for `iOS`.
* No Device Information available for `iOS` notifications . 

**Expected result:**

* `enableNative: true` works for `iOS`, and we get notifications in the `Sentry` dashboard.
* Device Information is available for `iOS` notifications.

**Comment by kahest** [comment] 2024-07-22 13:31
Thank you @timmyjose for the detailed report! We'll take a look and get back to you - due to PTOs and such we might take a few days though.

And to clarify 
> Secondary Issue: No Device Information coming through for iOS. (Possibly related to the main issue?)

does this only happen if you deactivate native? (i.e. `enableNative: Platform.OS === 'android',` on iOS would resolve to false)
if you do that, I would expect ` LOG  Sentry Logger [log]: Integration installed: DeviceContext` not to show up on the logs as well

**Comment by timmyjose** [comment] 2024-07-22 13:38
@kahest Thank you! And, yes, the configuration is the same: `enableNative: Platform.OS === 'android'`. 

About that specific log entry, let me check and get back to you on that. It is quite possible that I might have been trying both `iOS` and `Android` for comparison.

**Comment by timmyjose** [comment] 2024-07-23 06:26
@kahest Sorry for the delay. I tested both scenarios, and here are the findings:

With `enableNative: Platform.OS === 'android'`:

```
 WARN  Sentry Logger [warn]: Note: Native Sentry SDK is disabled. // @timmyjose - this makes sense to me since it's disabled for `iOS`
 LOG  Sentry Logger [log]: Unhandled promise rejections will be caught by Sentry.
 LOG  Sentry Logger [log]: Integration installed: ReactNativeErrorHandlers
 LOG  Sentry Logger [log]: Integration installed: NativeLinkedErrors
 LOG  Sentry Logger [log]: Integration installed: InboundFilters
 LOG  Sentry Logger [log]: Integration installed: FunctionToString
 LOG  Sentry Logger [log]: Integration installed: Breadcrumbs
 LOG  Sentry Logger [log]: Integration installed: Dedupe
 LOG  Sentry Logger [log]: Integration installed: HttpContext
 LOG  Sentry Logger [log]: Integration installed: Release
 LOG  Sentry Logger [log]: Integration installed: EventOrigin
 LOG  Sentry Logger [log]: Integration installed: SdkInfo
 LOG  Sentry Logger [log]: Integration installed: ReactNativeInfo
 LOG  Sentry Logger [log]: Integration installed: DebugSymbolicator
 LOG  Sentry Logger [log]: Integration installed: RewriteFrames
 WARN  Sentry Logger [warn]: [ReactNativeTracing] NativeFramesTracking is not available on the Web, Expo Go and other platforms without native modules.
 LOG  Sentry Logger [log]: [ReactNativeTracing] Not instrumenting route changes as routingInstrumentation has not been set.
 LOG  Sentry Logger [log]: Integration installed: ReactNativeTracing
 LOG  Sentry Logger [log]: Integration installed: ReactNativeProfiler
 LOG  Sentry Logger [log]: Integration installed: TouchEventBoundary

```

With `enableNative: true`:


 ```
 LOG  Sentry Logger [log]: Unhandled promise rejections will be caught by Sentry.
 LOG  Sentry Logger [log]: Integration installed: ReactNativeErrorHandlers
 LOG  Sentry Logger [log]: Integration installed: NativeLinkedErrors
 LOG  Sentry Logger [log]: Integration installed: InboundFilters
 LOG  Sentry Logger [log]: Integration installed: FunctionToString
 LOG  Sentry Logger [log]: Integration installed: Breadcrumbs
 LOG  Sentry Logger [log]: Integration installed: Dedupe
 LOG  Sentry Logger [log]: Integration installed: HttpContext
 LOG  Sentry Logger [log]: Integration installed: Release
 LOG  Sentry Logger [log]: Integration installed: EventOrigin
 LOG  Sentry Logger [log]: Integration installed: SdkInfo
 LOG  Sentry Logger [log]: Integration installed: ReactNativeInfo
 LOG  Sentry Logger [log]: Integration installed: DebugSymbolicator
 LOG  Sentry Logger [log]: Integration installed: RewriteFrames
 LOG  Sentry Logger [log]: Integration installed: DeviceContext
 LOG  Sentry Logger [log]: Integration installed: ModulesLoader
 LOG  Sentry Logger [log]: [ReactNativeTracing] Native frames instrumentation initialized.
 LOG  Sentry Logger [log]: [ReactNativeTracing] Not instrumenting route changes as routingInstrumentation has not been set.
 LOG  Sentry Logger [log]: Integration installed: ReactNativeTracing
 LOG  Sentry Logger [log]: Integration installed: ReactNativeProfiler
 LOG  Sentry Logger [log]: Integration installed: TouchEventBoundary```

```

and when I trigger an action that should send a notification (from what I can tell, unrelated warnings?):

```
 LOG  Sentry Logger [log]: [TouchEvents] Touch event within element: Text
 LOG  Sentry Logger [log]: [ReactNativeTracing] User Interaction Tracing is disabled.
 LOG  Sentry Logger [log]: [TouchEvents] Touch event within element: Text
 LOG  Sentry Logger [log]: [ReactNativeTracing] User Interaction Tracing is disabled.
 LOG  Sentry Logger [log]: [TouchEvents] Touch event within element: Text
 LOG  Sentry Logger [log]: [ReactNativeTracing] User Interaction Tracing is disabled.
 LOG  Sentry Logger [log]: [TouchEvents] Touch event within element: Text
 LOG  Sentry Logger [log]: [ReactNativeTracing] User Interaction Tracing is disabled

```

**Comment by kahest** [comment] 2024-07-23 07:35
@timmyjose thanks for the detailed tests! This confirms one thing - you don't get device information on iOS because/when `enableNative` is false on iOS (see the first log missing `DeviceContext` integration).

The error you get on notification if native is disabled seems strange though, we need to look into that. Can you confirm that "Upon triggering an action that should send a notification:" means you send a Push Notification to the app?

**Comment by timmyjose** [comment] 2024-07-23 09:32
@kahest 

> The error you get on notification if native is disabled seems strange though, we need to look into that. Can you confirm that "Upon triggering an action that should send a notification:" means you send a Push Notification to the app?

This specific operation triggers a `Sentry.captureMessage` with some diagnostic data that we collect for the user. Another manual operation is done via `Sentry.captureException` as well. 

Not to confuse matters more, but the same init code with `enableNative: Platform.OS === 'android'` does send `iOS` notifications with the deprecated `sentry-expo` library (`expo`-49). Now that we have updated to `expo` 51 (which uses only  the `@sentry/react-native` package), we see this behaviour.

**Comment by timmyjose** [comment] 2024-07-23 09:34
Also, the attached `sentry.json` file is around 62KB. That shouldn't be a factor though, I suppose? (Since `Android` is sending it just fine?). Thanks for helping out with this, @kahest. Appreciate it!

**Comment by kahest** [comment] 2024-07-23 09:54
Got it - your `captureMessage` (and `captureException`) are not sent when `enableNative=true` on iOS, even though the events apparently go through `beforeSend` and you don't see a warning/error in the debug log. We'll investigate this.

> Also, the attached sentry.json file (...) is around 62KB. That shouldn't be a factor though, I suppose?

Correct, that's rather slim actually. :)

**Comment by timmyjose** [comment] 2024-07-23 12:56
> Got it - your `captureMessage` (and `captureException`) are not sent when `enableNative=true` on iOS, even though the events apparently go through `beforeSend` and you don't see a warning/error in the debug log. We'll investigate this.
> 
> > Also, the attached sentry.json file (...) is around 62KB. That shouldn't be a factor though, I suppose?
> 
> Correct, that's rather slim actually. :)

Hahaha, nice! 🙂

**Comment by krystofwoldrich** [comment] 2024-08-01 11:50
@timmyjose thank you for all the details, logs and code snippets.

Since there are no error in JS when native enabled on iOS, let's focus on the Xcode project. 

---

Could you share what pod version of RNSentry and Sentry are installed via CocoaPods? 

The RNSentry version should be the same as the JS package (`@sentry/react-native`) version.

---

When `enableNative=true` and `debug=true`, could you share output of the iOS Console? You can find it in Xcode.

![Image](https://github.com/user-attachments/assets/4cdb2861-4079-463f-8802-f5583e13abdf)

---

Have you tried to regenerate the Xcode project? Using `npx expo prebuild --clean`?

**Comment by timmyjose** [comment] 2024-08-03 13:52
Hey @krystofwoldrich, sorry for the delayed response (I missed seeing the GitHub notification!).

Here's the data that you asked for.

> Could you share what pod version of RNSentry and Sentry are installed via CocoaPods?

```
In `package.json`: 

    "@sentry/react-native": "~5.22.0",

In `Podfile.lock`:

  - RNSentry (5.22.3):
    - hermes-engine
    - React-Core
    - React-hermes
    - Sentry/HybridSDK (= 8.26.0)

  - Sentry/HybridSDK (8.26.0)
```

> Xcode Console output

With the following configuration:

```
Sentry.init({
  dsn: SENTRY_DSN,
  environment: ENV_NAME,
  normalizeDepth: 7,
  integrations: [
    new Sentry.ReactNativeTracing({
      enableAppStartTracking: false
    })
  ],
  enabled: true,
  // enabled: !__DEV__,
  debug: true,
  enableNative: true,
  // enableNative: Platform.OS === 'android',
  enableNativeCrashHandling: Platform.OS === 'android',
  release: `${getVersion()} (${getBuildNumber()})`,
  dist: getBuildNumber(),
  ignoreErrors: [/network-error error/]
})

```

Please see the attached file for the `Xcode` console output (output contains data from a manual trigger of an action which does `Sentry.captureMessage` as well).

> Have you tried to regenerate the Xcode project? Using npx expo prebuild --clean?

Yes, we actually have the `ios` and `android` direct

[xcode_console.txt](https://github.com/user-attachments/files/16480779/xcode_console.txt)

ories in `.gitignore` - we generate them using `prebuild` on every build. What `expo` calls CNG (Continuous Native Generation).

Hope that this helps narrow down the issue further!

**Comment by krystofwoldrich** [comment] 2024-08-05 08:49
@timmyjose Thank you for the extra data, I'll take a look and hopefully it will narrow down the investigation.

**Comment by timmyjose** [comment] 2024-08-23 12:28
Hey @krystofwoldrich, any idea where the issue might be? If you need more information from my side, please do let me know. I'd be glad to provide any further details!

**Comment by krystofwoldrich** [comment] 2024-08-26 15:26
Hi @timmyjose,
from the logs it looks like the Native `sentry-cocoa` sends the envelopes as expected. 

Related message and code. https://github.com/getsentry/sentry-cocoa/blob/379ff2adeef7ee64a171bcff990561b9075495b8/Sources/Sentry/SentryHttpTransport.m#L324

Sadly, I don't see anything suspicious in the logs.

**Comment by krystofwoldrich** [comment] 2024-08-26 15:27
@brustolin Do you see any reason why envelope would not be sent in the [logs](https://github.com/user-attachments/files/16480779/xcode_console.txt)?

**Comment by timmyjose** [comment] 2024-08-26 16:21
Thank you for the update, @krystofwoldrich. Yes, this appears to be something insidious, and probably related to the payload our app is sending and/or the size (?). It's quite bizarre.

**Comment by brustolin** [comment] 2024-08-27 06:54
>@brustolin Do you see any reason why envelope would not be sent in the [logs](https://github.com/user-attachments/files/16480779/xcode_console.txt)?

I can't find any problem related to envelopes in the log

**Comment by timmyjose** [comment] 2024-08-29 09:39
Folks, really appreciate the work you're doing. If there's any data needed from my side/anything you wish me to try out, I'll be happy to furnish the same!

**Comment by krystofwoldrich** [comment] 2024-08-30 11:50
@timmyjose If there would be even smallest change to reproduce this in a new app that would be the best, but I understand that the chances are small.

Although there is no error in the logs it might be a network issue, so it might be worth investigating the outgoing requests and verifying the envelope is being sent.

The second thing I would try is to start the application with debugger nad add breakpoint before:

```
[Sentry] [debug] [SentryFileManager:57] Successfully deleted file at /Users/timmyjose/Library/Developer/CoreSimulator/Devices/D9C5195D-C4A4-4A60-BF0C-A840D6F1B0B8/data/Containers/Data/Application/7451903B-83F1-4F1B-8042-4E643F00CA16/Library/Caches/io.sentry/abd9c5869c71332261e477d1e8f1bf93f8aaaff5/envelopes/1722692325.394499-00001-C8342FBE-81CE-426B-B2A3-2B189B70C990.json
```

then you can locate the envelope and check if it will be accepted by Sentry backend using.

```
sentry-cli send-envelope path/to/envelope
```

**Comment by timmyjose** [comment] 2024-08-30 12:47
@krystofwoldrich Thank you for the actionable items! I'll try them out and get back with findings.

**Comment by krystofwoldrich** [comment] 2024-09-12 12:16
I'll close this for now, as there are no step on our side.

Please comment here when the state changes, we can reopen the issue at any time.

**Closed by krystofwoldrich** 2024-09-12 12:16 UTC
Labels: Platform: React-Native, iOS, Waiting for: Community, Expo
