### ISSUE TITLE
node_modules/@sentry/cli/sentry-cli: cannot execute binary file in macOS CI environment

### ISSUE THREAD

**Issue by matt-dalton** [getsentry/sentry-react-native#2445] opened 2022-09-01 08:27 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.2.4

**`react-native` version:** 0.63.4

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**
N/A

**Configuration:**
Sentry init config not relevant

Xcode bundle command: `export NODE_BINARY="$(which node)"
../node_modules/@sentry/cli/bin/sentry-cli react-native xcode ../node_modules/react-native/scripts/react-native-xcode.sh`

---
**I have following issue:**
I am using a circleCI node image (`circleci/node`) to install my dependencies (using `yarn install`), plus run JS tests.

To build/deploy through fastlane, I then need to use a macOS image (`macos.x86.medium.gen2`).

This mac step is failing on any step where it runs the sentry-cli with:
`/Users/distiller/myapp/node_modules/@sentry/cli/sentry-cli: cannot execute binary file`

If I ssh into the instance I can recreate the issue by trying to run the CLI. I have tried changing permissions/ownership, and it doesn't fix the problem. The only thing that seems to work is running `yarn install` again in the macOS environment

I presume the sentry react native library is running some kind of postinstall script to install the correct CLI binary for the environment. Is there a way I can just run this script, or just run the sentry postinstall scripts, to avoid having to run the whole yarn install process?
Or is there a more elegant way I should handle this?

**Comment by krystofwoldrich** [comment] 2022-09-06 12:36
I don't think you need to run whole `yarn install`, but installing only the CLI should be enough. Just be careful to install the correct version, that is specified in the version of React Native SDK you are using.

For example for RN `4.24`:
```bash
yarn install @sentry/cli@1.74.4
```

I haven't tried it my self, but I would expect that the trouble is caused by running the install on Linux and then executing the binary on macOS.

**Comment by matt-dalton** [comment] 2022-09-06 14:46
> I don't think you need to run whole `yarn install`, but installing only the CLI should be enough. Just be careful to install the correct version, that is specified in the version of React Native SDK you are using.
> 
> For example for RN `4.24`:
> 
> ```shell
> yarn install @sentry/cli@1.74.4
> ```
> 
> I haven't tried it my self, but I would expect that the trouble is caused by running the install on Linux and then executing the binary on macOS.

yeah true...i guess i then have to be careful to maintain my package.json file at the same version as my circleCI version. but would save time for sure.

**Comment by marandaneto** [comment] 2022-09-06 15:09
`sentry-cli` has specific binaries per platform so you either install it again or install the CLI standalone and run it manually, apparently, you can do that already.
Should we close this issue?

**Comment by marandaneto** [comment] 2022-09-15 08:19
Closing the issue as a part of large repository cleanup, due to it being inactive and/or outdated. There's a large chance that this issue has been solved since.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Closed by marandaneto** 2022-09-15 08:19 UTC
Labels: Status: Awaiting Response, Platform: React-Native
