### ISSUE TITLE
JS Error is reported as Java Exception

### ISSUE THREAD

**Issue by fantasyado** [getsentry/sentry-react-native#3078] opened 2023-05-18 10:29 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (5.5.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 0.0.0

**`react-native` version:** 0.70.5

**Are you using Expo?**
- [x]  Yes -- bare flow
- [ ]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://aspiraconnect.sentry.io/issues/4191461462/?alert_rule_id=1038348&alert_timestamp=1684404390608&alert_type=email&environment=production&project=5174057&referrer=alert_email)

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
  enabled: !__DEV__
});
```

---
**I have following issue:**

[Description]

**Steps to reproduce:**
- run xcode build script 
   ``` 
    xcodebuild -workspace $schemeName.xcworkspace   -scheme $schemeName -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.1'  
  ```
- install the ipa to simulator and trigger a error

**Actual result:**

[Actual result]
The source map seems not used to display the error source code location.
<img width="699" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/10321851/f19b1895-5baa-4d3e-80ad-86d2e2e03402">
and when I check the sourceMaps tab in sentry.io it shows no  bundle connected to this release

<img width="836" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/10321851/0190793a-a789-4f73-b0e8-457da33f21f9">

**Expected result:**

[Expected result]
The source map should be used to parse the error stacktrace.

Please help on this, Thanks !

**Comment by fantasyado** [comment] 2023-05-19 07:28
update:   after I set release and dist in Sentry.init and doing 
```
export SENTRY_ORG=my-org
export SENTRY_PROJECT=my-project 
```
in the build script , the source map uploading seems normal on sentry like this 
<img width="929" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/10321851/7affc737-79bd-4249-a2e6-559d215bbdbf">
but the issue detail still not showing method name and a warning popped up: 
<img width="767" alt="image" src="https://github.com/getsentry/sentry-react-native/assets/10321851/c8cbbe0f-8a7d-41dc-bc1d-47c359b903e4">

[issue link](https://aspiraconnect.sentry.io/issues/4193501052/?project=5592094&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)

tried both jsc and hermes and both are same result.

**Comment by krystofwoldrich** [comment] 2023-05-19 08:12
Hi,
thank you for the link and details. It looks like you are using bare `@sentry/react-native`, so you will have to add the following integration to match the bundle name with the uploaded artifacts name.

```js
Sentry.init({
  integrations: [
    new RewriteFrames({
      iteratee: (frame) => {
        if (frame.filename && frame.filename !== '[native code]') {
          frame.filename =
            Platform.OS === 'android' ? 'app:///index.android.bundle' : 'app:///main.jsbundle';
        }
        return frame;
      },
    }),
  ]
})
```

This code is added by the [`sentry-expo` automatically](https://github.com/expo/sentry-expo/blob/689f78092da814557e2e268e24bc0bac8366f969/src/sentry.ts#L62).

**Comment by fantasyado** [comment] 2023-05-19 10:20
@krystofwoldrich Thanks very much for your reply.  after I added the integrations option to Sentry.init, iOS seems working fine now but Android is still not.  one thing I noticed is when I run the iOS build, the source map appeared on both tabs (Artifact Bundles, release-bundles) but Android only appeared in release-bundles with warning.

Besides, Android build speed is much faster than iOS, during the build process I didn't see too much upload traffic but it can be observed during iOS build process.

Is there any other settings I am missing?

**Comment by krystofwoldrich** [comment] 2023-05-23 09:51
I'm happy to hear that it helped a bit. A assume both the iOS and Android errors use the same JS code?

The issue from Android is a Java exception with JS stack trace in its message. Sentry doesn't symbolicate the message content.

We handle this case [here](https://github.com/getsentry/sentry-react-native/blob/5a0dac7e9227193ee0154c1a651252b3af32457b/android/src/main/java/io/sentry/react/RNSentryModuleImpl.java#L196). Are you initializing `SentryAndroid` manually?

**Comment by fantasyado** [comment] 2023-05-29 02:16
@krystofwoldrich You are right, both the iOS and Android errors use the same JS code and I did not initialize SentryAndroid manually.  what I have done is init sentry with release and dist and export same release/dist env var in build script.

**Comment by krystofwoldrich** [comment] 2023-05-30 07:50
Would you be able to share a minimal reproducible example for the Android JavascriptException? As I mentioned you should get JS Error but you are getting Java Exception.

**Comment by fantasyado** [comment] 2023-06-01 02:27
OK， I‘ll try to create a minimal example when I got time. currently cause we also need to integrate with codepush, we'll upload the source map manually anyway.

**Comment by krystofwoldrich** [comment] 2023-06-16 11:16
Closing as duplicate of https://github.com/getsentry/sentry-react-native/issues/3126

**Closed by krystofwoldrich** 2023-06-16 11:16 UTC
Labels: Status: Awaiting Response, Platform: React-Native
