### ISSUE TITLE
Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by genesiscz** [getsentry/sentry-react-native#3442] opened 2023-11-30 16:56 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 5.14.0))

**SDK version:** 5.14.1

**`react-native` version:** 0.72.6

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
import * as Sentry from "@sentry/react-native";
Sentry.init({
	dsn: Config.SENTRY_DSN,
	environment: Config.APP_ENV,
});

export const AppWithSentry = Sentry.wrap(App);
```

---
**I have the following issue:**

After upgrading versions of sentry (@sentry/react ^7.80.0 (from 7.80.0 to 7.81.1), @sentry/react-native ^5.13.0 (from 5.13.0 to 5.14.1)), I started gettting this error

![image](https://github.com/getsentry/sentry-react-native/assets/1512353/5f5ce80f-f40e-4690-8ab1-bf1af1e73928)

And this in console:
```
 ERROR  TypeError: Cannot read property 'prototype' of undefined, js engine: hermes
 ERROR  TypeError: Cannot read property 'AppWithSentry' of undefined, js engine: hermes
```
I feel like it's something wrong with the breadcrumbs in `@sentry/browser` and I am not sure where to place this error, if getsentry/sentry-reace-native or getsentry/sentry-javascript. 

Just to elaborate, these are the versions I have in my yarn.lock file (and I hope sentry/cli has nothing to do with this :-))

```

"@sentry-internal/tracing@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry-internal/tracing/-/tracing-7.81.1.tgz#1180365cd8a9e18cb0f92e1ea970161840ec0e2e"
  integrity sha512-E5xm27xrLXL10knH2EWDQsQYh5nb4SxxZzJ3sJwDGG9XGKzBdlp20UUhKqx00wixooVX9uCj3e4Jg8SvNB1hKg==
  dependencies:
    "@sentry/core" "7.81.1"
    "@sentry/types" "7.81.1"
    "@sentry/utils" "7.81.1"

"@sentry-internal/tracing@7.84.0":
  version "7.84.0"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry-internal/tracing/-/tracing-7.84.0.tgz#430da253ee5b075be4ef57f20ea842c0208bc6b0"
  integrity sha512-y9bGYA0OM6PEREfd+nk4UURZy29tpIw+7vQwpxWfEVs2fqq0/5TBFX/tKFb8AKUI9lVM8v0bcF0bNSCnuPQZHQ==
  dependencies:
    "@sentry/core" "7.84.0"
    "@sentry/types" "7.84.0"
    "@sentry/utils" "7.84.0"

"@sentry/browser@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/browser/-/browser-7.81.1.tgz#5ee6ae3679ee80f444d2e8c5662430e7a734ae50"
  integrity sha512-DNtS7bZEnFPKVoGazKs5wHoWC0FwsOFOOMNeDvEfouUqKKbjO7+RDHbr7H6Bo83zX4qmZWRBf8V+3n3YPIiJFw==
  dependencies:
    "@sentry-internal/tracing" "7.81.1"
    "@sentry/core" "7.81.1"
    "@sentry/replay" "7.81.1"
    "@sentry/types" "7.81.1"
    "@sentry/utils" "7.81.1"

"@sentry/browser@7.84.0":
  version "7.84.0"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/browser/-/browser-7.84.0.tgz#7c82470f0afbb6178f26127894e40e9ce2b1e6d6"
  integrity sha512-X50TlTKY9WzAnHsYc4FYrCWgm+CdVo0h02ggmodVBUpRLUBjj+cs5Q1plov/v/XeorSwmorNEMUu/n+XZNSsrA==
  dependencies:
    "@sentry-internal/tracing" "7.84.0"
    "@sentry/core" "7.84.0"
    "@sentry/replay" "7.84.0"
    "@sentry/types" "7.84.0"
    "@sentry/utils" "7.84.0"

"@sentry/cli@1.74.6", "@sentry/cli@2.21.3":
  version "1.74.6"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/cli/-/cli-1.74.6.tgz#c4f276e52c6f5e8c8d692845a965988068ebc6f5"
  integrity sha512-pJ7JJgozyjKZSTjOGi86chIngZMLUlYt2HOog+OJn+WGvqEkVymu8m462j1DiXAnex9NspB4zLLNuZ/R6rTQHg==
  dependencies:
    https-proxy-agent "^5.0.0"
    mkdirp "^0.5.5"
    node-fetch "^2.6.7"
    npmlog "^4.1.2"
    progress "^2.0.3"
    proxy-from-env "^1.1.0"
    which "^2.0.2"

"@sentry/core@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/core/-/core-7.81.1.tgz#082fd9122bf9a488c8e05b1754724ddbc2d5cf30"
  integrity sha512-tU37yAmckOGCw/moWKSwekSCWWJP15O6luIq+u7wal22hE88F3Vc5Avo8SeF3upnPR+4ejaOFH+BJTr6bgrs6Q==
  dependencies:
    "@sentry/types" "7.81.1"
    "@sentry/utils" "7.81.1"

"@sentry/core@7.84.0":
  version "7.84.0"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/core/-/core-7.84.0.tgz#01d33fc452044ffd8ea57b20f60304b9cfa2b9e1"
  integrity sha512-tbuwunbBx2kSex15IHCqHDnrMfIlqPc6w/76fwkGqokz3oh9GSEGlLICwmBWL8AypWimUg13IDtFpD0TJTriWA==
  dependencies:
    "@sentry/types" "7.84.0"
    "@sentry/utils" "7.84.0"

"@sentry/hub@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/hub/-/hub-7.81.1.tgz#c49bcc1894bfeb019811bac8e3b6fd81011b6f7c"
  integrity sha512-25cvsI3HKiRLJBZGFC8ntuy7/yB8M1w8YLTjr3tIqydYmjFUX7f18w0iuWEtd204d8OQSPBJDapbGMdfkE5x6w==
  dependencies:
    "@sentry/core" "7.81.1"
    "@sentry/types" "7.81.1"
    "@sentry/utils" "7.81.1"

"@sentry/integrations@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/integrations/-/integrations-7.81.1.tgz#1b12c0cf3a7fa88224e86c0be46523ed7e3f3a43"
  integrity sha512-DN5ONn0/LX5HHVPf1EBGHFssIZaZmLgkqUIeMqCNYBpB4DiOrJANnGwTcWKDPphqhdPxjnPv9AGRLaU0PdvvZQ==
  dependencies:
    "@sentry/core" "7.81.1"
    "@sentry/types" "7.81.1"
    "@sentry/utils" "7.81.1"
    localforage "^1.8.1"

"@sentry/react-native@^5.2.0":
  version "5.14.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/react-native/-/react-native-5.14.1.tgz#a9e5ff933ebd87d6e3a34b0acca1adc9df29aa80"
  integrity sha512-qeQC72HMFJX7WEDF5rUT/8OZOkx64O6lZZWds8qGuwcDK0FeHBxt4IPJb6YGBTSW20q7mdK/c2hM8Q2ey13h2A==
  dependencies:
    "@sentry/browser" "7.81.1"
    "@sentry/cli" "2.21.3"
    "@sentry/core" "7.81.1"
    "@sentry/hub" "7.81.1"
    "@sentry/integrations" "7.81.1"
    "@sentry/react" "7.81.1"
    "@sentry/types" "7.81.1"
    "@sentry/utils" "7.81.1"

"@sentry/react@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/react/-/react-7.81.1.tgz#6a94e8e373a5bf27330cea2eb1a603ae0eb0b8ba"
  integrity sha512-kk0plP/mf8KgVLOiImIpp1liYysmh3Un8uXcVAToomSuHZPGanelFAdP0XhY+0HlWU9KIfxTjhMte1iSwQ8pYw==
  dependencies:
    "@sentry/browser" "7.81.1"
    "@sentry/types" "7.81.1"
    "@sentry/utils" "7.81.1"
    hoist-non-react-statics "^3.3.2"

"@sentry/react@^7.23.0":
  version "7.84.0"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/react/-/react-7.84.0.tgz#2cb3192f7fb67b7696e8ece08d67229b193ddaa4"
  integrity sha512-VQZrEHwPKCYTSbRYXD2ohXcQg99G1Hgs8eevRUuRpdChmA2e3z/RvT00NlaSNNZrS86wPyKpAK6kickB/eSYrw==
  dependencies:
    "@sentry/browser" "7.84.0"
    "@sentry/types" "7.84.0"
    "@sentry/utils" "7.84.0"
    hoist-non-react-statics "^3.3.2"

"@sentry/replay@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/replay/-/replay-7.81.1.tgz#a656d55e2a00b34e42be6eeb79018d21efc223af"
  integrity sha512-4ueT0C4bYjngN/9p0fEYH10dTMLovHyk9HxJ6zSTgePvGVexhg+cSEHXisoBDwHeRZVnbIvsVM0NA7rmEDXJJw==
  dependencies:
    "@sentry-internal/tracing" "7.81.1"
    "@sentry/core" "7.81.1"
    "@sentry/types" "7.81.1"
    "@sentry/utils" "7.81.1"

"@sentry/replay@7.84.0":
  version "7.84.0"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/replay/-/replay-7.84.0.tgz#7e17876d9a1802ee33800e2b2cbda4e026c0a2af"
  integrity sha512-c4PxT0ZpvkR9zXNfmAk3ojkm6eZ9+NlDze09RFBOCNo69QwIN90hnvbjXFC1+vRIJsfgo78Zr0ya/Wzb3Rog7Q==
  dependencies:
    "@sentry-internal/tracing" "7.84.0"
    "@sentry/core" "7.84.0"
    "@sentry/types" "7.84.0"
    "@sentry/utils" "7.84.0"

"@sentry/tracing@^7.23.0":
  version "7.84.0"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/tracing/-/tracing-7.84.0.tgz#64fbd93ed771f8e19fb60b06968cc133e3c82ea0"
  integrity sha512-NhBX28vUmCu/5avyGKX6B4UTm4MTOfbdg9ZzCnS7hPuWDfEAUIVHZVryi2q8bqp2DNGJvS9qIq/TSf39JIpdJg==
  dependencies:
    "@sentry-internal/tracing" "7.84.0"

"@sentry/types@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/types/-/types-7.81.1.tgz#2b2551fc291e1089651fd574a68f7c4175878bd5"
  integrity sha512-dvJvGyctiaPMIQqa46k56Re5IODWMDxiHJ1UjBs/WYDLrmWFPGrEbyJ8w8CYLhYA+7qqrCyIZmHbWSTRIxstHw==

"@sentry/types@7.84.0":
  version "7.84.0"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/types/-/types-7.84.0.tgz#e8db86c36c61659c3b2558f0aa8b6a073a756117"
  integrity sha512-VqGLIF3JOUrk7yIXjLXJvAORkZL1e3dDX0Q1okRehwyt/5CRE+mdUTeJZkBo9P9mBwgMyvtwklzOGGrzjb4eMA==

"@sentry/utils@7.81.1":
  version "7.81.1"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/utils/-/utils-7.81.1.tgz#42f3e77baf90205cec1f8599eb8445a6918030bd"
  integrity sha512-gq+MDXIirHKxNZ+c9/lVvCXd6y2zaZANujwlFggRH2u9SRiPaIXVilLpvMm4uJqmqBMEcY81ArujExtHvkbCqg==
  dependencies:
    "@sentry/types" "7.81.1"

"@sentry/utils@7.84.0":
  version "7.84.0"
  resolved "https://artif.cc.corp:443/artifactory/api/npm/cprdigital-npm-release/@sentry/utils/-/utils-7.84.0.tgz#32861d922fa31e86dd2863a1d9dfc5a369e98952"
  integrity sha512-qdUVuxnRBvaf05AU+28R+xYtZmi/Ymf8os3Njq9g4XuA+QEkZLbzmIpRK5W9Ja7vUtjOeg29Xgg43A8znde9LQ==
  dependencies:
    "@sentry/types" "7.84.0"

```

**Comment by krystofwoldrich** [comment] 2023-12-01 11:31
@genesiscz Thank you for the message,
I believe the issue was caused by the presence of `@sentry/browser@7.84.0`. Can you try your app with `7.81.1` as that's the version we ship with the RN SDK?

**Comment by thomasviaud** [comment] 2023-12-11 11:14
Same problem with 7.86.0

**Comment by krystofwoldrich** [comment] 2023-12-11 11:21
@thomasviaud Thank you for the message, please use the JS SDK version bundled with the RN SDK to avoid this.

**Comment by krystofwoldrich** [comment] 2023-12-15 12:31
Closing the issues as the error was caused by an incompatible Sentry JS SDK version.

**Closed by krystofwoldrich** 2023-12-15 12:31 UTC
Labels: Platform: React-Native
