### ISSUE TITLE
Correct way to deploy ReactNative + CodePush + Hermes to Sentry

### ISSUE THREAD

**Issue by witalobenicio** [getsentry/sentry-react-native#2244] opened 2022-05-09 20:00 UTC
When I send codepush bundle to sentry, it gives me the correct error, but the wrong line of code.
If I press "Minified" it show me what method throwed the error, but using bundle its not correct.

How is the correct way to upload when using CodePush and Hermes enabled?
Can we use the same way when sending an app to PlayStore and AppStore (native build)?

### Environment

How do you use Sentry?
self-hosted/on-premise

### Steps to Reproduce

1. appcenter codepush release-react -a MEU-TUDO/Meu-TUDO-iOS -d ${CODEPUSH_TEAM_ENV} -m -t "4.0.0" --token ${CODEPUSH_TOKEN_IOS} --sourcemap-output --output-dir build --disable-duplicate-release-error
2. sentry-cli react-native appcenter MEU-TUDO/Meu-TUDO-iOS ios ./build/CodePush --deployment ${CODEPUSH_TEAM_ENV} --dist ${SENTRY_DIST} --release-name ${SENTRY_RELEASE}

### Expected Result

Get the correct error and line of code.

### Actual Result

It show the error (e.g: undefined is not a function), but the wrong line of code.
Error happens in FAQ.js and sentry shows line 115 of NoEnrollment.js.

**Comment by marandaneto** [comment] 2022-05-10 08:13
@witalobenicio have you checked the docs page for CodePush and Hermes?

https://docs.sentry.io/platforms/react-native/manual-setup/hermes/
https://docs.sentry.io/platforms/react-native/manual-setup/codepush/

Which version of the Sentry self-hosted are you running? What's the version of the SDK? Can you provide a minimal reproduction example? thanks.

**Comment by witalobenicio** [comment] 2022-05-10 10:57
@marandaneto that's the problem. The docs doesn't say anything about CodePush and Hermes in the same process, only docs for separate ones.
If I release a codePush bundle with hermes, how is the correct approach?

Another question...if I'm building an app to go to AppStore (only native build without codepush), I would have to use this docs (https://docs.sentry.io/platforms/react-native/manual-setup/hermes/) ?

**Comment by witalobenicio** [comment] 2022-05-10 11:30
@sentry/react-native: 3.4.0
self hosted is latest

**Comment by witalobenicio** [comment] 2022-05-10 13:19
You can check an example in [this issue](https://sentry.meutudo.app/share/issue/6466a81b4e19422ebe5704f2069b4087/)

If you see the original it points to wrong line of code, and if you click on Minified, it shows the correct location `getFilteredResult`.

I thought it was because I was using codepush bundle in a native bundle. I've manually uploaded following [this doc](https://docs.sentry.io/platforms/react-native/manual-setup/hermes/) but the error remains showing wrong line of code.

**Comment by witalobenicio** [comment] 2022-05-10 14:58
@marandaneto nope. RAM bundles are disabled.

**Comment by witalobenicio** [comment] 2022-05-10 15:24
@marandaneto for some reason iOS stoped showing correct line/files locations too. Sometimes it crash in same place and show correct line/file and other time in same crash doesn't show.

**Comment by marandaneto** [comment] 2022-05-10 15:26
> @marandaneto for some reason iOS stoped showing correct line/files locations too. Sometimes it crash in same place and show correct line/file and other time in same crash doesn't show.

If you are uploading source maps to the very same `release` and `dist`, could be caching on the server, always test it out with a new `release` and `dist` in case you want to test things right away.

**Comment by marandaneto** [comment] 2022-05-13 09:29
Related issue https://github.com/getsentry/sentry-react-native/issues/2087

**Comment by marandaneto** [comment] 2022-05-13 09:31
@witalobenicio please check the https://github.com/getsentry/sentry-react-native/issues/2087#issuecomment-1125673168 comment, it might be the very same issue.

**Comment by marandaneto** [comment] 2022-06-11 05:40
@witalobenicio any news here, have you checked the other issue?

**Comment by witalobenicio** [comment] 2022-06-11 08:30
@marandaneto when I launch a update through codepush, sourcemaps are working great. I just send the CP and use the sentry cli to upload the generated sourcemaps by CP.
When sending my to Google play and Appstore, is just s native build, so the process to upload a source map is to generate the bundle, generate Hermes code, unit then and send to sentry. 
The problem now is when I sent to appstore. I never get the source map in the issue. It always show the there's a problem find the source.

**Comment by marandaneto** [comment] 2022-06-13 06:31
@witalobenicio can you link me to an issue that shows off this problem?

**Comment by witalobenicio** [comment] 2022-06-13 09:35
@marandaneto https://sentry.meutudo.app/share/issue/17f3c5e648a84d4986a2c56a70f1d711/

Reproducible demo is complicated, because its not related to the code itself, but the way I'm sending sourceMaps.

Let me show you the commands:

`npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output build/index.android.bundle --sourcemap-output build/index.android.bundle.packager.map`

`node_modules/hermes-engine/osx-bin/hermesc -O -emit-binary -output-source-map -out=build/index.android.bundle.hbc build/index.android.bundle`

`node node_modules/react-native/scripts/compose-source-maps.js build/index.android.bundle.packager.map build/index.android.bundle.hbc.map -o build/index.android.bundle.map`

`node_modules/@sentry/cli/bin/sentry-cli releases \
                files ${RELEASE_NAME} \
                upload-sourcemaps \
                --dist ${SENTRY_DIST} \
                --strip-prefix /path/to/project/root \
                --rewrite build/index.android.bundle build/index.android.bundle.map`
                
These are the commands I use to upload sourcemaps when I'm sending my app to PlayStore/AppStore (without CodePush). 

When sending just a codepush, it works without problems (but I use another way to send files):

`sentry-cli react-native appcenter <my-app> android ./build/CodePush --deployment ${CODEPUSH_TEAM_ENV} --dist ${SENTRY_DIST} --release-name ${RELEASE_NAME}`

**Comment by witalobenicio** [comment] 2022-06-13 16:54
I thought I just need to pass the release name after `files`. It would `files --release {RELEASE_NAME}` then?

**Comment by witalobenicio** [comment] 2022-06-14 09:09
I'll try that. I really doubt the problem is in the code, since through codepush works, but ok.

**Comment by witalobenicio** [comment] 2022-06-14 10:21
@marandaneto tried with a brand new project and same problem:

https://sentry.meutudo.app/share/issue/aacdb0ab7bc645bfac1483bda5667933/

**Comment by marandaneto** [comment] 2022-06-14 20:18
@witalobenicio thanks, will investigate it, just to be sure, you don't use [RAM Bundles](https://reactnative.dev/docs/ram-bundles-inline-requires) as well, right?

**Comment by witalobenicio** [comment] 2022-06-14 20:20
No RAM bundles

**Comment by marandaneto** [comment] 2022-06-14 21:37
So at least on Android, if I do:

Comment out the `sentry.gradle` import to not trigger the auto-upload.
`// apply from: "../../node_modules/@sentry/react-native/sentry.gradle"`

Assuming you're in the root folder.
```
cd android
./gradlew AssembleRelease
cd..
sentry-cli releases files $release upload-sourcemaps --dist $dist --strip-prefix /Users/myuser/Github/RNTests/RNTest0674 --rewrite android/app/build/generated/assets/react/release/index.android.bundle android/app/build/generated/sourcemaps/react/release/index.android.bundle.map
```

So in this case I didn't generate the bundles myself using `react-native bundle`, `hermesc` and `compose-source-maps`, but rather used the generated files by `AssembleRelease` itself.
I've tried using RN 0.67.4, everything worked out.

I guess `--strip-prefix` needs to be the full path of the root folder as well.

**Comment by witalobenicio** [comment] 2022-06-14 21:42
Hum...I'll try that in the next android build.
About iOS, what would be the process?

**Comment by marandaneto** [comment] 2022-06-14 21:46
> Hum...I'll try that in the next android build. About iOS, what would be the process?

I will test that tomorrow, thanks for the patience.

**Comment by witalobenicio** [comment] 2022-06-14 21:47
Nice, thanks.

**Comment by marandaneto** [comment] 2022-06-15 10:34
So I've tried to reverse engineering the script for iOS and I did that:

```
npx react-native bundle --platform ios --dev false --entry-file index.js --reset-cache --bundle-output main.jsbundle --sourcemap-output main.jsbundle.packager.map --minify false
node_modules/hermes-engine/osx-bin/hermesc -O -emit-binary -output-source-map -out=main.jsbundle.hbc main.jsbundle
node node_modules/react-native/scripts/compose-source-maps.js main.jsbundle.packager.map main.jsbundle.hbc.map -o main.jsbundle.map
```

And uploaded the files:

`sentry-cli releases files $release upload-sourcemaps --dist $dist --strip-prefix $fullRootFolder --rewrite main.jsbundle main.jsbundle.map`

It kinda worked, but I need to double-check why line numbers are so wrong.

<img width="1014" alt="Screenshot 2022-06-15 at 12 33 34" src="https://user-images.githubusercontent.com/5731772/173807162-9810fda2-8fd5-4a66-b183-95139185bb7e.png">

**Comment by marandaneto** [comment] 2022-06-20 06:53
@witalobenicio would you like to raise an issue on the https://github.com/facebook/react-native/ repo asking if we're calling the right commands and passing the right arguments?
I believe this changed over the versions, it used to work and now it's kinda flaky depending on the version.

Based on my research, everything works as expected when it's being automatically uploaded since we use the generated files, so it's not a symbolication nor SDK bug, but rather the documentation to manually generate and upload the files.

**Comment by kopax-polyconseil** [comment] 2022-06-29 13:38
Hello, I can see a bunch of PR and discussion regarding sourcemaps for code push when using hermes.

We are unable to have source maps displayed in Sentry for all our code push (iOS and Android), do you have a working documentation we can use to solve that problem ? What is your current configuraiton @witalobenicio ?

Thanks a lot for sharing !

**Comment by marandaneto** [comment] 2022-07-01 08:18
So I've summarized the changes identified while debugging and pairing up with members of the RN community.
https://github.com/getsentry/sentry-docs/pull/5241
This was tested using RN 0.67 and 0.68.

Can one of you test it out @witalobenicio and @kopax-polyconseil ?
Thanks.

**Comment by kopax-polyconseil** [comment] 2022-07-01 08:24
Hello, I have just warned my PO, it will be prioritized and I'll keep you
updated very soon for the test results.

Thanks again for your help !

**Comment by marandaneto** [comment] 2022-07-07 08:06
Closing the issue, as it seems like the original issue has been resolved.
Please do not hesitate to ping me if it is still relevant, and I will happily reopen and work on it.
Cheers!

**Closed by marandaneto** 2022-07-07 08:06 UTC
Labels: code-push, Status: Awaiting Response, hermes, Status: Backlog, source-maps, Effort: Medium, Impact: Large, Platform: React-Native

**Comment by kopax-polyconseil** [comment] 2022-07-13 15:55
So after some tests, I was able to get the proper source maps for iOS build hard :tada: 

However code push doesn't work better, for example, on the same app after code push and new source map uploaded with the same technique : 

## iOS

![image](https://user-images.githubusercontent.com/77674046/178776441-f3ae4149-e3b1-40b6-bff0-30385de23d46.png)
![image](https://user-images.githubusercontent.com/77674046/178776556-a902f985-ceb8-4804-9767-081a243bdfaa.png)

## Android

![image](https://user-images.githubusercontent.com/77674046/178777410-d002be05-980a-45cf-8c8b-1afdec8cdc86.png)
![image](https://user-images.githubusercontent.com/77674046/178777508-fe272d61-e983-4888-93e7-bcc0571ccce7.png)


This is [how we generate the sourcemaps](https://github.com/pass-culture/pass-culture-app-native/pull/3248/commits/aac10561bc77a76ce4fee2933815934a4269818a#diff-38f8b59ae2582ff01f0c8420dd35183fed02d47b44c0b32d8ed53f14920763c4R26-R56), we used all of your recommendations, but still can't use source map with Android/iOS app after code push, which we often use.

It seemed that code push issue was not fixed, may we perhaps reopen my issue, this one or should I create a new one?

**Comment by kopax-polyconseil** [comment] 2022-07-15 09:59
I have created a new issue [here](https://github.com/getsentry/sentry-react-native/issues/2372) regarding that matter.
