### ISSUE TITLE
Metro Bundler throws error on iOS: Unable to resolve module `./index.ios`.

### ISSUE THREAD

**Issue by MathieuUrstein** [getsentry/sentry-react-native#790] opened 2019-12-11 17:56 UTC
With sentry-cli installed, on ios, the metro bundler tries to reach the bundle by expecting it to have a `.ios` extension, while for a lot of people, there is none.

Metro bundler logs:
```
"GET /index.ios.bundle?platform=ios&dev=true HTTP/1.1" 500 1835 "-" "sentry-cli/1.49.0"
Error: Unable to resolve module `./index.ios` from `/Users/user/project/.`: The module `./index.ios` could not be found from `/Users/user/project/.`. Indeed, none of these files exist:
  * `/Users/user/project/index.ios(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/user/project/index.ios/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
```

As you can see the command does : `GET /index.ios.bundle` while `GET /index.bundle` would be enough since `.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx` would be tried.

This call may be based on `node_modules/@sentry/react-native/ios/Sentry/Tests/Resources/ReactNative.json` which contains those kind of lines:
```
...
{
   "lineNumber": 12,
   "file": "http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false",
   "methodName": "value",
   "column": 939
},
...
```

It may also be related to [this file](https://github.com/getsentry/sentry-cli/blob/089cd2bffa5dd90bb23fa0b12ad3bc10dd5d2459/src/commands/react_native_xcode.rs) which contains lots of `index.ios`

**Comment by HazAT** [comment] 2020-03-23 08:20
@lwmouneyrac Please instead of running `react-native bundle` use the `sentry-cli react-native xcode --force-foreground ../node_modules/react-native/scripts/react-native-xcode.sh` command. We do some additional things there.

Also, make sure to export the sentry.properties file and point it to the right location.
```
export SENTRY_PROPERTIES=sentry.properties
sentry-cli react-native xcode --force-foreground ../node_modules/react-native/scripts/react-native-xcode.sh
```
See if this works.

**Comment by lwmouneyrac** [comment] 2020-03-24 09:55
_react-native bundle_ comes from https://docs.sentry.io/platforms/react-native/sourcemaps/

When I tried your suggestion in the terminal (which is the same command than the one run by xcode apart from --force-foreground)
```
jerome@Jeromes-MacBook-Pro my-rn-typescript-project % sentry-cli react-native xcode --force-foreground ../node_modules/react-native/scripts/react-native-xcode.sh                     

error: Need to run this from Xcode

Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
Please attach the full debug log to all bug reports.
jerome@Jeromes-MacBook-Pro my-rn-typescript-project %
```

**Comment by HazAT** [comment] 2020-03-24 10:15
@lwmouneyrac Sorry, please add `CONFIGURATION=release` in front of the command
`CONFIGURATION=release sentry-cli react-native xcode --force-foreground ../node_modules/react-native/scripts/react-native-xcode.sh`

**Comment by lwmouneyrac** [comment] 2020-03-25 04:42
@HazAT Thanks Daniel.

When I run it, it is saying that I am forbidden to write in the root folder which is normal.

```
jerome@Jeromes-MacBook-Pro ios % CONFIGURATION=release sentry-cli react-native xcode --force-foreground ../node_modules/react-native/scripts/react-native-xcode.sh --verbose
+ DEST=/
+ [[ release = *Debug* ]]
+ [[ -n '' ]]
+ case "$CONFIGURATION" in
+ DEV=false
+++ dirname /Users/jerome/Documents/my-rn-typescript-project/node_modules/react-native/scripts/react-native-xcode.sh
++ cd /Users/jerome/Documents/my-rn-typescript-project/node_modules/react-native/scripts/..
++ pwd
+ REACT_NATIVE_DIR=/Users/jerome/Documents/my-rn-typescript-project/node_modules/react-native
+ PROJECT_ROOT=/Users/jerome/Documents/my-rn-typescript-project/node_modules/react-native/../..
+ cd /Users/jerome/Documents/my-rn-typescript-project/node_modules/react-native/../..
+ '[' -z '' ']'
+ export NVM_DIR=/Users/jerome/.nvm
+ NVM_DIR=/Users/jerome/.nvm
+ [[ -s index.ios.js ]]
+ ENTRY_FILE=index.js
+ [[ -s /Users/jerome/.nvm/nvm.sh ]]
++ command -v brew
+ [[ -x /usr/local/bin/brew ]]
++ brew --prefix nvm
+ [[ -s /usr/local/Cellar/nvm/0.35.2/nvm.sh ]]
+ [[ -x /Users/jerome/.nodenv/bin/nodenv ]]
++ command -v brew
+ [[ -x /usr/local/bin/brew ]]
++ brew --prefix nodenv
+ [[ -x /usr/local/Cellar/nodenv/1.3.1/bin/nodenv ]]
+ [[ ! -x node ]]
+ [[ -d /Users/jerome/.anyenv/bin ]]
+ '[' -z /usr/local/lib/node_modules/@sentry/cli/sentry-cli ']'
+ '[' -z '' ']'
+ export NODE_ARGS=
+ NODE_ARGS=
+ '[' -z '' ']'
+ export CLI_PATH=/Users/jerome/Documents/my-rn-typescript-project/node_modules/react-native/cli.js
+ CLI_PATH=/Users/jerome/Documents/my-rn-typescript-project/node_modules/react-native/cli.js
+ '[' -z '' ']'
+ BUNDLE_COMMAND=bundle
+ [[ -z '' ]]
+ CONFIG_ARG=
+ type /usr/local/lib/node_modules/@sentry/cli/sentry-cli
+ BUNDLE_FILE=//main.jsbundle
+ /usr/local/lib/node_modules/@sentry/cli/sentry-cli /Users/jerome/Documents/my-rn-typescript-project/node_modules/react-native/cli.js bundle --entry-file index.js --platform ios --dev false --reset-cache --bundle-output //main.jsbundle --assets-dest /
warning: the transform cache was reset.
Loading dependency graph, done.
info Writing bundle output to:, //main.jsbundle
info Writing sourcemap output to:, //main.jsbundle.map
error EROFS: read-only file system, open '//main.jsbundle'. Run CLI with --verbose flag for more details.
+ [[ false != true ]]
+ [[ ! -f //main.jsbundle ]]
+ echo 'error: File //main.jsbundle does not exist. This must be a bug with'
error: File //main.jsbundle does not exist. This must be a bug with
+ echo 'React Native, please report it here: https://github.com/facebook/react-native/issues'
React Native, please report it here: https://github.com/facebook/react-native/issues
```

**Comment by lwmouneyrac** [comment] 2020-03-26 08:03
@HazAT I noticed that when I add CONFIGURATION=release in Xcode "Bundle React Native code and images" then the two jsbundle files are visible in the artifacts screen otherwise there were not appearing before that (regardless I added --force-foreground) - or maybe there are some cache system in Sentry and by an unlikelycoincidence, it got refreshed as soon I launch the app the third time with CONFIGURATION=release

Anyway in all three cases the issue report is the same (with metro saying ::1 - - [26/Mar/2020:07:52:45 +0000] "GET /LoginScreen.tsx HTTP/1.1" 404 154 ):

<img width="868" alt="Screen Shot 2020-03-26 at 3 58 25 pm" src="https://user-images.githubusercontent.com/61490093/77623468-1b6cd800-6f7b-11ea-9cc3-79e1fdf9f2b6.png">

**Comment by HazAT** [comment] 2020-03-26 10:34
@lwmouneyrac I took the time now to try it with ignite.

Here is what I did:

1. Installed ignite
2. `ignite new igniteapp`
3. `cd igniteapp`
4. `yarn add @sentry/react-native`
5. `yarn sentry-wizard -i reactNative -p ios android`
6. Added to `index.js`
```javascript
import * as Sentry from "@sentry/react-native"

Sentry.init({
  dsn: 'DSN'
})
```

7. Added to `demo-screen.tsx`
```javascript
<Text style={LOVE} text="Made with" onPress={() => {
  throw new Error("ignite test")
}}/>
```
8. Open `ios/igniteapp.xcworkspace`
9. Build the app in release mode 
![image](https://user-images.githubusercontent.com/363802/77632832-d763de00-6f4e-11ea-831a-76b77f1bbe64.png)

10. Stop Xcode, Start the app new and click on the button to crash the app, the next screenshot shows the result.

![image](https://user-images.githubusercontent.com/363802/77632516-64f2fe00-6f4e-11ea-84a0-a7eb39bcfb27.png)

This looks correct, everything is working as expected and the stack trace is fine.
I am really not sure what the problem is.


PS:
I tried to run the app in debug mode and was able to get the same result as you did.

![image](https://user-images.githubusercontent.com/363802/77633146-52c58f80-6f4f-11ea-9028-3dbaf03ec216.png)

After a bit of debugging I found the issue, this is the PR fixing it: https://github.com/getsentry/sentry-react-native/pull/806

Now it also works in debug
![image](https://user-images.githubusercontent.com/363802/77636553-95d63180-6f54-11ea-864a-dce6460ee22f.png)

I am closing this issue, will release `1.3.4` today.

**Closed by HazAT** 2020-03-26 10:34 UTC

**Comment by lwmouneyrac** [comment] 2020-03-27 01:26
I updated to 1.3.5 and it worked straight away! Thanks a lot Dan.
