### ISSUE TITLE
Some errors immediately after installing the app leave incorrect logs

### ISSUE THREAD

**Issue by lafest** [getsentry/sentry-react-native#2700] opened 2022-12-16 03:16 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 4.8.0

**`react-native` version:** 69.6.0

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue](https://sentry.io/organizations/ridi/releases/22.114.6.0_1534/?issuesType=all&project=4504252256157696)

---
**I have following issue:**

[Description]
After app install, some initial crashes point wrong line for the error. sentry error links under here are occured in same line, but they points another lines.
[points wrong line](https://sentry.io/organizations/ridi/issues/3782518964/?project=4504252256157696&referrer=release-issue-stream)
[correct error](https://sentry.io/organizations/ridi/issues/3782562710/?project=4504252256157696&referrer=release-issue-stream)

main.jsbundle has only 2437 lines, but incorrect error points 186577 line.

```
Error: onPressCategoryListButton test
  at onPressCategoryListButton(app:///main.jsbundle:186577:26)
  at _performTransitionSideEffects(app:///main.jsbundle:20901:22)
  at _receiveSignal(app:///main.jsbundle:20843:45)
  at onResponderRelease(app:///main.jsbundle:20689:34)
  at apply(native)
  at invokeGuardedCallbackImpl(app:///main.jsbundle:2653:17)
  at apply(native)
  at invokeGuardedCallback(app:///main.jsbundle:2673:36)
  at apply(native)
  at invokeGuardedCallbackAndCatchFirstError(app:///main.jsbundle:2677:32)
  at executeDispatch(app:///main.jsbundle:2698:44)
  at executeDispatchesAndReleaseTopLevel(app:///main.jsbundle:3373:50)
  at forEach(native)
  at forEachAccumulated(app:///main.jsbundle:2925:37)
  at anonymous(app:///main.jsbundle:3401:27)
  at batchedUpdatesImpl(app:///main.jsbundle:8569:16)
  at batchedUpdates(app:///main.jsbundle:3359:32)
  at _receiveRootNodeIDEvent(app:///main.jsbundle:3387:19)
  at receiveTouches(app:///main.jsbundle:3439:32)
  at apply(native)
  at __callFunction(app:///main.jsbundle:2296:36)
  at anonymous(app:///main.jsbundle:2117:31)
  at __guard(app:///main.jsbundle:2247:15)
  at callFunctionReturnFlushedQueue(app:///main.jsbundle:2116:21)
```

**Steps to reproduce:**
- Step 1. manually uploaded sourcemap. (using `sentry-cli react-native appcenter`)
- Step 2. install app.
- Step 3. make crash.
- Step 4. crash points wrong line number.
- Step 5. after some wrong errors, crashes are reported as correct error. but, errors that are incorrectly reported are not migrated to correct error report.
- Step 6. if we delete and reinstall app, this step 5 reproduces.

**Actual result:**

[Actual result](https://sentry.io/organizations/ridi/issues/3782518964/?project=4504252256157696&referrer=release-issue-stream)

**Expected result:**

[Expected result](https://sentry.io/organizations/ridi/issues/3782562710/?project=4504252256157696&referrer=release-issue-stream)

**Comment by krystofwoldrich** [comment] 2022-12-16 11:24
Hi, thank you for the information, could you send a minimal reproducible example, a simple app on which we can debug the issue?

**Comment by lafest** [comment] 2022-12-19 05:49
I could not reproduce with sample app 😭 

> main.jsbundle has only 2437 lines, but incorrect error points 186577 line.

I think this might be hint about this error.
Can you explain any other examples that stacktrace points not existing line?

And, what is difference with `sentry-cli releases files <release> upload-sourcemaps` and `sentry-cli react-native appcenter`?
because `sentry-cli react-native appcenter` requires folder(`./build/Codepush`), i could not guess why this process requires folder name.

**Comment by krystofwoldrich** [comment] 2023-01-03 17:01
`sentry-cli react-native appcenter`[ resolves the release name and source maps paths automatically](https://docs.sentry.io/clients/react-native/codepush/) for you. The folder path is necessary for the automatic info resolution.

`sentry-cli releases files <release> upload-sourcemaps` upload source maps files from provided paths to the manually selected release.

So if you create a new project and set it up similarly to your original project you can't reproduce the issue?

**Comment by lafest** [comment] 2023-01-04 05:29
I succeeded in finding the cause of this issue and resolving this. I will share my debugging history soon.

**Comment by krystofwoldrich** [comment] 2023-01-04 09:52
Thank you for the short summary. I will close the issue for now. But please share the detailed information and we can reopen this or create a new issue if there is something we can improve/change.

**Closed by krystofwoldrich** 2023-01-04 09:52 UTC
Labels: Platform: React-Native
