### ISSUE TITLE
IOS Build + SDK 5.11+

### ISSUE THREAD

**Issue by AlaaInflyter** [getsentry/sentry-react-native#3402] opened 2023-11-16 16:09 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [x]  iOS
- [ ]  Android

**SDK:**
- [5.13.0]  `@sentry/react-native` (>= 1.0.0)

**SDK version:** 5.13.0

**`react-native` version:** 0.72.3

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [x]  sentry.io (SaaS)
- [ ]  on-premise

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
});
```

---
**I have the following issue:**
Since release 5.11, the manual build installation changed to the following:
```
WITH_ENVIRONMENT="../node_modules/react-native/scripts/xcode/with-environment.sh"
REACT_NATIVE_XCODE="../node_modules/react-native/scripts/react-native-xcode.sh"
SENTRY_XCODE="../node_modules/@sentry/react-native/scripts/sentry-xcode.sh"
BUNDLE_REACT_NATIVE="/bin/sh $SENTRY_XCODE $REACT_NATIVE_XCODE"

/bin/sh -c "$WITH_ENVIRONMENT \"$BUNDLE_REACT_NATIVE\""
```

Starting a build with XCode after this change results in the following:
<img width="1043" alt="Capture d’écran 2023-11-16 à 17 08 49" src="https://github.com/getsentry/sentry-react-native/assets/137527627/4e8f3ba8-6891-45c5-acae-b738f8de12ab">

Do you guys have any clue ?

**Steps to reproduce:**
- Setup the new way of configuring Sentry
- Run a build

**Actual result:**

Build failed with the error above

**Expected result:**

Build successful

**Comment by krystofwoldrich** [comment] 2023-11-17 09:44
Looks like the Sentry CLI in `../node_modules/@sentry/cli` is older than `2.21.2`.

If you installed `@sentry/cli` update it to the latest version.

Otherwise, can you try to reinstall `node_modules`.

```bash
rm -rf node_modules
yarn
```

**Comment by AlaaInflyter** [comment] 2023-11-17 09:53
@krystofwoldrich thanks for the answer !
I tried (I'm using pnpm btw).
FYI, I haven't manually installed any cli, only dependencies (monorepo with nextjs + sentry, and react-native + sentry)

The thing is, from what I can see, I have 2 sentry clis in my modules:

- `node_modules/@sentry/cli:` this one is indeed outdated and doesn't support no-auto-release (1.xx.xx)
- `node_modules/@sentry/react-native/node_module/@sentry/cli`: this one is the correct version (2.21.3)

The command in xcode uses the second one apparently, if we check the **sentry-xcode.sh** script:
`[ -z "$SENTRY_CLI_EXECUTABLE" ] && SENTRY_CLI_EXECUTABLE="../node_modules/@sentry/cli/bin/sentry-cli"
`
 so it should work shouldn't it ?

**Comment by krystofwoldrich** [comment] 2023-11-17 10:02
The relative path to the Sentry CLI resolves from the Xcode project, not from the sh script as it might seem. So it will use the `1.xx.xx` version.

You can add `export SENTRY_CLI_EXECUTABLE="../node_modules/@sentry/react-native/node_module/@sentry/cli/bin/sentry-cli"` to `.xcode.env` to force `sentry-xcode.sh` to use the cli shipped with the RN SDK.

**Comment by AlaaInflyter** [comment] 2023-11-17 10:59
@krystofwoldrich 
I tried changing the cli path, now it seems like a sourcemap directory issue 🤔 

The executed command is:

```
 .../monorepo/node_modules/@sentry/cli/sentry-cli .../monorepo/node_modules/react-native/cli.js bundle --entry-file .../monorepo/apps/inflyter-mobile/ios/../src/main.tsx --platform ios --dev false --reset-cache --bundle-output '/Users/user/Library/Developer/Xcode/DerivedData/app-fhzztsroouvmwugrkjcxmkhqpane/Build/Products/Dev debug-iphonesimulator/main.jsbundle' --assets-dest '/Users/user/Library/Developer/Xcode/DerivedData/app-fhzztsroouvmwugrkjcxmkhqpane/Build/Products/Dev debug-iphonesimulator/App Dev.app' --sourcemap-output /Users/user/Library/Developer/Xcode/DerivedData/app-fhzztsroouvmwugrkjcxmkhqpane/Build/Products/Dev debug-iphonesimulator/Dev --minify false
```

But then the result is:


```
info Writing bundle output to:, /Users/user/Library/Developer/Xcode/DerivedData/app-fhzztsroouvmwugrkjcxmkhqpane/Build/Products/Dev debug-iphonesimulator/main.jsbundle
```

```
info Writing sourcemap output to:, /Users/user/Library/Developer/Xcode/DerivedData/app-fhzztsroouvmwugrkjcxmkhqpane/Build/Products/Dev
```

Why is it writing to Products/Dev instead of following the arg in the command `(/Products/Dev debug-iphonesimulator/Dev)` ?
Because then the **compose-sourcemaps.sh** doesn't find `/Products/Dev debug-iphonesimulator/Dev` and fails:
```
Error: ENOENT: no such file or directory, open '/Users/user/Library/Developer/Xcode/DerivedData/app-fhzztsroouvmwugrkjcxmkhqpane/Build/Products/Dev debug-iphonesimulator/Dev'
```

**Comment by krystofwoldrich** [comment] 2023-11-17 11:34
How do you specify the sourcemap path?

The issue is the space in the sourcemap path.
Context of the RN Scripts https://github.com/facebook/react-native/blob/fa89dd68b0f64acb68c45912d39fe9beed4e13cf/packages/react-native/scripts/react-native-xcode.sh#L134

Can you change the path so there is no white space on the path?

**Comment by AlaaInflyter** [comment] 2023-11-17 12:06
I don't specify anything, everything is done automatically by RN/Sentry 🤔

**Comment by krystofwoldrich** [comment] 2023-11-17 12:14
🤔 Could you share the whole Xcode log, so we can see what was `SOURCEMAP_FILE` set to?

**Comment by AlaaInflyter** [comment] 2023-11-17 12:31
I can see this in logs:

```
export SOURCEMAP_FILE=/Users/user/Library/Developer/Xcode/DerivedData/app-fhzztsroouvmwugrkjcxmkhqpane/Build/Intermediates.noindex/InflyterMobile.build/Dev debug-iphonesimulator/InflyterMobile.build/DerivedSources/main.jsbundle.map
```

**Comment by krystofwoldrich** [comment] 2023-11-17 13:44
Yes, the RN Build script can't handle the space at the moment. ([related code](https://github.com/facebook/react-native/blob/fa89dd68b0f64acb68c45912d39fe9beed4e13cf/packages/react-native/scripts/react-native-xcode.sh#L134))

You can add `export SOURCEMAP_FILE=../main.jsbundle.map` to your `.xcode.env` that will create the source map in root of your RN project.

**Comment by AlaaInflyter** [comment] 2023-11-17 14:11
Doesn't seem to be that simple.
<img width="245" alt="Capture d’écran 2023-11-17 à 15 10 21" src="https://github.com/getsentry/sentry-react-native/assets/137527627/cc9e75ac-b655-48c9-ba3d-ab5c53880ddf">
These env vars here still keep the default value so I guess there is more than 1 env var to set.

**Comment by krystofwoldrich** [comment] 2023-11-17 15:38
Can you change the build configuration name from `Dev debug` to `Dev-debug`? Or something else without the space?

**Comment by krystofwoldrich** [comment] 2023-11-17 15:39
I'll close this issue since the SDK does not cause it. But feel free to post your findings.

**Closed by krystofwoldrich** 2023-11-17 15:39 UTC
Labels: Platform: React-Native

**Comment by AlaaInflyter** [comment] 2023-11-17 15:59
Naturally that's what I did.
But I shouldn't have to change my Product name, scheme name, config name and everything that contains a space just so Sentry could work 🤔 
Now, the only issue I have left is that after using using sentry script in the build phase instead of the classic react-native script, my build is always a production build (even when used with a debug configuration), it seems like my node_env is getting overriden and `__DEV__` is always `false`.
@krystofwoldrich Do you have any idea why this might be the case ?

**Comment by krystofwoldrich** [comment] 2023-11-17 16:58
> But I shouldn't have to change my Product name, scheme name, config name, and everything that contains a space just so Sentry could work 🤔

I agree, but I would like to note that `SOURCEMAP_FILE` is an RN flag, not Sentry. Nevertheless, we can try to fix this in RN.

> Now, the only issue I have left is that after using using sentry script in the build phase instead of the classic react-native script, my build is always a production build (even when used with a debug configuration), it seems like my node_env is getting overriden and __DEV__ is always false.

Does your configuration name include `Debug`? That's how RN Tooling determinates if create dev or prod bundle.
https://github.com/krystofwoldrich/react-native/blob/d09c02f9e2d468e4d0bde51890e312ae7003a3e6/packages/react-native/scripts/react-native-xcode.sh#L36

**Comment by AlaaInflyter** [comment] 2023-11-17 17:29
That I know, but I didn't know it was case sensitive, thanks !
Now, (last step hopefully 😆) I have the classic:
```
Exception	NSException *	"No bundle URL present.\n\nMake sure you're running a packager server or have included a .jsbundle file in your application bundle."	0x0000600000c742d0
```

**Comment by AlaaInflyter** [comment] 2023-11-17 17:51
That I know, but I didn't know it was case sensitive, thanks !

So to conclude, for anyone having an issue like this, **you gotta rid of any space you have** (product_name, schemes, configurations, ...)
