### ISSUE TITLE
Could not invoke RNSentry.fetchNativeAppStart

### ISSUE THREAD

**Issue by zvitek** [getsentry/sentry-react-native#3498] opened 2024-01-06 14:53 UTC
**OS:**
- [ ]  Windows
- [x]  MacOS
- [ ]  Linux

**Platform:**
- [ ]  iOS
- [x]  Android

**SDK:**
- [x]  `@sentry/react-native` (>= 1.0.0)
- [ ]  `react-native-sentry` (<= 0.43.2)

**SDK version:** 5.15.2

**`react-native` version:** 0.72.5

**Are you using Expo?**
- [ ]  Yes
- [x]  No

**Are you using sentry.io or on-premise?**
- [ ]  sentry.io (SaaS)
- [x]  on-premise

**If you are using sentry.io, please post a link to your issue so we can take a look:**

[Link to issue]

**Configuration:**

(`@sentry/react-native`)
```
Sentry.init({
  dsn: 'https://...@sentry.io/...'
  // other options
});
```

---
**I have the following issue:**

The application build process will be fine. However, the application crashes after starting with error 
`java.lang.RuntimeException: Could not invoke RNSentry.fetchNativeAppStart`

**Comment by facugaich** [comment] 2024-01-08 15:07
I think this is a duplicate of #3497

**Comment by kahest** [comment] 2024-01-09 09:37
Closing this as duplicate of #3497

**Closed by kahest** 2024-01-09 09:37 UTC
Labels: Platform: React-Native, Waiting for: Product Owner
