### ISSUE TITLE
Late Init of sentry

### ISSUE THREAD

**Issue by daniel-johns-99** [getsentry/sentry-react-native#3726] opened 2024-04-02 08:58 UTC
I read in the documentation that it's better to retrieve the [Sentry DSN dynamically](https://docs.sentry.io/product/sentry-basics/concepts/dsn-explainer/#dsn-utilization) rather than embedding it in the app. But if I wait to fetch this configuration dynamically, I might miss events that occur during the wait, especially during app startup. Am I understanding this correctly? If I initialize Sentry 500ms after app start, will I lose events from the first 500ms?

Alternatively, is there a way to change configuration values after initialization? Specifically, I want to dynamically retrieve values for tracesSampleRate, sampleRate, and ignoreErrors, but I don't want to miss any events while waiting for these values before calling sentry.init. I know I can achieve this with an event processor, but I'd prefer using these built-in options before resorting to a custom solution.

Overall, I'm trying to understand the impact of delaying Sentry initialization versus initializing it immediately on app start and then adjusting configuration values once they're received (If that is even possible)

**Comment by krystofwoldrich** [comment] 2024-04-02 10:19
Hi @daniel-johns-99,
thank you for the message,

you understand it correctly, when the SDK initialization is delayed all events (errors) that happened before the init will be lost.

Generally, when changing the options we recommend closing and re-initializing the SDK. As the options are used during the initialization process and later changes might not have the desired effect, a module where the value is used might not be included.

Typically `undefined` and `0` lead to the exclusion of a module during init.

**Comment by daniel-johns-99** [comment] 2024-04-03 08:55
> Generally, when changing the options we recommend closing and re-initializing the SDK.

Are there any impacts on doing this?

**Comment by krystofwoldrich** [comment] 2024-04-04 11:32
Closing the SDK flushes events which are currently being processed, how this takes depends on the current state of the app, the amount of events and the connection speed.

**Comment by krystofwoldrich** [comment] 2024-04-19 11:57
Closing this due to inactivity. If this is still an issue feel free to comment here or open a new issue if the context changed.

**Comment by realkosty** [comment] 2024-05-04 03:40
> Closing the SDK flushes events which are currently being processed, how this takes depends on the current state of the app, the amount of events and the connection speed.

@krystofwoldrich is `close()` synchronous or will `close(); init();` result in potential loss of events?

I see that javascript supports [`then()` + timeout](https://docs.sentry.io/platforms/javascript/configuration/draining/) while [Shutdown and Draining page for React Native](https://docs.sentry.io/platforms/react-native/configuration/draining/) looks generic and suggests `Sentry.flush()` (presumably right before `close()`?).

**Comment by krystofwoldrich** [comment] 2024-05-06 18:28
@realkosty 

Yes, errors between the `close()` and `init()` would be lost. The same way as any errors before the SDK is initialized the first time.

The `Sentry.close()` calls `flush()` internally. 

Yes, the [Shutdown and Draining page for React Native](https://docs.sentry.io/platforms/react-native/configuration/draining/)  is missing the `close()` function.

**Comment by realkosty** [comment] 2024-05-07 15:18
@krystofwoldrich would it be a valid feature request to have an api similar to JS SDK or is this not possible in React Native because of architectural limitations?
```
Sentry.close(2000).then(function () { // ...
```

**Comment by krystofwoldrich** [comment] 2024-05-08 14:51
@realkosty We already have it, without the timeout option.

```js
import * as Sentry from `@sentry/react-native`;

Sentry.close(/* RN doesn't have the timeout property */).then(function () {});
```

**Comment by realkosty** [comment] 2024-05-08 17:48
@krystofwoldrich 
Customer is reporting that 

> Calling `Sentry.close().finally(() => Sentry.init(options))` is resulting in this error from Sentry "Transport Disabled". As a result, app start and other transactions are failing to send.

any idea why that could be happening?

**Comment by krystofwoldrich** [comment] 2024-05-17 15:36
I'm not sure, I will try to reproduce it and update my post here.

**Comment by daniel-johns-99** [comment] 2024-05-22 05:31
@realkosty As a question. If I reinit sentry as proposed. Does it track as a new session in the release health? In addition what happens to any other transactions which are already open. Are they lost? 
I seem to be losing the mobile performance metrics of time to start by doing the reinit of Sentry

**Comment by krystofwoldrich** [comment] 2024-05-27 10:05
Hi @daniel-johns-99,
when the SDK is re-initialized, the currently running transactions will be lost.

A new session will be created.

Note that `Sentry.close()` closes the native SDKs, therefore when calling `Sentry.init(options)` the options should enabled the auto native init function or the native SDKs should be initialized manually as well.

**Comment by krystofwoldrich** [comment] 2024-06-14 11:45
Closing this due to inactivity. If this is still an issue feel free to comment here or open a new issue if the context changed.

**Closed by krystofwoldrich** 2024-06-14 11:45 UTC
Labels: Platform: React-Native, Waiting for: Community
